### ISSUE TITLE
Rename 'examples' to 'templates'

### ISSUE THREAD

**Issue by ryall** [heptio/velero#1001]
The term "examples" is a term I would associate with complete and runnable manifests. However there are many placeholders inside them currently, and this confused me initially. I was not expecting to have to change them to get things running. 

I think it would make a lot more sense to call them "templates".

**Comment by ncdc** [comment]
cc @Bradamant3 for your thoughts

**Comment by skriss** [comment]
We've removed the templated static YAML and replaced with the `velero install` command. What's left are truly examples. Closing this issue.
