### ISSUE TITLE
New metrics for backup deletion attempt/failure/success

### ISSUE THREAD

**Issue by mwieczorek** [heptio/velero#1059]
Ark provides metrics for f.e. failed backups and we can use it to display graphs in Grafana or make some alerts.
But in case of failed backup deletion, we don't have such metrics.

Also, Ark provides `ark_backup_tarball_size_bytes` but no corresponding metric for the PV snapshots size.

Would it be propose to add new metrics:

```
# TYPE ark_backup_delete_attempt_total counter
# TYPE ark_backup_delete_failure_total counter
# TYPE ark_backup_delete_success_total counter

# TYPE ark_backup_snapshots_size_bytes gauge
```

**Comment by skriss** [comment]
I split the snapshot size metric idea out into its own issue, #1309, so updating this one to just focus on deletion attempt/failure/success.
