### ISSUE TITLE
In-progress backups have no start timestamp

### ISSUE THREAD

**Issue by skriss** [heptio/velero#1060]
Steps to reproduce:
- create a backup -- ark backup create foo
- list all backups -- ark backup get
- see that backup `foo` is in progress, and has no start timestamp

The value displayed here is `.status.startTimestamp`, which is set on L386: https://github.com/heptio/ark/blob/master/pkg/controller/backup_controller.go#L386

The `runBackup` function is called on L202: https://github.com/heptio/ark/blob/master/pkg/controller/backup_controller.go#L202

Which is *AFTER* the backup has been patched to `InProgress` (on L182): https://github.com/heptio/ark/blob/master/pkg/controller/backup_controller.go#L182

I think we should probably set `.status.startTimestamp` at the same time as we set the phase to `InProgress`, so that when we patch, both of those values get persisted.

**Comment by ncdc** [comment]
👍

**Comment by yastij** [comment]
@ncdc - we are seeing this behaviour in some of our clusters, can you assign me ?

Thanks

**Comment by ncdc** [comment]
@yastij assigned, thanks!

**Comment by ncdc** [comment]
@yastij you still planning on doing this?

**Comment by yastij** [comment]
Yes, shipping it while flying to kubeCon, sorry for the delay

**Comment by yastij** [comment]
@skriss - sorry I got a bit overwhelmed with GH notifications. I’ll send a PR Tuesday.
