### ISSUE TITLE
New gauge metrics for number of existing backups and restores

### ISSUE THREAD

**Issue by mwieczorek** [heptio/velero#1077]
Ref: [thread on google groups](https://groups.google.com/forum/#!topic/heptio-ark/8mECN2CuQ14)

**Describe the solution you'd like**
I'd like to get new metrics from ark:
- [gauge] number of existing backups based on the number of CRDs (f.e. to track how many backups do we have and if they are deleted properly)
- [gauge] number of existing restores based on the number of CRDs (this one I don't have a use case, rather to make it consistent with backup metrics)

Another metric which can be valuable for me (but maybe questionable for you, I can move it to another issue for discussion or 'reject'):
- [gauge] size of all PV snapshots (labeled with a schedule, volumeSnapshotLocation) - to track how much space do I use.

**Comment by skriss** [comment]
I split the snapshot size metric into its own issue, #1309, so let's scope this one just to the gauge metrics for total # of backups/restores that currently exist
