### ISSUE TITLE
Use CLI commands instead of YAML for setting up backup/snapshot locations in our documentation

### ISSUE THREAD

**Issue by domcar** [heptio/velero#1079]
In the example folder for Minio there is no example for VolumeSnapshotLocation, instead it is present for aws and gcp.

**Comment by ncdc** [comment]
@domcar with AWS and GCP, we make the assumption that you want to use the dynamic provisioning for PVs that each provider offers. With the Minio example, we have no way of knowing what kind of volume provider you're using.

@heptio/ark-team should we consider removing all the example BSL and VSL yaml files and instead replace them with the appropriate `ark backup-location create` and `ark snapshot-location create` commands in the docs?

**Comment by carlisia** [comment]
I think for the purpose of examples using the commands instead of the file is better for precision and clarity.

I also think having an example of what those files look like is very helpful so I would advocate to having that in the docs if we remove them.

**Comment by domcar** [comment]
@ncdc yes, i looked at it too quickly, thanks :)

**Comment by skriss** [comment]
Updating this issue to cover switching from YAML to CLI commands for location config.

**Comment by skriss** [comment]
Since we'll be updating the install docs to use `velero install` (per #952), this is no longer relevant.
