### ISSUE TITLE
Expand restore item action interfaces to include unmodified object from backup

### ISSUE THREAD

**Issue by ncdc** [heptio/velero#1092]
Forked from https://github.com/heptio/ark/issues/965. 

> Is it possible to pass to plugin not only object with deleted metadata but also original object read from the backup?
If I get object with deleted metadata I have to rely on secret's name (which I think should be equal to SB name) but if I get object from the backup I can get old ownerReference.

**Comment by mwieczorek** [comment]
Hi, can I help here and start to extend the interface for plugins or do you have a plan to start it after some other issues from the related epic?

**Comment by ncdc** [comment]
We're doing a lot of plugin rework, so one of us is going to end up having to rebase. That will likely take longer than this change, so if you'd like to proceed, please feel free!
