### ISSUE TITLE
update Helm for v0.11

### ISSUE THREAD

**Issue by wwitzel3** [heptio/velero#1096]
Create a PR in upstream for the 0.10 release.

https://github.com/helm/charts/tree/master/stable/ark

**Comment by mehemken** [comment]
I'm building a helm chart for use internally at my company. I've run into a failure due to a CRD not being immediately available. The prereqs file creates the BackupStorageLocation and VolumeStorageLocation CRDs but to create a resource of kind BSL or VSL fails because those CRDs are not found.

Helm is aware of this:
https://docs.helm.sh/chart_best_practices/#install-a-crd-declaration-before-using-the-resource

**Comment by wiegandf** [comment]
A third option would be to extend the current hook-deploy.yaml file and create the custom resources with a job. The downside is that the custom resources are not managed by the helm release then.

**Comment by rosskukulinski** [comment]
Helm's support for CRDs is a known problem.  I was pointed to https://github.com/helm/helm/issues/4863 as something we should look into which also references this [community proposal](https://github.com/helm/community/pull/64).  We should be very careful until the Helm community works this out.

**Comment by rosskukulinski** [comment]
and FWIW, Istio & cert-manager are also facing similar challenges

**Comment by vidhyashankarpaysafe** [comment]
Any update on this. is it still in progress?

**Comment by wwitzel3** [comment]
I have not had a chance to really get started on this yet, but it is something we are still planning to do. I will try to make some progress on this, this week.

**Comment by jonaskello** [comment]
I'm looking to deploy ark on bare-metal and I guess the helm chart is the way to go? Only thing is that it currently only supports 0.9.0 so having the chart updated would be nice :-)

**Comment by agolomoodysaada** [comment]
https://github.com/helm/charts/commit/3c34df71ac7da7b490427622b5b90151aee79e14
^ Got this merged already

**Comment by skriss** [comment]
@agolomoodysaada thanks! when @wwitzel3 is back in the office I'm sure he'd like to chat with you about maintenance of the chart going forward.

**Comment by agolomoodysaada** [comment]
Sounds good. You can find me as `saada` on the velero slack channel

**Comment by skriss** [comment]
@nrb FYI - andy had a PR to update some docs links that never got merged. Could you ensure this stuff is updated as part of this PR?

Ref. https://github.com/helm/charts/pull/11123

**Comment by nrb** [comment]
@skriss Yeah, I had seen several open PRs for v0.10 for quality of life improvements. I'll make sure they're rolled up into the v0.11 change.

**Comment by nrb** [comment]
https://github.com/helm/charts/pull/12031 is in flight, I'm going to help review this since I was a bit behind.

**Comment by skriss** [comment]
@nrb nice. keep an eye out for any UX issues with it that we might want to tackle. Particularly interested in if the CRD creation race condition has been addressed?

**Comment by nrb** [comment]
https://github.com/helm/charts/pull/12031 is merged.

**Comment by skriss** [comment]
FYI https://github.com/helm/charts/pull/13209

**Comment by nrb** [comment]
IMO, once 13209 is merged, we can close this issue and make a separate one for our own documentation. And another one for getting the chart ready for 1.0.

**Comment by skriss** [comment]
Docs PR is merged - closing this issue. We'll open 1+ new issues for additional 1.0 work.
