### ISSUE TITLE
Document why Ark doesn't restore storageClassName on a PersistentVolume

### ISSUE THREAD

**Issue by ncdc** [heptio/velero#1097]
We should document in both code comments and .md docs why Ark does not restore the storageClassName on a PersistentVolume. See 
https://github.com/heptio/ark/issues/791#issuecomment-416631566 for details.

**Comment by skriss** [comment]
we should probably experiment with it too to see if it really needs to be removed - a lot's changed since that code was originally written.

**Comment by skriss** [comment]
Initial tests show that not deleting the `storageClassName` works fine.

**Comment by nrb** [comment]
Would it be possible for us to back up and restore the storage class? I think doing so would present problems with copying between regions/zones, but if we had #474 implemented it could possibly work.

**Comment by skriss** [comment]
@nrb there's nothing preventing us from backing up/restoring StorageClasses today - whether it "works" probably depends on the provisioner. Either way, I think *not* removing `.spec.storageClassName` from PVs makes sense by default.

**Comment by morganwalker** [comment]
I don't think I'm saying anything new here but just wanted to explain why we'd like to have the storageClassName automatically restored.

Velero has shined in all of our use cases except for statefulsets. We use quite a few stateful workloads (cassandra, kafka, prometheus, elasticsearch, etc.) across multiple storageClasses. As you know,  the storageClassName on a PersistentVolume isn't restored, which leaves our pods in an pending/unschedulable state after restore. We can't safely use this in production until we know statefulsets can be fully restored.

In the meantime, is there a workaround for restoring statefulSets that have PVs with storageClassName left blank?
