### ISSUE TITLE
Ark backup in AWS rotating access keys daily

### ISSUE THREAD

**Issue by jvaibhav123** [heptio/velero#1128]

**Comment by nrb** [comment]
@jvaibhav123 Could you provide some more context? Are you trying to use Ark in an environment that's rotating its AWS keys daily?

**Comment by ncdc** [comment]
@jvaibhav123 could you please provide more information for your issue/feature request?

**Comment by skriss** [comment]
closing as unresponsive, reopen with further information if needed!
