### ISSUE TITLE
Unable to restore namespaces from one cluster to another in different region in aws,pvc's lost 

### ISSUE THREAD

**Issue by puneethpk** [heptio/velero#1129]
**What steps did you take and what happened:**
i have taken backup of the entire namespace in a cluster inlcuding pvcs using --snapshot voulmes. After restoring it in a different cluster ,backupstorage location i.e s3 bucket being same for both the clusters,restoring is failing . 

**What did you expect to happen:**
Restoring of entire namespace including pvcs .

Exlcuding pvc and pv all other resources are being created. 

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/ark -n heptio-ark`

time="2018-12-12T07:13:16Z" level=info msg="successfully restored persistent volume from snapshot" backup=latest-backup logSource="pkg/restore/restore.go:1057" persistentVolume=pvc-9851be5b-fa22-11e8-a988-023b8eb4d0a4 providerSnapshotID=snap-0909cec60c714b7db restore=heptio-ark/latest-backup-20181212071243
time="2018-12-12T07:13:16Z" level=info msg="Restoring PersistentVolume: pvc-9851be5b-fa22-11e8-a988-023b8eb4d0a4" backup=latest-backup logSource="pkg/restore/restore.go:796" restore=heptio-ark/latest-backup-20181212071243
time="2018-12-12T07:13:16Z" level=info msg="error restoring pvc-9851be5b-fa22-11e8-a988-023b8eb4d0a4: <nil>" backup=latest-backup logSource="pkg/restore/restore.go:855" restore=heptio-ark/latest-backup-20181212071243

* `kubectl get pvc`
es-master-es-master-1       Lost     pvc-264617b7-fd29-11e8-8d4d-023253ed9574   0                         ebs            3m
es-master-es-master-2       Lost     pvc-3420e3e9-fd29-11e8-8d4d-023253ed9574   0                         ebs            3m
grafana-data                Lost     pvc-9856f20c-fa22-11e8-a988-023b8eb4d0a4   0                         ebs            3m
jenkinscore-home            Lost     pvc-9858371a-fa22-11e8-a988-023b8eb4d0a4   0                         ebs            3m

**Anything else you would like to add:**
snapshots are not being copied from one region to another for creating pvcs.

**Environment:**

- Ark version (use `ark version`):  v0.9.3
- Kubernetes version (use `kubectl version`):v1.12.2
- Cloud provider or hardware configuration:AWS

**Comment by skriss** [comment]
hi @puneethpk, Ark does not currently support cross-region migration of EBS snapshots.  This feature is planned as part of #103.

**Comment by puneethpk** [comment]
So ,in the same region but in a different cluster wil wel be able to restore the namespace with pvcs??

**Comment by puneethpk** [comment]
So,in the same region but in a different cluster will we be able to restore the namespace along with the pvcs ??

**Comment by skriss** [comment]
Yes, that's a supported use case.

**Comment by puneethpk** [comment]
but even then I'm not able to do it,pvcs are not getting created from snapshots

**Comment by ncdc** [comment]
@puneethpk are you seeing errors?

**Comment by puneethpk** [comment]
Yes, But the volumes which i had attached to the pods using the volume-id are not getting backed up.Only the PVC snapshots are getting backed up.

**Comment by ncdc** [comment]
@puneethpk could you please provide more detailed information - anything will be useful. For example, run `kubectl get ... -o yaml` for anything relevant here (PV, PVC, Pod). Also `ark backup get NAME -o yaml`. I'm not clear what you mean by "volumes which I had attached to the pods using volume-id are not getting backed up". Thanks!

**Comment by skriss** [comment]
@puneethpk is this still an active issue? If so, we'll need more information on your scenario to try to help debug.

**Comment by puneethpk** [comment]
No,we can close this issue.
