### ISSUE TITLE
Add custom tags to snapshots

### ISSUE THREAD

**Issue by wiegandf** [heptio/velero#1132]
**Describe the solution you'd like**
Currently, two tags are added to the snapshots of the cloud provider: "ark.heptio.com/backup" and "ark.heptio.com/pv". This seems to happen here:
https://github.com/heptio/ark/blob/59ca9a39742a8c527b82194b678c95a782cf9ce8/pkg/backup/item_backupper.go#L448-L464

It would be great to add custom tags to backups and schedules. One way would be to add a flag like --additional-volume-tags myTag=myValue. Another option could to add the labels that are already added to the backups. 

I think for schedules the tag "ark.heptio.com/schedule" could be a default tag. 

**Environment:**
- Ark version (use `ark version`): 0.10.0
- Kubernetes version (use `kubectl version`): 1.11.5
- Cloud provider or hardware configuration: Azure

**Comment by prydonius** [comment]
> Another option could to add the labels that are already added to the backups.

This seems like the quick and easy approach given it's already possible to add custom labels to backups. Additionally, if we use the labels on the Backup object, backups from schedules have a `velero.io/schedule-name` label that will get included.

**Comment by skriss** [comment]
That sounds like a good place to start -- doesn't require any new API fields or CLI flags.
