### ISSUE TITLE
backup and restore not work by info"Configuration not found"

### ISSUE THREAD

**Issue by WZQ1397** [heptio/velero#1137]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

I use the example minio , why not work?

**What did you expect to happen:**

`[root@K8S-Z-1 ark-ceph]# ark restore describe zach-ceph-sts-181223-20181223211333
Name:         zach-ceph-sts-181223-20181223211333
Namespace:    heptio-ark
Labels:       <none>
Annotations:  <none>

Backup:  zach-ceph-sts-181223

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <none>

Restore PVs:  auto

Phase:  

Validation errors:  <none>

Warnings:  <none>
Errors:    <none>`

LOG:

`[root@K8S-Z-1 minio]# kubectl logs deployment/ark -n heptio-ark | tail 
time="2018-12-23T14:13:06Z" level=info msg="Configuration not found" logSource="pkg/cmd/server/server.go:280"
time="2018-12-23T14:13:06Z" level=info msg="Will attempt to retrieve configuration again in 5 seconds" logSource="pkg/cmd/server/server.go:282"
time="2018-12-23T14:13:11Z" level=info msg="Configuration not found" logSource="pkg/cmd/server/server.go:280"
time="2018-12-23T14:13:11Z" level=info msg="Will attempt to retrieve configuration again in 5 seconds" logSource="pkg/cmd/server/server.go:282"
time="2018-12-23T14:13:16Z" level=info msg="Configuration not found" logSource="pkg/cmd/server/server.go:280"
time="2018-12-23T14:13:16Z" level=info msg="Will attempt to retrieve configuration again in 5 seconds" logSource="pkg/cmd/server/server.go:282"
time="2018-12-23T14:13:21Z" level=info msg="Configuration not found" logSource="pkg/cmd/server/server.go:280"
time="2018-12-23T14:13:21Z" level=info msg="Will attempt to retrieve configuration again in 5 seconds" logSource="pkg/cmd/server/server.go:282"
time="2018-12-23T14:13:26Z" level=info msg="Configuration not found" logSource="pkg/cmd/server/server.go:280"
time="2018-12-23T14:13:26Z" level=info msg="Will attempt to retrieve configuration again in 5 seconds" logSource="pkg/cmd/server/server.go:282"`

`[root@K8S-Z-1 minio]# ark restore get               
NAME                                  BACKUP                 STATUS    WARNINGS   ERRORS    CREATED                         SELECTOR
zach-ceph-sts-181223-20181223211017   zach-ceph-sts-181223   New       0          0         2018-12-23 21:10:17 +0800 CST   <none>
zach-ceph-sts-181223-20181223211333   zach-ceph-sts-181223   New       0          0         2018-12-23 21:13:33 +0800 CST   <none>
[root@K8S-Z-1 minio]# ark restore logs zach-ceph-sts-181223-20181223211017
An error occurred: unable to retrieve logs because restore is not complete`

**Environment:**

- Ark version (use `ark version`): 0.9
- Kubernetes version (use `kubectl version`): 1.12
- Kubernetes installer & version: 1.12
- Cloud provider or hardware configuration: KVM
- OS (e.g. from `/etc/os-release`): centos7.5

**Comment by ncdc** [comment]
@WZQ1397 as this is v0.9.x, you have not created the `Config` resource named `default` in the `heptio-ark` namespace (https://github.com/heptio/ark/blob/release-0.9/examples/minio/10-ark-config.yaml). Once you create that, the Ark server will get past the `Configuration not found` message.

**Comment by skriss** [comment]
@WZQ1397 were you able to get this working?

**Comment by skriss** [comment]
Closing as inactive, reopen as needed.
