### ISSUE TITLE
Document timezone of --schedule

### ISSUE THREAD

**Issue by sbarre-esit** [heptio/velero#1157]
**Describe the solution you'd like**
`ark schedule create --help` should note that `--schedule` is in UTC

**Environment:**

- Ark version (use `ark version`): Version: v0.10.1 Git commit: 7e4fca428d73899cbbdb00da8d340d44984975d8
- Kubernetes version (use `kubectl version`): oc v3.11.59
- Cloud provider or hardware configuration: on-prem
- OS (e.g. from `/etc/os-release`): RHEL 7

**Comment by skriss** [comment]
@sbarre-esit we would love a PR for this if you have the time/inclination!

**Comment by nzoueidi** [comment]
If it is possible I would love to work on this. Thanks

**Comment by skriss** [comment]
@nzoueidi sounds great! let me know if you need any input
