### ISSUE TITLE
Not found: /restores/application/.ark/8ee6f3a0-random-hash

### ISSUE THREAD

**Issue by encryptedfear** [heptio/velero#1158]
**What steps did you take and what happened:**

kubectl -n application-namespace annotate pod/application-pod-random-hash backup.ark.heptio.com/backup-volumes=application-pv-mount-name
ark backup create backup-name --include-namespaces application-namespace --snapshot-volumes
kubectl delete namespace application-namespace
ark restore create --from-backup backup-name

**What did you expect to happen:**
Backup restoration from Restic and Ark should be successful for the application.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

Executing `kubectl logs application-pod-random-hash -c restic-wait` shows the following:

Not found: /restores/application-name/.ark/8ee6f3a0-1587-11e9-8885-a81e8420728c
Not found: /restores/application-name/.ark/8ee6f3a0-1587-11e9-8885-a81e8420728c
Not found: /restores/application-name/.ark/8ee6f3a0-1587-11e9-8885-a81e8420728c

* `kubectl logs deployment/ark -n heptio-ark`

time="2019-01-11T09:59:44Z" level=info msg="Getting client for /v1, Kind=Service" backup=backup-name logSource="pkg/restore/restore.go:652" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Executing item action for services" backup=backup-name logSource="pkg/restore/restore.go:764" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Restoring Service: application-test-postgresql" backup=backup-name logSource="pkg/restore/restore.go:796" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Executing item action for services" backup=backup-name logSource="pkg/restore/restore.go:764" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Restoring Service: application-test-application" backup=backup-name logSource="pkg/restore/restore.go:796" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:56Z" level=info msg="restore completed" backup=backup-name logSource="pkg/controller/restore_controller.go:517" restore=heptio-ark/backup-name-20190111175956

* `ark backup describe <backupname>` or `kubectl get backup/<backupname> -n heptio-ark -o yaml`

Name:         backup-name
Namespace:    heptio-ark
Labels:       ark.heptio.com/storage-location=default
Annotations:  <none>

Phase:  Completed

Namespaces:
  Included:  application-namespace
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Snapshot PVs:  true

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2019-01-11 17:58:32 +0800 +08
Completed:  2019-01-11 17:58:47 +0800 +08

Expiration:  2019-02-10 17:58:32 +0800 +08

Validation errors:  <none>

Persistent Volumes: <none included>

Restic Backups (specify --details for more information):
  Completed:  2

apiVersion: ark.heptio.com/v1
kind: Backup
metadata:
  clusterName: ""
  creationTimestamp: 2019-01-11T09:58:32Z
  deletionGracePeriodSeconds: null
  deletionTimestamp: null
  generation: 0
  labels:
    ark.heptio.com/storage-location: default
  name: backup-name
  namespace: heptio-ark
  resourceVersion: "175382914"
  selfLink: /apis/ark.heptio.com/v1/namespaces/heptio-ark/backups/backup-name
  uid: 742feaf9-1587-11e9-8885-a81e8420728c
spec:
  excludedNamespaces: null
  excludedResources: null
  hooks:
    resources: null
  includeClusterResources: null
  includedNamespaces:
  - application-namespace
  includedResources: null
  labelSelector: null
  snapshotVolumes: true
  storageLocation: default
  ttl: 720h0m0s
  volumeSnapshotLocations:
  - default
status:
  completionTimestamp: 2019-01-11T09:58:47Z
  expiration: 2019-02-10T09:58:32Z
  phase: Completed
  startTimestamp: 2019-01-11T09:58:32Z
  validationErrors: null
  version: 1
  volumeSnapshotsAttempted: 0
  volumeSnapshotsCompleted: 0

* `ark backup logs <backupname>`
https://pastebin.com/M7M00BPe

* `ark restore describe <restorename>` or `kubectl get restore/<restorename> -n heptio-ark -o yaml`

b025018335@su10200871:~$ ark restore describe sonarqube-full-20190111175956
Name:         sonarqube-full-20190111175956
Namespace:    heptio-ark
Labels:       <none>
Annotations:  <none>

Backup:  sonarqube-full

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        nodes, events, events.events.k8s.io, backups.ark.heptio.com, restores.ark.heptio.com
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <none>

Restore PVs:  auto

Phase:  Completed

Validation errors:  <none>

Warnings:  <none>
Errors:    <none>

Restic Restores (specify --details for more information):
  Completed:  2

* `ark restore logs <restorename>`
time="2019-01-11T09:59:17Z" level=info msg="starting restore" backup=backup-name logSource="pkg/controller/restore_controller.go:515" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:37Z" level=info msg="Not including resource" backup=backup-name groupResource=nodes logSource="pkg/restore/restore.go:133" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:37Z" level=info msg="Not including resource" backup=backup-name groupResource=events logSource="pkg/restore/restore.go:133" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:37Z" level=info msg="Not including resource" backup=backup-name groupResource=restores.ark.heptio.com logSource="pkg/restore/restore.go:133" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:37Z" level=info msg="Not including resource" backup=backup-name groupResource=backups.ark.heptio.com logSource="pkg/restore/restore.go:133" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Starting restore of backup heptio-ark/backup-name" backup=backup-name logSource="pkg/restore/restore.go:351" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Restoring cluster level resource 'persistentvolumes' from: /tmp/804351557/resources/persistentvolumes/cluster" backup=backup-name logSource="pkg/restore/restore.go:594" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Getting client for /v1, Kind=PersistentVolume" backup=backup-name logSource="pkg/restore/restore.go:652" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Not restoring PV because it doesn't have a snapshot and its reclaim policy is Delete." backup=backup-name logSource="pkg/restore/restore.go:692" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Not restoring PV because it doesn't have a snapshot and its reclaim policy is Delete." backup=backup-name logSource="pkg/restore/restore.go:692" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Restoring resource 'persistentvolumeclaims' into namespace 'application-namespace' from: /tmp/804351557/resources/persistentvolumeclaims/namespaces/application-namespace" backup=backup-name logSource="pkg/restore/restore.go:592" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Getting client for /v1, Kind=PersistentVolumeClaim" backup=backup-name logSource="pkg/restore/restore.go:652" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Resetting PersistentVolumeClaim application-namespace/application-name-postgresql for dynamic provisioning because its PV pvc-c24d8958-1584-11e9-8885-a81e8420728c has a reclaim policy of Delete" backup=backup-name logSource="pkg/restore/restore.go:742" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Restoring PersistentVolumeClaim: application-name-postgresql" backup=backup-name logSource="pkg/restore/restore.go:796" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Resetting PersistentVolumeClaim application-namespace/application-name-sonarqube for dynamic provisioning because its PV pvc-c24e333e-1584-11e9-8885-a81e8420728c has a reclaim policy of Delete" backup=backup-name logSource="pkg/restore/restore.go:742" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Restoring PersistentVolumeClaim: application-name-sonarqube" backup=backup-name logSource="pkg/restore/restore.go:796" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Restoring resource 'secrets' into namespace 'application-namespace' from: /tmp/804351557/resources/secrets/namespaces/application-namespace" backup=backup-name logSource="pkg/restore/restore.go:592" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Getting client for /v1, Kind=Secret" backup=backup-name logSource="pkg/restore/restore.go:652" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Restoring Secret: ceph-k8s-secret" backup=backup-name logSource="pkg/restore/restore.go:796" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Restoring Secret: default-token-w4zzf" backup=backup-name logSource="pkg/restore/restore.go:796" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Restoring Secret: registry-secret" backup=backup-name logSource="pkg/restore/restore.go:796" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Restoring Secret: application-name-postgresql" backup=backup-name logSource="pkg/restore/restore.go:796" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Restoring resource 'configmaps' into namespace 'application-namespace' from: /tmp/804351557/resources/configmaps/namespaces/application-namespace" backup=backup-name logSource="pkg/restore/restore.go:592" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Getting client for /v1, Kind=ConfigMap" backup=backup-name logSource="pkg/restore/restore.go:652" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Restoring ConfigMap: application-name-sonarqube-config" backup=backup-name logSource="pkg/restore/restore.go:796" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Restoring ConfigMap: application-name-sonarqube-install-plugins" backup=backup-name logSource="pkg/restore/restore.go:796" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Restoring ConfigMap: application-name-sonarqube-startup" backup=backup-name logSource="pkg/restore/restore.go:796" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Restoring ConfigMap: application-name-application-namespaces" backup=backup-name logSource="pkg/restore/restore.go:796" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Restoring resource 'serviceaccounts' into namespace 'application-namespace' from: /tmp/804351557/resources/serviceaccounts/namespaces/application-namespace" backup=backup-name logSource="pkg/restore/restore.go:592" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Getting client for /v1, Kind=ServiceAccount" backup=backup-name logSource="pkg/restore/restore.go:652" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Executing item action for serviceaccounts" backup=backup-name logSource="pkg/restore/restore.go:764" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Restoring ServiceAccount: default" backup=backup-name logSource="pkg/restore/restore.go:796" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Restoring resource 'pods' into namespace 'application-namespace' from: /tmp/804351557/resources/pods/namespaces/application-namespace" backup=backup-name logSource="pkg/restore/restore.go:592" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Getting client for /v1, Kind=Pod" backup=backup-name logSource="pkg/restore/restore.go:652" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Executing item action for pods" backup=backup-name logSource="pkg/restore/restore.go:764" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Executing item action for pods" backup=backup-name logSource="pkg/restore/restore.go:764" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Restoring Pod: application-name-postgresql-b8678755f-kqn29" backup=backup-name logSource="pkg/restore/restore.go:796" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Executing item action for pods" backup=backup-name logSource="pkg/restore/restore.go:764" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Executing item action for pods" backup=backup-name logSource="pkg/restore/restore.go:764" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Restoring Pod: application-name-sonarqube-55bb55884d-s5mmv" backup=backup-name logSource="pkg/restore/restore.go:796" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Restoring resource 'deployments.apps' into namespace 'application-namespace' from: /tmp/804351557/resources/deployments.apps/namespaces/application-namespace" backup=backup-name logSource="pkg/restore/restore.go:592" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Getting client for apps/v1beta1, Kind=Deployment" backup=backup-name logSource="pkg/restore/restore.go:652" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Restoring Deployment: application-name-postgresql" backup=backup-name logSource="pkg/restore/restore.go:796" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Restoring Deployment: application-name-sonarqube" backup=backup-name logSource="pkg/restore/restore.go:796" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Restoring resource 'endpoints' into namespace 'application-namespace' from: /tmp/804351557/resources/endpoints/namespaces/application-namespace" backup=backup-name logSource="pkg/restore/restore.go:592" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Getting client for /v1, Kind=Endpoints" backup=backup-name logSource="pkg/restore/restore.go:652" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Restoring Endpoints: application-name-postgresql" backup=backup-name logSource="pkg/restore/restore.go:796" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Restoring Endpoints: application-name-sonarqube" backup=backup-name logSource="pkg/restore/restore.go:796" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Restoring resource 'replicasets.apps' into namespace 'application-namespace' from: /tmp/804351557/resources/replicasets.apps/namespaces/application-namespace" backup=backup-name logSource="pkg/restore/restore.go:592" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Getting client for apps/v1beta2, Kind=ReplicaSet" backup=backup-name logSource="pkg/restore/restore.go:652" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Restoring ReplicaSet: application-name-postgresql-b8678755f" backup=backup-name logSource="pkg/restore/restore.go:796" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Restoring ReplicaSet: application-name-sonarqube-55bb55884d" backup=backup-name logSource="pkg/restore/restore.go:796" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Restoring resource 'services' into namespace 'application-namespace' from: /tmp/804351557/resources/services/namespaces/application-namespace" backup=backup-name logSource="pkg/restore/restore.go:592" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Getting client for /v1, Kind=Service" backup=backup-name logSource="pkg/restore/restore.go:652" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Executing item action for services" backup=backup-name logSource="pkg/restore/restore.go:764" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Restoring Service: application-name-postgresql" backup=backup-name logSource="pkg/restore/restore.go:796" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Executing item action for services" backup=backup-name logSource="pkg/restore/restore.go:764" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:44Z" level=info msg="Restoring Service: application-name-sonarqube" backup=backup-name logSource="pkg/restore/restore.go:796" restore=heptio-ark/backup-name-20190111175956
time="2019-01-11T09:59:56Z" level=info msg="restore completed" backup=backup-name logSource="pkg/controller/restore_controller.go:517" restore=heptio-ark/backup-name-20190111175956

**Anything else you would like to add:**
mountPropagation for Persistent Volume mounts have been set to HostToContainer.

**Environment:**

- Ark version (use `ark version`): v0.10.0
- Kubernetes version (use `kubectl version`): 1.8.4
- Kubernetes installer & version:
- Cloud provider or hardware configuration: Using Minio for backups
- OS (e.g. from `/etc/os-release`): Debian GNU/Linux 8 (jessie)

**Comment by skriss** [comment]
@encryptedfear I believe mount propagation was introduced as alpha in Kubernetes v1.9 and beta in v1.10.  So you'll need to be running a more recent version of Kubernetes, and ensure that the feature flag is enabled, for restic restores to work properly.

**Comment by skriss** [comment]
closing as inactive, reopen as needed. thanks!
