### ISSUE TITLE
BackupStorageLocation prefix confusion

### ISSUE THREAD

**Issue by ncdc** [heptio/velero#1176]
We recently had a user on Slack who created a backup, had it uploaded to object storage, was able to see it in `ark backup get`, but the next time ark synced backups from the backup storage location, it deleted the just-created backup so it was no longer visible in `ark backup get`. The backup continued to exist in object storage.

We discovered that the backup storage location had a configuration like this:

```
spec:
  objectStorage:
    bucket: <my-bucket-name>/ark-backups/
    prefix: ""
  provider: aws
```

The user wanted to put the backups in a folder in object storage. Apparently ark was able to create the files in the `ark-backups` folder, but when it tried to list backups, it didn't find any (and it deleted the backups in the cluster that were not in the bucket). This is because `prefix` was empty, and ark was looking for backups in the root of the bucket.

We have 2 options I think we can consider:

1. Validate `spec.objectStorage.bucket` and disallow any `/` characters. Continue to require folder specification in `spec.objectStorage.prefix`
1. Deprecate and eventually remove `spec.objectStorage.prefix` and instead only use `spec.objectStorage.bucket`. If the value contains a `/`, anything after that is the folder.

**Comment by vivekgarg20** [comment]
Is there a specific use case to have bucket and prefix separately?

**Comment by skriss** [comment]
We've added more validation and changed the code to be more forgiving with leading/trailing slashes. Closing this issue out. We can always consider combining bucket and prefix down the road if the need resurfaces.
