### ISSUE TITLE
efs-provisioner non restic backup creates new PV 

### ISSUE THREAD

**Issue by hibbert** [heptio/velero#1179]
**What steps did you take and what happened:**

* Run backup of just the resources
* Remove namespace plus all resources
* Restore EFS directory
* Run a restore
* PVC and PV are restored, new PV created with different path, name etc. E.g.:-

jenkins-thorl4-home-pvc-f6ba87d6-24ad-11e9-9f23-0a26ccee28ca
becomes
jenkins-thorl4-home-pvc-9e5d4193-24c6-11e9-9f23-0a26ccee28ca

**What did you expect to happen:**

* PV/PVC would use old path, name etc

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/ark -n heptio-ark`
```
time="2019-01-30T18:43:56Z" level=info msg="Restoring resource 'persistentvolumeclaims' into namespace 'jenkins-thorl4' from: /tmp/534039426/resources/persistentvolumeclaims/namespaces/jenkins-thorl4" backup=nonrestic logSource="pkg/restore/restore.go:592" restore=heptio-ark/nonrestict2
time="2019-01-30T18:43:56Z" level=info msg="Getting client for /v1, Kind=PersistentVolumeClaim" backup=nonrestic logSource="pkg/restore/restore.go:652" restore=heptio-ark/nonrestict2
time="2019-01-30T18:43:56Z" level=info msg="Resetting PersistentVolumeClaim jenkins-thorl4/jenkins-thorl4-home for dynamic provisioning because its PV pvc-f6ba87d6-24ad-11e9-9f23-0a26ccee28ca has a reclaim policy of Delete" backup=nonrestic logSource="pkg/restore/restore.go:742" restore=heptio-ark/nonrestict2
time="2019-01-30T18:43:56Z" level=info msg="Restoring PersistentVolumeClaim: jenkins-thorl4-home" backup=nonrestic logSource="pkg/restore/restore.go:796" restore=heptio-ark/nonrestict2
time="2019-01-30T19:38:29Z" level=info msg="Restoring resource 'persistentvolumeclaims' into namespace 'jenkins-thorl4' from: /tmp/061081450/resources/persistentvolumeclaims/namespaces/jenkins-thorl4" backup=nonrestic logSource="pkg/restore/restore.go:592" restore=heptio-ark/nonrestict4
time="2019-01-30T19:38:29Z" level=info msg="Getting client for /v1, Kind=PersistentVolumeClaim" backup=nonrestic logSource="pkg/restore/restore.go:652" restore=heptio-ark/nonrestict4
time="2019-01-30T19:38:29Z" level=info msg="Resetting PersistentVolumeClaim jenkins-thorl4/jenkins-thorl4-home for dynamic provisioning because its PV pvc-f6ba87d6-24ad-11e9-9f23-0a26ccee28ca has a reclaim policy of Delete" backup=nonrestic logSource="pkg/restore/restore.go:742" restore=heptio-ark/nonrestict4
time="2019-01-30T19:38:29Z" level=info msg="Restoring PersistentVolumeClaim: jenkins-thorl4-home" backup=nonrestic logSource="pkg/restore/restore.go:796" restore=heptio-ark/nonrestict4
```
* `ark backup describe <backupname>` or `kubectl get backup/<backupname> -n heptio-ark -o yaml`
* `ark backup logs <backupname>`
* `ark restore describe <restorename>` or `kubectl get restore/<restorename> -n heptio-ark -o yaml`
* `ark restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

* I am looking to use more of a granular file level backup utility and use ark to restore resources, hence testing without restic

**Environment:**

- Ark version (use `ark version`): 
$ ark version
Version: v0.10.1
Git commit: 7e4fca428d73899cbbdb00da8d340d44984975d8
- Kubernetes version (use `kubectl version`):
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.1", GitCommit:"eec55b9ba98609a46fee712359c7b5b365bdd920", GitTreeState:"clean", BuildDate:"2018-12-13T19:44:19Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.5-eks-6bad6d", GitCommit:"6bad6d9c768dc0864dab48a11653aa53b5a47043", GitTreeState:"clean", BuildDate:"2018-12-06T23:13:14Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
EKS
- OS (e.g. from `/etc/os-release`):

**Comment by ncdc** [comment]
If you:

1. have a PersistentVolume with a reclaim policy of `Delete`
1. perform an Ark backup without taking a snapshot of the volume (restic or native)
1. delete the PersistentVolume
1. perform an Ark restore

Ark sees that the backup has a PersistentVolume with a `Delete` reclaim policy, sees we don't have a snapshot of it, so the only thing we can do is allow the dynamic provisioner to provision a completely new, empty PersistentVolume to go along with the PersistentVolumeClaim, which means it will get a new/different name.

Could you please share more details about your use case?

**Comment by hibbert** [comment]
Yeah, that's correct. I'm starting to see that from this issue to https://github.com/heptio/ark/issues/1151. I guess I can try to see if it works as I expect with the reclaim policy set to Retain.

**Comment by skriss** [comment]
@hibbert were you able to get this to work as desired using a `Retain` policy? Anything else needed here?

**Comment by skriss** [comment]
Closing as inactive, please reopen if needed!
