### ISSUE TITLE
 Restoring GCP Regional pv error

### ISSUE THREAD

**Issue by christianlafleur** [heptio/velero#1183]
**Description**

Restore  for regional storage class on GCP fail with this error  : Invalid value for field 'resource.replicaZones[0]': ''. Exactly 2 replica zones must be set for regional disks 

Standard storage class restore is working.

**The output of the following commands will help us better understand what's going on**:

ark create restore test2 --from-backup full01-20190204180049 --include-namespaces chris-test 
Restore request "test2" submitted successfully.

ark describe restore test2
Name:         test2
Namespace:    heptio-ark
Labels:       <none>
Annotations:  <none>

Backup:  full01-20190204180049

Namespaces:
  Included:  chris-test
  Excluded:  <none>

Resources:
  Included:        persistentvolumes
  Excluded:        nodes, events, events.events.k8s.io, backups.ark.heptio.com, restores.ark.heptio.com
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <none>

Restore PVs:  auto

Phase:  Completed

Validation errors:  <none>

Warnings:
  Ark:        <none>
  Cluster:    <none>
  Namespaces: <none>

Errors:
  Ark:        <none>
  Cluster:  error executing PVAction for /tmp/878522100/resources/persistentvolumes/cluster/pvc-0c5099ee-289f-11e9-bbb9-42010aa20034.json: rpc error: code = Unknown desc = googleapi: Error
400: Invalid value for field 'resource.replicaZones[0]': ''. Exactly 2 replica zones must be set for regional disks., invalid
  Namespaces: <none>

**Anything else you would like to add:**

kubectl get pv pvc-5d8cb4c0-28bf-11e9-bbb9-42010aa20034 --show-labels

NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS    CLAIM                     STORAGECLASS   REASON    AGE       LABELS
pvc-5d8cb4c0-28bf-11e9-bbb9-42010aa20034   10Gi       RWO            Delete           Bound     chris-test/pvc-regional   regional                 56s       failure-domain.beta.kubernetes.io/region=northamerica-northeast1,failure-domain.beta.kubernetes.io/zone=northamerica-northeast1-a__northamerica-northeast1-b

**Environment:**
* Ark version (use `ark version`):   0.10.1
* Kubernetes version (use `kubectl version`): v1.10.7
* Kubernetes installer & version: "v1.10.11-gke.1"
* Cloud provider or hardware configuration: GKE

**Comment by christianlafleur** [comment]
apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kubernetes.io/createdby: gce-pd-dynamic-provisioner
    pv.kubernetes.io/bound-by-controller: "yes"
    pv.kubernetes.io/provisioned-by: kubernetes.io/gce-pd
  creationTimestamp: 2019-02-04T20:56:42Z
  finalizers:
  - kubernetes.io/pv-protection
  labels:
    failure-domain.beta.kubernetes.io/region: northamerica-northeast1
    failure-domain.beta.kubernetes.io/zone: northamerica-northeast1-a__northamerica-northeast1-b
  name: pvc-5d8cb4c0-28bf-11e9-bbb9-42010aa20034
  resourceVersion: "146304170"
  selfLink: /api/v1/persistentvolumes/pvc-5d8cb4c0-28bf-11e9-bbb9-42010aa20034
  uid: 5fc9b00d-28bf-11e9-bbb9-42010aa20034
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: pvc-regional
    namespace: chris-test
    resourceVersion: "146304136"
    uid: 5d8cb4c0-28bf-11e9-bbb9-42010aa20034
  gcePersistentDisk:
    fsType: ext4
    pdName: gke-devl01-671c7607-dy-pvc-5d8cb4c0-28bf-11e9-bbb9-42010aa20034
  persistentVolumeReclaimPolicy: Delete
  storageClassName: regional
status:
  phase: Bound

**Comment by nrb** [comment]
Thanks for that, @christianlafleur. I've managed to replicate the issue and have a fixed that I've tested locally. I'm going to clean up the code, add some tests, then push up a PR.
