### ISSUE TITLE
Provide instructions and tools to migrate from Ark to Velero

### ISSUE THREAD

**Issue by nrb** [heptio/velero#1189]
Current installs will need to have their existing CRDs as well as the deployments migrated to our new API groups, images, and namespace.

We need to provide instructions and tooling to help users accomplish this move.

**Comment by Sam123ben** [comment]
We just started to use this and all of sudden it got migrated make us wonder where to start now. Anyways. If you can let us know will be able to create a helm chart as well to support your utility will be great as we were using the ark helm chart

**Comment by skriss** [comment]
@Sam123ben we'll be officially releasing v0.11 with the new name next week. the Helm chart for ark has historically been community-maintained, and gets updated following a new release of the product. I'd expect that to continue after we release v0.11.  

Going forward, the core team also wants to be more proactive in assisting with getting the chart updated in a timely manner.

Closing this issue as the migration instructions have been merged into master.
