### ISSUE TITLE
Do we have a document that have details on how we can install and proceed with velero

### ISSUE THREAD

**Issue by Sam123ben** [heptio/velero#1191]
Hi team,

I had been using ark and now after the change we have from today I am a bit concerned with the stability of the same.

I could not find much on velero, as I tried using brew install velero to install the client but was not possible and then I found issues while trying to install the velero server on my cluster.

As the resources are in failure states:

(⎈ |devops3-vlocity:default)➜  vof_xom_deployment_develop_branch git:(feature/XOM-4370-cluster-ark-backup) ✗ kubectl get pods,deployments -n backup             
NAME                         READY     STATUS              RESTARTS   AGE
po/restic-7mpdc              0/1       ContainerCreating   0          8s
po/restic-d9rkl              0/1       ImagePullBackOff    0          8s
po/restic-jbx4c              0/1       ContainerCreating   0          8s
po/velero-54d5cd5cc5-lkx4l   0/1       ContainerCreating   0          8s

NAME            DESIRED   CURRENT   UP-TO-DATE   AVAILABLE   AGE
deploy/velero   1         1         1            0           8s
(⎈ |devops3-vlocity:default)➜  vof_xom_deployment_develop_branch git:(feature/XOM-4370-cluster-ark-backup) ✗ kubectl describe po/velero-54d5cd5cc5-lkx4l -n backup
Name:           velero-54d5cd5cc5-lkx4l
Namespace:      backup
Node:           ip-172-18-5-8.us-east-2.compute.internal/172.18.5.8
Start Time:     Wed, 06 Feb 2019 22:06:52 +1100
Labels:         component=velero
                pod-template-hash=1081781771
Annotations:    prometheus.io/path=/metrics
                prometheus.io/port=8085
                prometheus.io/scrape=true
Status:         Pending
IP:             
Controlled By:  ReplicaSet/velero-54d5cd5cc5
Containers:
  velero:
    Container ID:  
    Image:         gcr.io/heptio-images/velero:latest
    Image ID:      
    Port:          <none>
    Command:
      /velero
    Args:
      server
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:
      VELERO_SCRATCH_DIR:  /scratch
      AWS_CLUSTER_NAME:    vlocity
    Mounts:
      /plugins from plugins (rw)
      /scratch from scratch (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from velero-token-w4h86 (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  plugins:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
  scratch:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
  velero-token-w4h86:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  velero-token-w4h86
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     <none>
Events:
  Type     Reason                  Age   From                                               Message
  ----     ------                  ----  ----                                               -------
  Normal   Scheduled               20s   default-scheduler                                  Successfully assigned velero-54d5cd5cc5-lkx4l to ip-172-18-5-8.us-east-2.compute.internal
  Normal   SuccessfulMountVolume   19s   kubelet, ip-172-18-5-8.us-east-2.compute.internal  MountVolume.SetUp succeeded for volume "scratch"
  Normal   SuccessfulMountVolume   19s   kubelet, ip-172-18-5-8.us-east-2.compute.internal  MountVolume.SetUp succeeded for volume "plugins"
  Normal   SuccessfulMountVolume   19s   kubelet, ip-172-18-5-8.us-east-2.compute.internal  MountVolume.SetUp succeeded for volume "velero-token-w4h86"
  Warning  FailedCreatePodSandBox  10s   kubelet, ip-172-18-5-8.us-east-2.compute.internal  Failed create pod sandbox: rpc error: code = Unknown desc = NetworkPlugin cni failed to set up pod "velero-54d5cd5cc5-lkx4l_backup" network: open /run/flannel/subnet.env: no such file or directory
  Normal   SandboxChanged          7s    kubelet, ip-172-18-5-8.us-east-2.compute.internal  Pod sandbox changed, it will be killed and re-created.

Any docs that let us know how to proceed and also we need to  stable version and a stable version of the helm chart for the same

**Comment by ncdc** [comment]
Hi @Sam123ben, we apologize if there has been any confusion. Until we release Velero v0.11.0, please continue to use Ark v0.10.1. The documentation for that release is at https://heptio.github.io/velero/v0.10.0/. As far as I know, the Helm chart should continue to function, since it still points to the ark v0.10.1 image:

https://github.com/helm/charts/blob/08c82581a13ddc1409fffdd22dbc2c90db738c95/stable/ark/values.yaml#L2-L3.

If you continue to have issues, would it be ok with you if we moved the conversation to our Google Group - https://groups.google.com/forum/#!forum/projectvelero?

**Comment by skriss** [comment]
Closing this as we'll have full migration documentation along with the release of v0.11 in the next few weeks.
