### ISSUE TITLE
Restic initContainer has no limits, can't be restored into namespaces with resource quotas

### ISSUE THREAD

**Issue by nrb** [heptio/velero#1201]
The restic init container defined at https://github.com/heptio/velero/blob/master/pkg/restore/restic_restore_action.go#L81-L103 is hard code, and restoring pods into namespaces that have quotas enabled results in an error such as this:

```
    test-namespace:  error restoring /tmp/671807868/resources/pods/namespaces/test-namespace/solr-trigger-test-0.json: pods "solr-trigger-test-0" is forbidden: failed quota: compute-resources: must specify limits.cpu,limits.memory,requests.cpu,requests.memory
```

I can think of 2 possible solutions off the top of my head:

* Allow the administrator to specify spec details for restic's initContainer
* Set limits on the initContainer in the code

**Comment by nrb** [comment]
A workaround, without Velero code changes, is to use a (LimitRange)[https://kubernetes.io/docs/tasks/administer-cluster/manage-resources/memory-constraint-namespace/] on the namespace, which should apply default limits to pods/containers created without limits.

**Comment by nrb** [comment]
Given the existence of the LimitRange, maybe we should document that instead of (or in addition to) code changes.

**Comment by skriss** [comment]
Now that we have a configmap for configuring the restic restore action (#1311), we could use that as a way for users to specify requests/limits if we want it to be user-configurable.  Otherwise, we could just add some static limits.

**Comment by nrb** [comment]
Low, static limits seem reasonable to me, given it's basically a spin-loop.

**Comment by nrb** [comment]
Currently blocked on #1691
