### ISSUE TITLE
Restore does not restore deployment properly

### ISSUE THREAD

**Issue by luayalem** [heptio/velero#1207]
**What steps did you take and what happened:**
1) I have a mysql deployment with 2 containers deployed, the deployment has label selector "app=mysql" 
2) Ark backup create testbackup1 -l app=mysql
3) deleted mysql deployment, 'kubectl delete deployment mysql'
4) ark restore create restore-1 --from-backup testbackup1
5) 'kubectl get deployments' will not list the restored deployment. Althought the pods got restored and the replicaset is restored and the app is running however it is not restored as a "Deployment" kind.

**What did you expect to happen:**
I expected the deployment to be restored as deployment kind and my restored deployment will show 

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

https://gist.github.com/luayalem/8793430d7106b5c33238400e2625dc4a

* `kubectl logs deployment/ark -n heptio-ark`
* `ark backup describe <backupname>` or `kubectl get backup/<backupname> -n heptio-ark -o yaml`
* `ark backup logs <backupname>`
* `ark restore describe <restorename>` or `kubectl get restore/<restorename> -n heptio-ark -o yaml`
* `ark restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
This could be easily reproduced with "Kind: Deployment".

**Environment:**

- Velero version (use `ark version`): 
0.10.1
- Kubernetes version (use `kubectl version`):
1.13.1
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by skriss** [comment]
@carlisia PTAL

**Comment by carlisia** [comment]
Thanks for the report @luayalem  I'll try to replicate this.

**Comment by skriss** [comment]
@luayalem is your deployment itself labeled with `app=mysql`, or is that only in the deployment's pod template?

**Comment by luayalem** [comment]
@skriss the deployment is labeled as well..

---
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
---

**Comment by skriss** [comment]
neither of those indicate that the `Deployment` itself is actually labeled.  can you provide the full deployment YAML?

**Comment by luayalem** [comment]
right.... I will double check the yaml file and update it.

**Comment by luayalem** [comment]
@skriss just double checked and the deployment is not labeled only the pod template is labeled.

**Comment by skriss** [comment]
Got it. So if you label the deployment, then all should be good!

**Comment by luayalem** [comment]
Yes if the deployment is labeled everything works fine.

**Comment by skriss** [comment]
Great. Closing this issue as resolved!
