### ISSUE TITLE
v1.0: remove pkg/apis/ark

### ISSUE THREAD

**Issue by skriss** [heptio/velero#1208]
`pkg/apis/ark` is deprecated as of v0.11, and should be removed entirely as of v1.0 along with any code using it.

- [x] add deprecation notices
- [ ] remove packages

**Comment by skriss** [comment]
@carlisia this is to track fully removing the package as of v1.0, this should remain open.

**Comment by carlisia** [comment]
Oh, sorry!

**Comment by skriss** [comment]
I'm tracking this in #1284 since it's all going in the same PR, closing this issue.
