### ISSUE TITLE
Mount restic snapshots to restore single files?

### ISSUE THREAD

**Issue by runam0K** [heptio/velero#1210]
Is there a way to mount the restic snapshots to restore single files?
Or is it possible to run restic commands in the cli?

I have tried to run restic commands inside the restic container, but it doesnt work:

```
# restic list snapshot -r default
Fatal: unable to open config file: Stat: stat default/config: no such file or directory
Is there a repository at the following location?
default
```

**Environment:**

- Velero version (use `ark version`): v0.9.9
- Kubernetes version (use `kubectl version`): 1.13
- Kubernetes installer & version: kubeadm v1.13.2
- Cloud provider or hardware configuration: vSphere Cloud Provider
- OS (e.g. from `/etc/os-release`): Debian 9.7

**Comment by skriss** [comment]
@runam0K you can certainly manually run `restic` commands to accomplish this - you'd have to do it either in the restic daemonset pod that's on the same node as your workload, or within your workload's pod itself (you'd have to add the restic CLI to it).  When you run them, you need to specify the repo identifier using the `--repo` flag; the value can be copied from the `resticIdentifier` field in the output of `ark restic repo get -o yaml`.  You'll also need to provide the repo password, which is currently a static value (https://github.com/heptio/velero/blob/master/pkg/restic/repository_keys.go#L32) (we're relying on IAM for your object storage for security).

I like the idea of exposing this through ark/velero itself.  Could you provide a few more details about your use case? Are you interested in doing this during an ark restore, or is the idea that you just want to roll back one file in an existing pod/volume?

**Comment by runam0K** [comment]
Thank you, it works with the static password. Why you dont use the ark-restic-credentials secret which exist?

My use case is: 

If only a few files are lost and the last backup is taken 12 hours ago, 
then I have to restore the entire volume to recover the files.
But the files that has been added after the snapshot would be lost.
At this state velero is useful for complete lost of the volume, but its complicated when you only need some files.

So it would be great if I can list the snapshots that are available and mount a snapshot to recover some files.

**Comment by joraff** [comment]
The `restic` client can be useful for this, but currently, I have to inspect the `backup` and `PodVolumeBackup` k8s resources directly to determine the restic snapshot identifier for a volume. Can these IDs be added to the `velero describe backup --details` output?

**Comment by skriss** [comment]
@joraff I think that would be reasonable to add.

**Comment by joraff** [comment]
@skriss My apologies - being new to restic, too, I was naively using `restic list snapshots` and not `restic snapshots`. The latter shows all the metadata I was looking for. I don't think digging into the k8s resources is unreasonable now - it should rarely be necessary.

**Comment by skriss** [comment]
The team has agreed we're not going to be pursuing single-file restore for restic or volume snapshots in the near future, so we're closing this issue.
