### ISSUE TITLE
Plugin log levels not respected

### ISSUE THREAD

**Issue by josephgorse** [heptio/velero#1211]
**What steps did you take and what happened:**
Wrote a plugin and tried to use log levels other than Info.

**What did you expect to happen:**
When the ark `--log-level` option is set to `debug`, my plugin's `Debug/Debugf` logs should be printed.

**The output of the following commands will help us better understand what's going on**:
N/A

**Anything else you would like to add:**
Never seeing this line printed: https://github.com/heptio/velero/blob/1675943f44dfec16f369d631046e52f6f252283c/pkg/cmd/server/plugin/plugin.go#L41

which infers that: https://github.com/heptio/velero/blob/1675943f44dfec16f369d631046e52f6f252283c/pkg/cmd/server/plugin/plugin.go#L34 is not pulling in log levels from anywhere.

Inside: https://github.com/heptio/velero/blob/7e4fca428d73899cbbdb00da8d340d44984975d8/pkg/plugin/logger.go#L28, we can see that the log level isn't referenced so the default: `Info` is inferred.

**Environment:**

- Velero version (use `ark version`): v0.10.1
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version: Minikube v0.30.0
- Cloud provider or hardware configuration: vSphere VM
- OS (e.g. from `/etc/os-release`): Ubuntu 18.04

**Comment by skriss** [comment]
thanks for the report @josephgorse, we have an in-flight PR #1049 to fix this!
