### ISSUE TITLE
Ark CrashLoopBackOff

### ISSUE THREAD

**Issue by gridworkz** [heptio/velero#1213]
I get the following messages in my ark pod log (deploying latest ark):

An error occurred: unable to retrieve the complete list of server APIs: admission.certmanager.k8s.io/v1beta1: the server is currently unable to handle the request

All other pods install fine. Has anyone seen this before?

...ahh hang on - it's a cert-manager thing.

https://github.com/jetstack/cert-manager/issues/1355

**Comment by nrb** [comment]
Closing since this is not a Velero/Ark issue.
