### ISSUE TITLE
Backups from ark schedule not deleted after expiring

### ISSUE THREAD

**Issue by puneethpk** [heptio/velero#1215]
**What steps did you take and what happened:**
created ark schedule to create backups using ark schedule command:

ark schedule create ns-backup --schedule="*/5 * * * *" --include-namespaces ethan --snapshot-volumes --ttl "2m"

**What did you expect to happen:**
All backup resources like snapshots should be deleted once it is expired.,

**The output of the following commands will help us better understand what's going on**:
But when i check the status of the backup it shows expired few seconds ago,but none of the snapshots are getting deleted.

ark get backup
NAME                       STATUS      CREATED                         EXPIRES   SELECTOR
ns-backup-20190218043006   Completed   2019-02-18 04:30:06 +0000 UTC   19s ago   <none>
ns-backup-20190218043002   Completed   2019-02-18 04:30:06 +0000 UTC   43s ago   <none>

`ark backup describe <backupname>` or `kubectl get backup/<backupname> -n heptio-ark -o yaml`
ark describe backup ns-backup-20190218043002
Name:         ns-backup-20190218043002
Namespace:    heptio-ark
Labels:       ark-schedule=ns-backup
              ark.heptio.com/storage-location=default
Annotations:  <none>

Phase:  Completed

Namespaces:
  Included:  ethan
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Snapshot PVs:  true

TTL:  2m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2019-02-18 04:30:06 +0000 UTC
Completed:  2019-02-18 04:30:29 +0000 UTC

Expiration:  2019-02-18 04:32:06 +0000 UTC

Validation errors:  <none>

Persistent Volumes: <none included>

**Comment by nrb** [comment]
Thanks for the report. A few questions:

* What is the version of ark on the server? `kubectl logs deployment/ark -n heptio-ark | head -n 1` will return the version.
* Are there any `DeleteBackupRequests` for the backup? `kubectl get deletebackuprequests -n heptio-ark` should show any.

**Comment by puneethpk** [comment]
`kubectl logs deployment/ark -n heptio-ark | head -n 1`

INFO[0000] Starting Ark server v0.9.3                    logSource="pkg/cmd/server/server.go:101"
INFO[0000] Checking existence of namespace               logSource="pkg/cmd/server/server.go:264" namespace=heptio-ark
INFO[0000] Namespace exists                              logSource="pkg/cmd/server/server.go:270" namespace=heptio-ark

There are no DeleteBackupRequests for the pod 

`kubectl get deletebackuprequests -n heptio-ark`

No resources found.

**Comment by skriss** [comment]
@puneethpk expired backups are deleted roughly once per hour, so you won't necessarily see them disappearing immediately after expiration.  Have they been deleted after an hour or so?

**Comment by puneethpk** [comment]
No , they have not been deleted.

**Comment by puneethpk** [comment]
Are there any changes which has to be made before the deployment?for --ttl flag to work?

**Comment by skriss** [comment]
No, there shouldn't be.  Could you turn on debug logging for the ark server (add `- --log-level=debug` to `args` in the deployment YAML, just under `- server`), then provide logs for a couple of hours after one of these backups is run?

**Comment by puneethpk** [comment]
I was able to fix it by adding CLUSTER_NAME env in ark-deployment.yaml. We can close this issue.
