### ISSUE TITLE
"Error getting backup store's revision, syncing" error message after upgrade to v0.10.1

### ISSUE THREAD

**Issue by lemaral** [heptio/velero#1223]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
Upgrade from v0.9.11 to v0.10.1 on AWS following instructions at https://heptio.github.io/velero/v0.10.0/upgrading-to-v0.10

**What did you expect to happen:**
No error message in logs or at least documentation in the upgrade instructions

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)
Relevant extract from kubectl logs
* `kubectl logs deployment/ark -n heptio-ark`

time="2019-02-20T22:32:33Z" level=info msg="Caches are synced" controller=gc-controller logSource="pkg/controller/generic_controller.go:83"
time="2019-02-20T22:32:33Z" level=info msg="Error getting backup store's revision, syncing" backupLocation=default controller=backup-sync error="error reading contents of revision file: rpc error: code = Unknown desc = error getting object metadata/revision: NoSuchKey: The specified key does not exist.\n\tstatus code: 404, request id: 55525345283F9776, host id: A+QjnrwYQUIxJFBJTdNfJ+Q+0LXzFiPlIeoH1qfO7y+dBjOSJAohe1Tm86GO5abvXzwIC4A+wu4=" error.file="object_store.go:370" error.function="(*objectBackupStore).GetRevision" lastSyncedRevision= lastSyncedTime="Mon, 01 Jan 0001 00:00:00 +0000" logSource="pkg/controller/backup_sync_controller.go:105"
time="2019-02-20T22:32:33Z" level=info msg="Got backups from backup store" backupCount=30 backupLocation=default controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:179"

**Environment:**
AWS eu-west-3

- Velero version (use `ark version`): (Upgrade from v0.9.11 to) v0.10.1
- Kubernetes version (use `kubectl version`): v1.11.6
- Kubernetes installer & version: kops 1.11
- Cloud provider or hardware configuration: aws
- OS (e.g. from `/etc/os-release`): debian stretch

As I'm about to upgrade several clusters with the exact same configuration, I'd like to understand what's really going on.
Thanks!

**Comment by skriss** [comment]
@lemaral this is not an error that you need to worry about, and the log msg has been clarified in `master` (see #1167).  The `revision` file isn't written until the first new backup is taken, so this is really just an info statement that the file's not found.

**Comment by lemaral** [comment]
@skriss thank you for the prompt answer :) Good to know the error message is harmless.
However I'm seeing the log filled with this error (with different ids) once per minute. I'm going to backup manually to stop it.

**Comment by lemaral** [comment]
Indeed after the backup the error is gone, maybe this can be documented somehow to avoid confusion  (and given that the error message is a little bit cryptic :)
Closing anyway, thanks!
