### ISSUE TITLE
Get v0.11 docs site ready

### ISSUE THREAD

**Issue by skriss** [heptio/velero#1224]
- [x] update version warning
- [x] update all TOC metadata
- [x] replace `Upgrading to version 0.10` in TOC with `Upgrading from ark to velero`
- [x] ensure #1203 is incorporated in the generated site
- [x] generate version-tagged site from docs in `master`
- [x] add a note to the `versions.md` page about v0.11 being the rename, with a link to upgrade
- [ ] re-generate docs for v0.11

**Comment by carlisia** [comment]
@skriss phew, glad you did this! I re-ordered the items in the way (I think) they need to be done. Thank you.

**Comment by carlisia** [comment]
@skriss The TOC link that points to `Upgrade to version 0.10` points to a page that doesn't exist (as far as I can tell). The live link is not working (https://heptio.github.io/velero/master/upgrading-to-v0.10). Should this page be created, or should we be pointing to the `versions` page (https://heptio.github.io/velero/master/versions)?

**Comment by skriss** [comment]
The upgrading to v0.10 page was intentionally deleted from `master` (it still exists in the v0.10-tagged docs site) -- but the TOC wasn't updated.  Let's remove that one from the TOC (in both the `master` and `v0.11` docs sites) and add an Upgrading to velero one.

**Comment by carlisia** [comment]
I see that we no longer maintain the `versions` page. So, not sure where to point that link to.

**Comment by carlisia** [comment]
Should the upgrading doc not be the content of `migrating-to-velero.md`?

**Comment by skriss** [comment]
Yep!

**Comment by skriss** [comment]
Closed by #1228
