### ISSUE TITLE
Velero client instead of ark?

### ISSUE THREAD

**Issue by naftulee** [heptio/velero#1225]
Hey 
we are moving to install heptio ark across all our servers.

We want to use Velero.  i cant find the velero client that replaces ark.

Can you point me to the right place?
Thanks

**Comment by carlisia** [comment]
Hi there,

We haven't released the client with the new name yet. It will be released next week (v0.11). Let us know if you have any other question.

**Comment by CamelCaseNotation** [comment]
@carlisia is there a document anywhere explaining why Ark was renamed?

**Comment by rosskukulinski** [comment]
Hi @CamelCaseNotation - the rename was announced [here](https://blogs.vmware.com/cloudnative/2019/02/05/welcoming-heptio-open-source-projects-to-vmware/).

>  Why change? Well, we discovered that another entity had a claim on the Ark name before us – so we had to find a new moniker. When we embarked on the renaming effort, we started by engaging the community—the collective contribution was hundreds of name ideas (alas, Arky McArkface did not make the cut to the dismay of Boaty McBoatface fans). Velero means sailboat in Spanish, which is consistent with our nautical theme. While the name Ark alluded to backup and recovery, the new Velero name signals that the project is capable of so much more.
