### ISSUE TITLE
Drop `warning` from restore item action plugin interface

### ISSUE THREAD

**Issue by skriss** [heptio/velero#1230]
xref #1123 
xref #286 

Restore item actions can return a warning, in the form of an `error`. AFAIK this isn't actually used anywhere, and I think we may want to get away from it in general.  Investigate whether it's okay to remove, and if so, do it as part of the plugins work.  

@carlisia

**Comment by skriss** [comment]
None of our current plugins return a warning, and per #286 we'd be dropping the warnings/errors restore results that exist today.  Warnings could still be logged to the per-restore log from plugins (as they can today).

Based on that, I'm a 👍 to move ahead with dropping this field from the plugin interface - @nrb @carlisia any input?

**Comment by carlisia** [comment]
Yes, 👍 
Changing the title.
