### ISSUE TITLE
Docs link on release notes v0.10.0 is broken

### ISSUE THREAD

**Issue by taherv** [heptio/velero#1240]
v0.10.0 release notes point to some upgrade instructions (with text in bold that it is critical for upgrades to work). The link takes us to : https://heptio.github.io/ark/v0.10.0/upgrading-to-v0.10 which is not a valid page.
Please fix this doc link.

**Comment by skriss** [comment]
https://heptio.github.io/velero/v0.10.0/upgrading-to-v0.10 is the right link. Will look at getting this updated.

**Comment by carlisia** [comment]
This is being fixed in the v0.11 release (see the docs related PR for that: https://github.com/heptio/velero/pull/1228). Closing this issue.
