### ISSUE TITLE
Backup completed with errors: [the server was unable to return a response in the time allotted

### ISSUE THREAD

**Issue by pawarrchetan** [heptio/velero#1241]
**What steps did you take and what happened:**
An ark schedule as below runs everyday.
Recently we observed that the scheduled backup is encountering errors.
NAME                STATUS    CREATED                         SCHEDULE     BACKUP TTL   LAST BACKUP   SELECTOR
ci-daily-backup     Enabled   2019-02-27 07:29:06 +0000 UTC   0 7 * * *    72h0m0s      1h ago        <none>
yaml-daily-backup   Enabled   2019-02-27 07:29:56 +0000 UTC   30 7 * * *   8760h0m0s    1h ago        <none>

The error message displayed is as below.

time="2019-02-27T07:51:52Z" level=info msg="Backup completed with errors: [the server was unable to return a response in the time allotted, but may still be processing the request (get serviceinstances.servicecatalog.k8s.io), the server was unable to return a response in the time allotted, but may still be processing the request (get serviceplans.servicecatalog.k8s.io), the server was unable to return a response in the time allotted, but may still be processing the request (get serviceclasses.servicecatalog.k8s.io), the server was unable to return a response in the time allotted, but may still be processing the request (get clusterservicebrokers.servicecatalog.k8s.io), the server was unable to return a response in the time allotted, but may still be processing the request (get servicebindings.servicecatalog.k8s.io), the server was unable to return a response in the time allotted, but may still be processing the request (get clusterserviceclasses.servicecatalog.k8s.io), the server was unable to return a response in the time allotted, but may still be processing the request (get servicebrokers.servicecatalog.k8s.io), the server was unable to return a response in the time allotted, but may still be processing the request (get clusterserviceplans.servicecatalog.k8s.io)]" backup=heptio-ark/yaml-daily-backup-20190227073019 logSource="pkg/backup/backup.go:302"

**What did you expect to happen:**
The backup should be completed successfully.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/ark -n heptio-ark`
time="2019-02-27T07:51:53Z" level=error msg="backup failed" error="[the server was unable to return a response in the time allotted, but may still be processing the request (get serviceinstances.servicecatalog.k8s.io), the server was unable to return a response in the time allotted, but may still be processing the request (get serviceplans.servicecatalog.k8s.io), the server was unable to return a response in the time allotted, but may still be processing the request (get serviceclasses.servicecatalog.k8s.io), the server was unable to return a response in the time allotted, but may still be processing the request (get clusterservicebrokers.servicecatalog.k8s.io), the server was unable to return a response in the time allotted, but may still be processing the request (get servicebindings.servicecatalog.k8s.io), the server was unable to return a response in the time allotted, but may still be processing the request (get clusterserviceclasses.servicecatalog.k8s.io), the server was unable to return a response in the time allotted, but may still be processing the request (get servicebrokers.servicecatalog.k8s.io), the server was unable to return a response in the time allotted, but may still be processing the request (get clusterserviceplans.servicecatalog.k8s.io)]" key=heptio-ark/yaml-daily-backup-20190227073019 logSource="pkg/controller/backup_controller.go:280"

* `ark backup describe <backupname>` or `kubectl get backup/<backupname> -n heptio-ark -o yaml`
Name:         yaml-daily-backup-20190227073019
Namespace:    heptio-ark
Labels:       ark-schedule=yaml-daily-backup
Annotations:  <none>

Phase:  Failed

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:

Snapshot PVs:  false

TTL:  8760h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2019-02-27 07:43:04 +0000 UTC
Completed:  2019-02-27 07:51:52 +0000 UTC

Expiration:  2020-02-27 07:43:04 +0000 UTC

Validation errors:  <none>

Persistent Volumes: <none included>

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]
This problem is occurring regularly on only 1 Kubernetes cluster.
When I run the backups manually after 2-3 hours, it completes successfully.

NAME                               STATUS      CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
ci-daily-backup-20190227110012     Completed   2019-02-27 07:20:12 +0000 UTC   2d                           <none>

**Environment:**

- Velero version (use `ark version`): 
# ark version
Version: v0.10.0
Git commit: v0.10.0
Git tree state: clean

- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.2", GitCommit:"cff46ab41ff0bb44d8584413b598ad8360ec1def", GitTreeState:"clean", BuildDate:"2019-01-10T23:35:51Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes installer & version:
- Cloud provider or hardware configuration:
AWS
- OS (e.g. from `/etc/os-release`):
Amazon Linux

**Comment by carlisia** [comment]
@pawarrchetan I have a few questions to start looking into this (and thanks for the already included info):

- please paste here the `create` commands for both the manual and schedule runs
- the output from `ark get schedule name -o yaml`
- question: you said after you wait a couple hours and run it manually it succeeds. Do you "have" to wait, or is it just when you get around to it?

**Comment by pawarrchetan** [comment]
@carlisia 
Please find below details 

ark create schedule ci-daily-backup --schedule="0 7 * * *" --include-namespaces ci --ttl="72h0m0s"
ark create schedule yaml-daily-backup --schedule="30 7 * * *" --ttl="8760h0m0s" --snapshot-volumes=false

ark create backup ci-daily-backup-20190227110012 --include-namespaces ci --ttl="72h0m0s" --snapshot-volumes=true
ark create backup yaml-daily-backup-20190227110012 --ttl="8760h0m0s" --snapshot-volumes=false

I had already provided the schedule details earlier - Pasting them again.
NAME STATUS CREATED SCHEDULE BACKUP TTL LAST BACKUP SELECTOR
ci-daily-backup Enabled 2019-02-27 07:29:06 +0000 UTC 0 7 * * * 72h0m0s 1h ago 
yaml-daily-backup Enabled 2019-02-27 07:29:56 +0000 UTC 30 7 * * * 8760h0m0s 1h ago

No. I do not have to wait. But it is strange that the manual run can also fail some times.

**Comment by pawarrchetan** [comment]
Hi @carlisia 
I am facing this error again while the backup is run as per schedule or when it runs manually.

time="2019-03-07T08:24:13Z" level=info msg="Skipping resource because it's cluster-scoped and only specific namespaces are included in the backup" backup=heptio-ark/ci-daily-backup-20190307100012 group=extensions/v1beta1 groupResource=podsecuritypolicies.extensions logSource="pkg/backup/resource_backupper.go:154"
time="2019-03-07T08:24:13Z" level=info msg="Backup completed with errors: [the server was unable to return a response in the time allotted, but may still be processing the request (get servicebindings.servicecatalog.k8s.io), the server was unable to return a response in the time allotted, but may still be processing the request (get servicebrokers.servicecatalog.k8s.io), the server was unable to return a response in the time allotted, but may still be processing the request (get serviceplans.servicecatalog.k8s.io), the server was unable to return a response in the time allotted, but may still be processing the request (get serviceclasses.servicecatalog.k8s.io), the server was unable to return a response in the time allotted, but may still be processing the request (get serviceinstances.servicecatalog.k8s.io)]" backup=heptio-ark/ci-daily-backup-20190307100012 logSource="pkg/backup/backup.go:302"

The backups has filed on both the attempts.

**Comment by skriss** [comment]
@pawarrchetan what happens if you `kubectl get` any of those resources, e.g. `kubectl get servicebindings.servicecatalog.k8s.io --all-namespaces`, `kubectl get servicebrokers.servicecatalog.k8s.io --all-namespaces`, etc.?

**Comment by pawarrchetan** [comment]
@skriss 
Thanks for getting back.

When I run the mentioned kubectl commands I get : 

[root@ip-100-66-12-84 cscripts]# kubectl get servicebindings.servicecatalog.k8s.io --all-namespaces
error: the server doesn't have a resource type "servicebindings"

[root@ip-100-66-12-84 cscripts]# kubectl get servicebrokers.servicecatalog.k8s.io --all-namespaces
error: the server doesn't have a resource type "servicebrokers"

**Comment by skriss** [comment]
OK, interesting. Can you provide the output of:

```
kubectl get --raw /
```

and

```
kubectl get --raw /apis/servicecatalog.k8s.io
```

**Comment by pawarrchetan** [comment]
@skriss 
Thanks for your post.

Please find below the output for 
kubectl get --raw /

# kubectl get --raw /
{
  "paths": [
    "/api",
    "/api/v1",
    "/apis",
    "/apis/",
    "/apis/admissionregistration.k8s.io",
    "/apis/admissionregistration.k8s.io/v1alpha1",
    "/apis/admissionregistration.k8s.io/v1beta1",
    "/apis/apiextensions.k8s.io",
    "/apis/apiextensions.k8s.io/v1beta1",
    "/apis/apiregistration.k8s.io",
    "/apis/apiregistration.k8s.io/v1",
    "/apis/apiregistration.k8s.io/v1beta1",
    "/apis/apps",
    "/apis/apps/v1",
    "/apis/apps/v1beta1",
    "/apis/apps/v1beta2",
    "/apis/ark.heptio.com",
    "/apis/ark.heptio.com/v1",
    "/apis/authentication.istio.io",
    "/apis/authentication.istio.io/v1alpha1",
    "/apis/authentication.k8s.io",
    "/apis/authentication.k8s.io/v1",
    "/apis/authentication.k8s.io/v1beta1",
    "/apis/authorization.k8s.io",
    "/apis/authorization.k8s.io/v1",
    "/apis/authorization.k8s.io/v1beta1",
    "/apis/autoscaling",
    "/apis/autoscaling.internal.knative.dev",
    "/apis/autoscaling/v1",
    "/apis/autoscaling/v2beta1",
    "/apis/autoscaling/v2beta2",
    "/apis/batch",
    "/apis/batch/v1",
    "/apis/batch/v1beta1",
    "/apis/batch/v2alpha1",
    "/apis/build.knative.dev",
    "/apis/caching.internal.knative.dev",
    "/apis/certificates.k8s.io",
    "/apis/certificates.k8s.io/v1beta1",
    "/apis/config.istio.io",
    "/apis/coordination.k8s.io",
    "/apis/coordination.k8s.io/v1beta1",
    "/apis/core.giantswarm.io",
    "/apis/core.giantswarm.io/v1alpha1",
    "/apis/custom.metrics.k8s.io",
    "/apis/custom.metrics.k8s.io/v1beta1",
    "/apis/etcd.database.coreos.com",
    "/apis/etcd.database.coreos.com/v1beta2",
    "/apis/eventing.knative.dev",
    "/apis/events.k8s.io",
    "/apis/events.k8s.io/v1beta1",
    "/apis/extensions",
    "/apis/extensions/v1beta1",
    "/apis/kubeapps.com",
    "/apis/kubeapps.com/v1alpha1",
    "/apis/metrics.k8s.io",
    "/apis/metrics.k8s.io/v1beta1",
    "/apis/monitoring.coreos.com",
    "/apis/monitoring.coreos.com/v1",
    "/apis/networking.internal.knative.dev",
    "/apis/networking.istio.io",
    "/apis/networking.k8s.io",
    "/apis/networking.k8s.io/v1",
    "/apis/policy",
    "/apis/policy/v1beta1",
    "/apis/rbac.authorization.k8s.io",
    "/apis/rbac.authorization.k8s.io/v1",
    "/apis/rbac.authorization.k8s.io/v1alpha1",
    "/apis/rbac.authorization.k8s.io/v1beta1",
    "/apis/rbac.istio.io",
    "/apis/scheduling.k8s.io",
    "/apis/scheduling.k8s.io/v1alpha1",
    "/apis/scheduling.k8s.io/v1beta1",
    "/apis/servicecatalog.k8s.io",
    "/apis/servicecatalog.k8s.io/v1beta1",
    "/apis/serving.knative.dev",
    "/apis/settings.k8s.io",
    "/apis/settings.k8s.io/v1alpha1",
    "/apis/sources.eventing.knative.dev",
    "/apis/storage.k8s.io",
    "/apis/storage.k8s.io/v1",
    "/apis/storage.k8s.io/v1alpha1",
    "/apis/storage.k8s.io/v1beta1",
    "/healthz",
    "/healthz/autoregister-completion",
    "/healthz/etcd",
    "/healthz/log",
    "/healthz/ping",
    "/healthz/poststarthook/apiservice-openapi-controller",
    "/healthz/poststarthook/apiservice-registration-controller",
    "/healthz/poststarthook/apiservice-status-available-controller",
    "/healthz/poststarthook/bootstrap-controller",
    "/healthz/poststarthook/ca-registration",
    "/healthz/poststarthook/generic-apiserver-start-informers",
    "/healthz/poststarthook/kube-apiserver-autoregistration",
    "/healthz/poststarthook/rbac/bootstrap-roles",
    "/healthz/poststarthook/scheduling/bootstrap-system-priority-classes",
    "/healthz/poststarthook/start-apiextensions-controllers",
    "/healthz/poststarthook/start-apiextensions-informers",
    "/healthz/poststarthook/start-kube-aggregator-informers",
    "/healthz/poststarthook/start-kube-apiserver-admission-initializer",
    "/healthz/poststarthook/start-kube-apiserver-informers",
    "/logs",
    "/metrics",
    "/openapi/v2",
    "/swagger-2.0.0.json",
    "/swagger-2.0.0.pb-v1",
    "/swagger-2.0.0.pb-v1.gz",
    "/swagger.json",
    "/swaggerapi",
    "/version"
  ]

Below is the output for the @second command.
# kubectl get --raw /apis/servicecatalog.k8s.io
{"kind":"APIGroup","apiVersion":"v1","name":"servicecatalog.k8s.io","versions":[{"groupVersion":"servicecatalog.k8s.io/v1beta1","version":"v1beta1"}],"preferredVersion":{"groupVersion":"servicecatalog.k8s.io/v1beta1","version":"v1beta1"}}

**Comment by skriss** [comment]
and `kubectl get --raw /apis/servicecatalog.k8s.io/v1beta1`?

**Comment by pawarrchetan** [comment]
@skriss 

Please find output for above command - 


# kubectl get --raw /apis/servicecatalog.k8s.io/v1beta1
{"kind":"APIResourceList","apiVersion":"v1","groupVersion":"servicecatalog.k8s.io/v1beta1","resources":[{"name":"clusterservicebrokers","singularName":"","namespaced":false,"kind":"ClusterServiceBroker","verbs":["create","delete","deletecollection","get","list","patch","update","watch"]},{"name":"clusterservicebrokers/status","singularName":"","namespaced":false,"kind":"ClusterServiceBroker","verbs":["get","patch","update"]},{"name":"clusterserviceclasses","singularName":"","namespaced":false,"kind":"ClusterServiceClass","verbs":["create","delete","deletecollection","get","list","patch","update","watch"]},{"name":"clusterserviceclasses/status","singularName":"","namespaced":false,"kind":"ClusterServiceClass","verbs":["get","patch","update"]},{"name":"clusterserviceplans","singularName":"","namespaced":false,"kind":"ClusterServicePlan","verbs":["create","delete","deletecollection","get","list","patch","update","watch"]},{"name":"clusterserviceplans/status","singularName":"","namespaced":false,"kind":"ClusterServicePlan","verbs":["get","patch","update"]},{"name":"servicebindings","singularName":"","namespaced":true,"kind":"ServiceBinding","verbs":["create","delete","deletecollection","get","list","patch","update","watch"]},{"name":"servicebindings/status","singularName":"","namespaced":true,"kind":"ServiceBinding","verbs":["get","patch","update"]},{"name":"servicebrokers","singularName":"","namespaced":true,"kind":"ServiceBroker","verbs":["create","delete","deletecollection","get","list","patch","update","watch"]},{"name":"servicebrokers/status","singularName":"","namespaced":true,"kind":"ServiceBroker","verbs":["get","patch","update"]},{"name":"serviceclasses","singularName":"","namespaced":true,"kind":"ServiceClass","verbs":["create","delete","deletecollection","get","list","patch","update","watch"]},{"name":"serviceclasses/status","singularName":"","namespaced":true,"kind":"ServiceClass","verbs":["get","patch","update"]},{"name":"serviceinstances","singularName":"","namespaced":true,"kind":"ServiceInstance","verbs":["create","delete","deletecollection","get","list","patch","update","watch"]},{"name":"serviceinstances/reference","singularName":"","namespaced":true,"kind":"ServiceInstance","verbs":["get","patch","update"]},{"name":"serviceinstances/status","singularName":"","namespaced":true,"kind":"ServiceInstance","verbs":["get","patch","update"]},{"name":"serviceplans","singularName":"","namespaced":true,"kind":"ServicePlan","verbs":["create","delete","deletecollection","get","list","patch","update","watch"]},{"name":"serviceplans/status","singularName":"","namespaced":true,"kind":"ServicePlan","verbs":["get","patch","update"]}]}

**Comment by skriss** [comment]
And is servicecatalog actually installed in your cluster? It sounds like possibly there are APIs registered but the extension API server itself might be missing?

**Comment by skriss** [comment]
xref #1283
