### ISSUE TITLE
kubectl fails to show BackupStorageLocation on new velero release

### ISSUE THREAD

**Issue by naftulee** [heptio/velero#1259]
Hi,
I just installed the new Velero v0.11.0
Backups are working, restore is working.  But I noticed I cant get the BackupStorageLocation.  With Ark 0.10.2  I could run the following command and would see the default BackupStorageLocation.  In the Velero release it comes back empty.
You can see the backupstoragelocation is configured and working with #velero backup get.

```
# kubectl -n velero get BackupStorageLocation
No resources found.
# velero backup get
NAME                           STATUS      CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
full-20190306150033   Completed   2019-03-06 10:00:33 -0500 EST   2d        default            <none>

The YAML for the BackupStorageLocation looks like this. 
---
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
spec:
  provider: aws
  objectStorage:
    bucket: qa
  config:
    region: qa
    s3ForcePathStyle: "true"
    s3Url: https://qa-objectstorage.net
```

**Comment by skriss** [comment]
Have you removed the old Ark CRD definitions? What do the following show:

`kubectl -n velero get backupstoragelocations.velero.io`
`kubectl get crds`

**Comment by naftulee** [comment]
Hi Skriss and thanks for your help.  I've solved the issue based on your advice.  The ark crds were in fact still around.  I removed the ark crds and after a short time the velero backupstoragelocation started showing up in kubectl command.

# kubectl -n velero get backupstoragelocations
No resources found.
# kubectl -n velero get backupstoragelocations.velero.io
NAME      AGE
default   17h

#kubectl get crds | grep ark
backups.ark.heptio.com                   2019-02-18T14:31:32Z
backupstoragelocations.ark.heptio.com    2019-02-18T14:31:32Z
deletebackuprequests.ark.heptio.com      2019-02-18T14:31:32Z
downloadrequests.ark.heptio.com          2019-02-18T14:31:32Z
podvolumebackups.ark.heptio.com          2019-02-18T14:31:32Z
podvolumerestores.ark.heptio.com         2019-02-18T14:31:32Z
resticrepositories.ark.heptio.com        2019-02-18T14:31:32Z
restores.ark.heptio.com                  2019-02-18T14:31:32Z
schedules.ark.heptio.com                 2019-02-18T14:31:32Z
volumesnapshotlocations.ark.heptio.com   2019-02-18T14:31:32Z

#kubectl get crds | grep ark | awk '{print "kubectl delete crds "$1}'
kubectl delete crds backups.ark.heptio.com
kubectl delete crds backupstoragelocations.ark.heptio.com
kubectl delete crds deletebackuprequests.ark.heptio.com
kubectl delete crds downloadrequests.ark.heptio.com
kubectl delete crds podvolumebackups.ark.heptio.com
kubectl delete crds podvolumerestores.ark.heptio.com
kubectl delete crds resticrepositories.ark.heptio.com
kubectl delete crds restores.ark.heptio.com
kubectl delete crds schedules.ark.heptio.com
kubectl delete crds volumesnapshotlocations.ark.heptio.com

And now I can see it.
# kubectl -n velero get backupstoragelocations
NAME      AGE
default   18h
