### ISSUE TITLE
restic backup to minio > The specified key does not exist

### ISSUE THREAD

**Issue by naftulee** [heptio/velero#1265]
Hi and thanks for helping out.

I deployed velero 0.11.0 recently with the latest restic deploy.
In this case Im using a minio s3 bucket

After deploying I am able to do velero backup/restore from minio.
After I label one of the pods with PV for inclusion I recieve the following error.
velero also successfully builds the directory tree for restic on the s3 bucket.

```
# velero backup logs testwithpv
An error occurred: request failed: <?xml version="1.0" encoding="UTF-8"?>
<Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Resource>/dtor-ksm2/backups/testwithpv/testwithpv-logs.gz</Resource><RequestId>1589B14A734FBFB7</RequestId><HostId>3L137</HostId></Error>

It staying in the InProgress mode.
testnopv     Completed    2019-03-07 08:45:40 -0500 EST   29d       default            <none>
testwithpv   InProgress   0001-01-01 00:00:00 +0000 UTC   29d       default            <none>

A key is created on minio and also the bucket /restic/default directories are created.
# mc ls s3/dtor-ksm2/restic/default/keys
[2019-03-07 08:47:35 EST]   455B 27e847de6ee8aabef031c7084db8f5df0e78dbdaa257794a88425e7c98163aee

# velero restic repo get -o yaml

apiVersion: velero.io/v1
kind: ResticRepository
metadata:
  creationTimestamp: 2019-03-07T13:47:32Z
  generateName: default-default-
  generation: 1
  labels:
    velero.io/storage-location: default
    velero.io/volume-namespace: default
  name: default-default-dcfcp
  namespace: velero
  resourceVersion: "7717220"
  selfLink: /apis/velero.io/v1/namespaces/velero/resticrepositories/default-default-dcfcp
  uid: 8eb0a5cb-40df-11e9-adfb-fa163e156c83
spec:
  backupStorageLocation: default
  maintenanceFrequency: 24h0m0s
  resticIdentifier: s3:http://ctor-minio01:9000/dtor-ksm2/restic/default
  volumeNamespace: default
status:
  lastMaintenanceTime: 2019-03-07T13:47:35Z
  message: ""
  phase: Ready






```

**Comment by naftulee** [comment]
its stopped running.. I have logs now. this is at the end.
```
time="2019-03-07T14:47:59Z" level=info msg="Retrieved 0 items" backup=velero/testwithpv group=extensions/v1beta1 groupResource=ingresses.extensions logSource="pkg/backup/resource_backupper.go:243" namespace=
time="2019-03-07T14:47:59Z" level=info msg="Backup completed with errors: timed out waiting for all PodVolumeBackups to complete" backup=velero/testwithpv logSource="pkg/backup/backup.go:297"

And on the minio S3 I see this.
testwithpv-volumesnapshots.json.gz  29Bytes
```

**Comment by skriss** [comment]
@naftulee re: the first error (the specified key does not exist) -- you need to follow the instructions here (https://heptio.github.io/velero/v0.11.0/expose-minio.html) to be able to run `velero backup logs`

**Comment by skriss** [comment]
could you provide the results of `kubectl get podvolumebackups.velero.io -n velero -o yaml`?

**Comment by naftulee** [comment]
> @naftulee re: the first error (the specified key does not exist) -- you need to follow the instructions here (https://heptio.github.io/velero/v0.11.0/expose-minio.html) to be able to run `velero backup logs`

Hi skriss,Thansk,  Minio is already exposed and working.  The minio is actually installed externally on vm currently, #velero backup logs works and so do backups when not using PV's.  The key does not exist happens when trying  to back up a PV,  at this point velero craetes this key on the S3 bucket ```
s3/dtor-ksm2/restic/default/keys
[2019-03-07 08:47:35 EST]   455B 27e847de6ee8aabef031c7084db8f5df0e78dbdaa257794a88425e7c98163aee
**but then it complains it does not have a key.**
```

**Comment by naftulee** [comment]
```
# kubectl get podvolumebackups.velero.io -n velero -o yaml
apiVersion: v1
items:
- apiVersion: velero.io/v1
  kind: PodVolumeBackup
  metadata:
    clusterName: ""
    creationTimestamp: 2019-03-07T13:47:35Z
    generateName: testwithpv-
    generation: 1
    labels:
      velero.io/backup-name: testwithpv
      velero.io/backup-uid: 88d0b05f-40df-11e9-adfb-fa163e156c83
    name: testwithpv-6lgj7
    namespace: velero
    ownerReferences:
    - apiVersion: velero.io/v1
      controller: true
      kind: Backup
      name: testwithpv
      uid: 88d0b05f-40df-11e9-adfb-fa163e156c83
    resourceVersion: "7717221"
    selfLink: /apis/velero.io/v1/namespaces/velero/podvolumebackups/testwithpv-6lgj7
    uid: 9047408c-40df-11e9-adfb-fa163e156c83
  spec:
    backupStorageLocation: default
    node: dtor-kubestorage05
    pod:
      kind: Pod
      name: wordpress-mysql-5bbddff49c-bl7qx
      namespace: default
      uid: aaf9b08e-3435-11e9-adfb-fa163e156c83
    repoIdentifier: s3:http://ctor-minio01:9000/dtor-ksm2/restic/default
    tags:
      backup: testwithpv
      backup-uid: 88d0b05f-40df-11e9-adfb-fa163e156c83
      ns: default
      pod: wordpress-mysql-5bbddff49c-bl7qx
      pod-uid: aaf9b08e-3435-11e9-adfb-fa163e156c83
      volume: mysql-persistent-storage
    volume: mysql-persistent-storage
  status:
    message: ""
    path: ""
    phase: ""
    snapshotID: ""
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by skriss** [comment]
ah, ok. it doesn't look like the restic daemonset pod picked up your request for a restic backup at all.  Can you provide:

```
kubectl get pods -n velero
kubectl describe daemonset restic -n velero

# for each restic daemonset pod:
kubectl logs -n velero <POD_NAME>
```

**Comment by naftulee** [comment]
well this is my mistake.  skriss pointed it out to me with the above queries, thanks you.

I reconfigured the S3 to minio from our Swift S3 bucket due to problems with the directory structure on the Swift S3.  In the process I removed the restic daemonset.  After reconfiguring to minio successfully I failed to redeploy the restic. daemonset.  No restic pods were deployed:( 

On the minio the restic backups appears to be working.  Backup is good. Ill test a restore later.   I see the data on the minio ui also now.  

#velero backup get
testwithpv1   Completed   2019-03-10 04:01:34 -0400 EDT   29d       default            <none>

**Comment by skriss** [comment]
Closing this issue as resolved.

**Comment by echel0n** [comment]
I'm finding this issue is still present in the v1.1.0-beta.2, I can successfully complete a backup but if I perform another backup right after I get "The specified key does not exist." in the backup log, always seems to be for the same namespace as well.

**Comment by beudbeud** [comment]
@skriss i have the same issue

`apiVersion: velero.io/v1
items:
- apiVersion: velero.io/v1
  kind: ResticRepository
  metadata:
    creationTimestamp: 2019-09-24T08:55:39Z
    generateName: cadran-test-default-
    generation: 1
    labels:
      velero.io/storage-location: default
      velero.io/volume-namespace: cadran-test
    name: cadran-test-default-vp8kd
    namespace: backup-service
    resourceVersion: "17390991"
    selfLink: /apis/velero.io/v1/namespaces/backup-service/resticrepositories/cadran-test-default-vp8kd
    uid: 14c70a0d-dea9-11e9-b07c-fa163ecc6ab7
  spec:
    backupStorageLocation: default
    maintenanceFrequency: 24h0m0s
    resticIdentifier: s3:http://minio.backup-service.svc:9000/velero/restic/cadran-test
    volumeNamespace: cadran-test
  status:
    lastMaintenanceTime: 2019-09-26T13:02:37Z
    message: ""
    phase: Ready
- apiVersion: velero.io/v1
  kind: ResticRepository
  metadata:
    creationTimestamp: 2019-09-10T14:21:39Z
    generateName: observations-test-default-
    generation: 1
    labels:
      velero.io/storage-location: default
      velero.io/volume-namespace: observations-test
    name: observations-test-default-mdxs4
    namespace: backup-service
    resourceVersion: "17654965"
    selfLink: /apis/velero.io/v1/namespaces/backup-service/resticrepositories/observations-test-default-mdxs4
    uid: 4e14bc09-d3d6-11e9-bd6e-fa163e826dbf
  spec:
    backupStorageLocation: default
    maintenanceFrequency: 24h0m0s
    resticIdentifier: s3:http://minio.backup-service.svc:9000/velero/restic/observations-test
    volumeNamespace: observations-test
  status:
    lastMaintenanceTime: 2019-09-25T14:36:30Z
    message: |-
      error running command=restic check --repo=s3:http://minio.backup-service.svc:9000/velero/restic/observations-test --password-file=/tmp/velero-restic-credentials-observations-test032784167 --cache-dir=/scratch/.cache/restic, stdout=using temporary cache in /scratch/.cache/restic/restic-check-cache-638355877
      created new cache in /scratch/.cache/restic/restic-check-cache-638355877
      create exclusive lock for repository
      load indexes
      , stderr=error: error loading index e9130c76: ciphertext verification failed
      Fatal: LoadIndex returned errors
      : exit status 1
    phase: NotReady
kind: ResticRepositoryList
metadata:
  resourceVersion: "17656006"
  selfLink: /apis/velero.io/v1/namespaces/backup-service/resticrepositories
`
