### ISSUE TITLE
GCP: Ability to restore snapshots from different projects

### ISSUE THREAD

**Issue by yoitsro** [heptio/velero#1268]
**Describe the solution you'd like**
I'm trying to migrate a cluster from one Google Cloud Project to another, but the restoration fails because it looks like velero derives the project ID for the disk snapshots from the generated service credentials, which references the project ID the cluster is in, as opposed to the source project.

Ideally, if there was a way to specify the source project ID in either the VolumeSnapshotLocation resource, or as a CLI flag, then this would be great.

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 0.11.0
- Kubernetes version (use `kubectl version`): 1.12
- Kubernetes installer & version:
- Cloud provider or hardware configuration: GKE
- OS (e.g. from `/etc/os-release`): Google container optimised OS

**Comment by skriss** [comment]
@yoitsro what kind of IAM setup do you need to be able to handle this case? Can a service account in Project B directly restore a disk from a snapshot in Project A?

**Comment by yoitsro** [comment]
It can as long as the permissions are set correctly. In this case, as long as the snapshots created in Project A allow read access to a service account in Project B, you're good to go.

**Comment by skriss** [comment]
OK - then sounds like this wouldn't be too bad to implement.  Like you said, we can add an optional `project` key to the `VolumeSnapshotLocation` config, and use that as the place to store/retrieve snapshots if it's specified. If it's not specified, we'll still get the project from the credentials file.  Sound right?

**Comment by yoitsro** [comment]
Sounds good to me! Thank you!

Please could you tag me in the working branch for this when you do your initial commit? I tried to figure out how I could add the `project` key myself, but my knowledge of Go is very limited, so I'd love to see how it _should_ be done!

**Comment by skriss** [comment]
Will do!

**Comment by jordanwilson230** [comment]
Just ran into this issue as well.  Thanks for picking this one up @skriss!

**Comment by tbeaudouin05** [comment]
Any update about this? I would also be interested :)

**Comment by skriss** [comment]
I wrote code that I think will enable this:

So you'd edit your `VolumeSnapshotLocation` YAML to look something like:

```yaml
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  name: gcp-default
  namespace: velero
spec:
  provider: gcp
  config:
    project: <SNAPSHOT_PROJECT_ID>
```

I pushed a test container image, `steveheptio/velero:v1.0.0-alpha.2-gcp-project`, that contains this fix. If someone could test it, that'd be awesome!

**Comment by skriss** [comment]
I pushed an update to this and rebuilt the image, if anyone can take a look!

**Comment by jordanwilson230** [comment]
@skriss I should be able to try it out this week...hopefully within a day or two. Thanks a lot for that.

**Comment by vxnick** [comment]
This works for me - thanks!

**Comment by skriss** [comment]
Thanks for testing @vxnick!

**Comment by skriss** [comment]
would be great if we could get one more verification on this before merging.

**Comment by xUmaRix** [comment]
> I wrote code that I think will enable this:
> 
> https://github.com/skriss/velero/tree/gcp-project
> 
> So you'd edit your `VolumeSnapshotLocation` YAML to look something like:
> 
> ```yaml
> apiVersion: velero.io/v1
> kind: VolumeSnapshotLocation
> metadata:
>   name: gcp-default
>   namespace: velero
> spec:
>   provider: gcp
>   config:
>     project: <SNAPSHOT_PROJECT_ID>
> ```
> 
> I pushed a test container image, `steveheptio/velero:v1.0.0-alpha.2-gcp-project`, that contains this fix. If someone could test it, that'd be awesome!

can you share what are the required steps.
I want to backup and restore k8s cluster from dev project to prod project.

**Comment by xUmaRix** [comment]
> @xUmaRix when you configure your VolumeSnapshotLocation in the prod project, you just need to specify the `project` config key and give it the name of your dev project. This will enable it to restore snapshots from there. Your service account will need to have permission to access the dev project's snapshots as well.
> 
> Once you start taking new backups in your prod project, you'll probably want a separate VSL that _doesn't_ specify the `project` key, since you'll (presumably) want those snapshots to stay in the prod project.

Hi @skriss 

This is what i did for BackupStorageLocation and VolumeSnapshotLocation to point to the dev cluster bucket

apiVersion: v1
items:
- apiVersion: velero.io/v1
  kind: BackupStorageLocation
  metadata:
    labels:
      component: velero
    name: default
    namespace: velero
  spec:
    config: {}
    objectStorage:
      bucket: vesta-prod
      prefix: ""
    provider: gcp
- apiVersion: velero.io/v1
  kind: BackupStorageLocation
  metadata:
    name: vesta-dev
    namespace: velero
  spec:
    accessMode: ReadOnly
    config: {}
    objectStorage:
      bucket: vesta-dev
      prefix: ""
    provider: gcp
kind: List

-------------------------------------------------

apiVersion: v1
items:
- apiVersion: velero.io/v1
  kind: VolumeSnapshotLocation
  metadata:
    name: default
    namespace: velero
  spec:
    config:
      project: smarthome-dev-212506
    provider: gcp
  status: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

**Comment by Rizal-I** [comment]
Trying to Migrate PV and PVC from Project B to Project A Example on GKE
1. Successfully Migrate PV & PVC
2. Attaching workload to PVC got below:

`attachdetach-controller  AttachVolume.Attach failed for volume "pvc-614bca47-5bbf-48bf-ae3f-1f72126718be" : rpc error: code = NotFound desc = ControllerPublish not permitted on node "projects/BACKUP_PROJECT_ID/zones/asia-east1-a/instances/gke-node-workload-8426e3b-n2kl" due to backoff condition`

Any idea for above Error?
