### ISSUE TITLE
Ability to preserve Status subresource on restored resources

### ISSUE THREAD

**Issue by dymurray** [heptio/velero#1272]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
Some applications depend upon the `Status` subresource in Kubernetes for managing state. An example of this is the Kubernetes Service Catalog, which stores the state of a given Service Instance in the `Status` subresource. For OpenShift, a good example of this are ImageStreams which stores the `dockerImageReference` associated with that ImageStream in the status field.

While sometimes it is desired to wipe away the status before restoring a resource, we do not want to do this for every single resource. I recommend moving the function `resetMetadataAndStatus` (https://github.com/heptio/velero/blob/0fd7872ef48ce617e561e6e45f8ccb0f11637f58/pkg/restore/restore.go#L1079) inside of a plugin so that the user may optionally write a restore plugin for specific resources that preserves the status.

Optionally, this could be handled via a whitelist/blacklist on the restore's Custom Resource.

**Comment by ncdc** [comment]
FYI, most (if not all) built-in resources don't allow you to restore status - when you create a new resource and it has status, the server-side code tends to wipe it out. For CRD instances, you can restore status as long as the CRD does **not** have the `/status` subresource enabled. If it does, you won't be able to restore status.

**Comment by dymurray** [comment]
@ncdc Thank you for that information, I wasn't aware of that. Our main use case is interested in restoring provisioned service instances from the Kubernetes Service Catalog, so I will have to dig more into those CRDs to determine if we would be able to restore these.

**Comment by dymurray** [comment]
After thinking this through more, it would suffice if the restore plugin simply had the ability to access the data on the `/status` subresource to perform some custom restoration logic. Can the restore code reset the status field *after* the restore plugins run?

**Comment by ncdc** [comment]
That's coming in #1123 #1256

**Comment by dymurray** [comment]
Excellent, thank you! I think that this issue can be closed then since the above will satisfy our concerns.
