### ISSUE TITLE
Ability to specify other S3-compatible storage for VolumeSnapshotLocation

### ISSUE THREAD

**Issue by bfabec** [heptio/velero#1275]
**Describe the solution you'd like**
First, thank you for the excellent work around velero, it's a really great project!

Currently it seems that other S3-compatible storage is only supported for the BackupStorageLocation artifacts and that is working well. However, there doesn't seem to be support (please correct me if I'm wrong!) for VolumeSnapshotLocation artifacts.

For example, BackupStorageLocation allows me to specify an `aws` config with the s3ForcePathStyle/s3Url properties. 
https://github.com/heptio/velero/blob/master/docs/api-types/backupstoragelocation.md

However, there are no such settings for VolumeSnapshotLocation properties:
https://github.com/heptio/velero/blob/master/docs/api-types/volumesnapshotlocation.md#aws

**Anything else you would like to add:**
We are trying to get IBM Cloud Object Storage which is an s3-compatible storage working with velero. It works with saving the Kubernetes objects via the BackupStorageLocation (as currently documented), but doesn't seem to be working with persistent snapshots (VolumeSnapshotLocation). We have persistent snapshots working directly with aws beautifully. 

**Environment:**

- Velero version (use `velero version`):
```
Client:
	Version: v0.11.0
	Git commit: ab2fc65c02ecdcb9bb1690e3afe67a3b3196aebc
Server:
	Version: v0.11.0
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1+icp", GitCommit:"90febef3a98de5efb2e1248525e24a57e01ad386", GitTreeState:"clean", BuildDate:"2018-09-04T08:03:44Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
IBM Cloud Private 3.1.0.0
- Cloud provider or hardware configuration:
IBM Cloud
- OS (e.g. from `/etc/os-release`):
Ubuntu 18.04

**Comment by skriss** [comment]
@bfabec what storage provider are you using for your block volumes? is it an IBM Cloud storage system?

We don't directly store volume snapshots in object storage - we use the cloud provider APIs where they exist to create the snapshots & restore from them.  We *do* put restic backup data into object storage, but that's based on the information configured in your `BackupStorageLocation`.

If your storage provider is IBM, and there's a snapshot API for it, then a `BlockStore` plugin could be written that wraps the appropriate API calls for taking snapshots, restoring from snapshot, etc. This could then be used as a `VolumeSnapshotLocation` provider.

**Comment by bfabec** [comment]
Thanks @skriss for the quick response!

If I understand what you just said correctly, the restic integration does it's backup and restores via the `BackupStorageLocation` resource, and doesn't use `VolumeSnapshotLocation` at all.  But we could additionally add a new plugin integration which then would use the `VolumeSnapshotLocation`.

That makes sense because I did notice my target volume was able to backup to my bucket and I was able to mount the folder locally with restic. However, the restore wasn't restoring my persistent volume with the IBM cloud object storage, but when changing the provider to aws, it was able to. 

After understanding this a bit more, when I removed the `VolumeSnapshotLocation` from my cluster and restarted my restic/velero pods, I was able to successfully backup and restore my persistent volumes with the object storage. 

It may be worth to add to the config/ibm example with the restic to help avoid confusion. Also, would there be any benefit to writing a `VolumeSnapshotLocation` provider if it works as is?

Thanks for the advice and clarification! Please close the issue when ready.

**Comment by skriss** [comment]
Glad you got things working.

If there is a native snapshot API for the storage provider, then yes, there would be value in writing a `BlockStore` plugin to take advantage of that, as snapshots/restores may be more efficient that way. I'm not familiar with the storage system you're using, though.

**Comment by bfabec** [comment]
Thanks again @skriss , we will discuss about the BlockStore plugin!

**Comment by prajyotparab** [comment]
@bfabec I am trying to do deployment of velero on ICP 3.1.2 using BackupStorageLocation
Here is my **05-backupstoragelocation.yaml**
```
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
spec:
  provider: aws
  objectStorage:
    bucket: ibm-velero-bucket
  config:
    s3ForcePathStyle: "true"
    s3Url: s3.us-east.cloud-object-storage.appdomain.cloud
    region: us-east

```

i am facing following error :
`An error occurred: some backup storage locations are invalid: error getting backup store for location "default": rpc error: code = Unknown desc = Invalid s3 url: s3.us-south.cloud-object-storage.appdomain.cloud`

- Kubernetes installer & version:
 IBM Cloud Private 3.1.2 EE
- Cloud provider:
 IBM Cloud
- OS :
 Ubuntu 16.04

Is there any specific provider for IBM cloud to be used?
Any help ?

**Comment by skriss** [comment]
`s3Url` should start with `http://` or `https://`

**Comment by metal3d** [comment]
I'm sorry to continue that issue, but I'm facing have the same problem.
I'm working with a hosting service that opens S3 compatible storage (Ceph) where Backup are stored. BackupLocation is ok and velero writes objects inside the bucket.
But even if I setup a VolumeStorageLocation, the PV are not stored.

```
$ velero backup describe test
Name:         test
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  <none>

Phase:  Completed

Namespaces:
  Included:  git
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Snapshot PVs:  true

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2019-05-03 15:55:09 +0200 CEST
Completed:  2019-05-03 15:55:17 +0200 CEST

Expiration:  2019-06-02 15:55:09 +0200 CEST

Persistent Volumes: <none included>
```

I tried with and without `--snapshot-volumes` flag, and same with `--volume-snapshot-locations` flag to point on my volume storage location name.

Is there any chance to make it working ?

**Comment by skriss** [comment]
@metal3d are you trying to use the restic integration to back up your volumes? If so, have you (1) deployed the restic daemonset, and (2) annotated the relevant pods? See https://heptio.github.io/velero/v0.11.0/restic for details.

**Comment by metal3d** [comment]
restic is deployed and I labelled pods (in deployment template). I will create another issue, it seems that something weird happens. Thanks
