### ISSUE TITLE
Split pkg/plugin up so plugin authors don't have to import things they don't need

### ISSUE THREAD

**Issue by skriss** [heptio/velero#1282]
ref. #1147

**Comment by skriss** [comment]
@carlisia let's discuss the proposed split here when you're ready. cc @nrb

**Comment by carlisia** [comment]
PR II: plugin client plumbing
```
pkg/plugin/clientmgmt
    backup_item_action
    block_store
    object_store
    restore_item_action
```

PR II: alternative to above, preferred
```
pkg/plugin/clientmgmt
    backup_item_action_client
    backup_item_action_server
    block_store_client
    block_store_server
    object_store_client
    object_store_server
    restore_item_action_client
    restore_item_action_server
```


PR III: plugin server and related framework
```
pkg/plugin/framework
    client_builder
    client_dispenser
    interface
    logger 
    logrus_adapter
    manager
    plugin_base
    plugin_kind
    plugin_lister
    process
    registry
    restartable_*
    server_mux
    server
    stream_reader
```

**Comment by skriss** [comment]
PR II (alt) looks good to me. I'd actually call that package `pkg/plugin/framework`, though.  In my mind this is the common package that both plugin authors *and* Velero core need to import.  And I think you'll need to move a few more things in there - `server`, `server_mux`, `logger`, `client_dispenser`, maybe one or two other things. The goal for this package is to not have it import anything from PR 3's package. 

PR III -- I'd call that package `pkg/plugin/clientmgmt` -- since Velero is the "client" when it comes to plugins.  It's fine for this package to import from PR II's package, but not vice-versa.  I agree with most of the items in here, with the few exceptions noted above.  There may be some additional dependencies that need to be untangled as we go through it, though.

**Comment by carlisia** [comment]
I appreciate the explanation! Copy that, will start on PR II.
