### ISSUE TITLE
Gracefully handle failed API groups from the discovery API

### ISSUE THREAD

**Issue by arianitu** [heptio/velero#1283]
**What steps did you take and what happened:**
After going through all the Azure steps in the documentation, velero fails to start with `An error occurred: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request`

**What did you expect to happen:**
Expected Velero to start

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

```
time="2019-03-13T20:13:32Z" level=info msg="setting log-level to INFO"
time="2019-03-13T20:13:32Z" level=info msg="Starting Velero server v0.11.0 (ab2fc65c02ecdcb9bb1690e3afe67a3b3196aebc)" logSource="pkg/cmd/server/server.go:134"
time="2019-03-13T20:13:32Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/registry.go:98" name=pod
time="2019-03-13T20:13:32Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/registry.go:98" name=pv
time="2019-03-13T20:13:32Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/registry.go:98" name=serviceaccount
time="2019-03-13T20:13:32Z" level=info msg="registering plugin" command=/velero kind=BlockStore logSource="pkg/plugin/registry.go:98" name=aws
time="2019-03-13T20:13:32Z" level=info msg="registering plugin" command=/velero kind=BlockStore logSource="pkg/plugin/registry.go:98" name=azure
time="2019-03-13T20:13:32Z" level=info msg="registering plugin" command=/velero kind=BlockStore logSource="pkg/plugin/registry.go:98" name=gcp
time="2019-03-13T20:13:32Z" level=info msg="registering plugin" command=/velero kind=ObjectStore logSource="pkg/plugin/registry.go:98" name=aws
time="2019-03-13T20:13:32Z" level=info msg="registering plugin" command=/velero kind=ObjectStore logSource="pkg/plugin/registry.go:98" name=azure
time="2019-03-13T20:13:32Z" level=info msg="registering plugin" command=/velero kind=ObjectStore logSource="pkg/plugin/registry.go:98" name=gcp
time="2019-03-13T20:13:32Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/registry.go:98" name=job
time="2019-03-13T20:13:32Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/registry.go:98" name=pod
time="2019-03-13T20:13:32Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/registry.go:98" name=restic
time="2019-03-13T20:13:32Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/registry.go:98" name=service
time="2019-03-13T20:13:32Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/registry.go:98" name=serviceaccount
time="2019-03-13T20:13:32Z" level=info msg="Checking existence of namespace" logSource="pkg/cmd/server/server.go:322" namespace=velero
time="2019-03-13T20:13:32Z" level=info msg="Namespace exists" logSource="pkg/cmd/server/server.go:328" namespace=velero
An error occurred: unable to retrieve the complete list of server APIs: metrics.k8s.io/v1beta1: the server is currently unable to handle the request

```

**Environment:**

- Velero version (use `velero version`): 

```
Client:
	Version: v0.11.0
	Git commit: ab2fc65c02ecdcb9bb1690e3afe67a3b3196aebc
<error getting server version: timed out waiting for server status request to be processed>
```

- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-05-12T04:12:47Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.5", GitCommit:"753b2dbc622f5cc417845f0ff8a77f539a4213ea", GitTreeState:"clean", BuildDate:"2018-11-26T14:31:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- Kubernetes installer & version:
AKS v1.11.5

- Cloud provider or hardware configuration:
Azure using AKS

**Comment by skriss** [comment]
It sounds like the Kubernetes metrics server is not properly responding? Is it deployed & running? ref. https://kubernetes.io/docs/tasks/debug-application-cluster/core-metrics-pipeline/#metrics-server

**Comment by arianitu** [comment]
@skriss It is not deployed or running. Should it be? I noticed I can't do `kubectl top pod` 

The deployment is handled by AKS.

**Comment by arianitu** [comment]
It looks like I can install it from https://github.com/kubernetes-incubator/metrics-server. But why is this a requirement for Velero?

**Comment by arianitu** [comment]
I tried to create the metrics server and it said it already exists. I checked my deployments and it's there, but does not appear to be running. This is probably an issue with our cluster and not this library.

Closing this for now unless I find it has something to do with Velero.

**Comment by arianitu** [comment]
It looks like it's paused with 0 replicas. We have heapster running instead, perhaps that's why AKS paused metrics-server?

The YAML looks like so for metrics-server:

```
spec:
  paused: true
  progressDeadlineSeconds: 600
  replicas: 0
```

Is this an edge case for Velero?

**Comment by skriss** [comment]
Velero does not gracefully handle an API that should be reachable, but isn't.  We might want to handle this more gracefully, but it also indicates something is probably wrong in your cluster.

**Comment by skriss** [comment]
I think our discovery helper should gracefully handle "failed groups" when using the discovery API.  Ref. https://github.com/kubernetes/client-go/blob/master/discovery/discovery_client.go#L224, https://github.com/kubernetes/client-go/blob/master/discovery/discovery_client.go#L342. We should be able to process the groups that returned successfully, and log but ignore the ones that didn't.

**Comment by skriss** [comment]
Our discovery helper uses the discovery API to get a list of all API groups/resources here:
https://github.com/heptio/velero/blob/master/pkg/discovery/helper.go#L110

Right now, if it gets any error, it just returns it up the stack. However, looking at https://github.com/kubernetes/client-go/blob/master/discovery/discovery_client.go#L342, we can see that the `ServerPreferredResources` may return partial results along with an `ErrGroupDiscoveryFailed` error.  

We should update our code so that it explicitly checks for an error of this type, and if it gets one, it should log (probably at warning level) that certain APIs were not available; however, it should continue executing with the partial result that it got. If an error of a different type is gotten from `ServerPreferredResources`, we should probably continue to immediately return it.
