### ISSUE TITLE
release tarball: prefix by a directory

### ISSUE THREAD

**Issue by philips** [heptio/velero#1310]
**Describe the solution you'd like**

In the grand 'ol tradition of tarballs it would be nice if velero prefixed all of its files by a directory instead of dropping a LICENSE file into whatever directory I am extracting into.

What I expect to happen:

```
$ tar xzvf velero-v0.11.0-linux-amd64.tar.gz
velero-v0.11.0-linux-amd64/LICENSE
velero-v0.11.0-linux-amd64/config/README.md
velero-v0.11.0-linux-amd64/config/aws/05-backupstoragelocation.yaml
velero-v0.11.0-linux-amd64/...
velero-v0.11.0-linux-amd64/velero
```

What happens today:

```
$ tar xzvf velero-v0.11.0-linux-amd64.tar.gz
LICENSE
config/README.md
config/aws/05-backupstoragelocation.yaml
...
velero
```

**Anything else you would like to add:**

I don't know how the release tarballs are generated but GNU tar can do this:

```
tar cf archive.tar velero LICENSE --transform 's,^,velero-v0.11.0-linux-amd64/,'
```

**Comment by skriss** [comment]
thanks @philips, we should be able to do this for the next release.

We need to update the `.goreleaser.yml` file - the `archive` section (https://github.com/heptio/velero/blob/master/.goreleaser.yml#L43) needs to set `wrap_in_directory` to `true` (see https://goreleaser.com/archive/).

We should also review the install docs to see if any bash snippets or instructions need to be updated to account for the directory.
