### ISSUE TITLE
Velero omitting Encrypted param when calling ec2:CreateVolume results in ec2:Encrypted being evaluated as false

### ISSUE THREAD

**Issue by mstump** [heptio/velero#1312]
**What steps did you take and what happened:**
This is on a cluster where AWS permissions prevent the creation of a volume without encryption.

1. Provision velero `v0.11.0` on AWS, configure block storage provider with KMS key.
1. Create a backup containing EBS volumes encrypted to KMS key
1. Restore snapshot

**What did you expect to happen:**
Volumes should be restored

**The output of the following commands will help us better understand what's going on**:
The AWS API responds with `403 UnauthorizedOperation` when executing `PVAction`. Upon decrypting the failure message the request contains the parameter `ec2:Ecnrypted` with the value set to false. I verified that the snapshot is indeed encrypted.

I originally raised this issue in [pr-211](https://github.com/heptio/velero/pull/211), and they've been on that fork ever since but they've been running into a controller bug that can cause old versions of ark to spam the EC2 API at a rate of thousands of requests per minute.

**Anything else you would like to add:**
It's a secure environment, and they're super sketchy about publishing logs or request details in a public forum but I'm in your slack.

**Environment:**

- Velero version (use `velero version`): `v0.11.0`
- Kubernetes version (use `kubectl version`): `1.13.0`
- Kubernetes installer & version: `kops v1.11 heavily customized`
- Cloud provider or hardware configuration: `AWS`
- OS (e.g. from `/etc/os-release`): `RHEL 7.6`

**Comment by mstump** [comment]
Relevant portion of the request for gratuitous proof below. Velero [isn't setting the param](https://github.com/heptio/velero/blob/master/pkg/cloudprovider/aws/block_store.go#L101), and the [API states that it should just follow the state of the snapshot](https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#CreateVolumeInput) (encrypted stays encrypted), but I'm thinking that the go SDK is implicitly setting the value to false (what's the value of an uninitialized `*bool`?), and that if you've explicitly forbidden that ability via policy it causes things to blow up. 

```
"action": "ec2:CreateVolume",
    "resource": "arn:aws:ec2:ap-southeast-2:XXXXXXXXXX:volume/*",
    "conditions": {
      "items": [
       ....
        {
          "key": "ec2:Encrypted",
          "values": {
            "items": [
              {
                "value": "false"
              }
            ]
          }
        }
       ...
```

**Comment by mstump** [comment]
Hold on this item, there may be something else going on. I put the onus on their team to give me a set of request params that work.

**Comment by mstump** [comment]
What we've been able to affirm:

- When a `CreateVolume` request is made using an encrypted snapshot as an input parameter an encrypted volume is always created. 
- The problem is the interaction with IAM policy. When the request is evaluated by the policy and the `Encrypted` param is omitted the policy is handed a conditions block with `ec2:Encrypted = false` as noted in previous comments. This is true in one sense, the request didn't set the param to true, but isn't true because it's being executed within the context of an encrypted volume.

The options for fixes include:
- Layering IAM policies so that only encrypted snapshots can be created, and trusting that if a `CreateVolume` request is made and `EC2:ParentSnapshots != Null` to let it through although `ec2:Encrypted = false`. I'm not a guru on this front and I'm not even sure if this logic is possible.
- Revive my previous patch or some variant thereof such that if the snapshot is encrypted, explicitly set the `Encrypted` when calling `CreateVolume`.
- Yell at AWS until they fix the `ec2:Encrypted` inconsistency.

**Comment by skriss** [comment]
Oof, that's a nasty one. +1 to yelling at AWS, but we can probably put an updated 211 in place (with comment!) to work around this for now

**Comment by mstump** [comment]
Thank you, this has consumed a huge chunk of time and I'd like to put it to bed. I'm going to go back and look at that patch but I think the problem at the time, and I still think this is true is that passing the need for encrypted to be set to true is difficult because that context is missing in the block store. We'd need to add a param or context, and that results in a much bigger patch that you'd think.

**Comment by skriss** [comment]
OK I'll take another look at it as well and see what we can come up with

**Comment by skriss** [comment]
@mstump this commit (https://github.com/heptio/velero/pull/211/commits/bcc98a83ef9a043107948cc72cbdf1a5207a6464) looks like it should be OK if updated - it's using `DescribeSnapshot` to figure out if the snap is encrypted or not, rather than trying to store that info somewhere in the velero metadata.  And we already use that API call, so our existing IAM policy recommendation covers it.

**Comment by mstump** [comment]
Validated that the patch fixes the issue in the target environment. Ready for merge if you are.
