### ISSUE TITLE
Velero does not work with an external minio server

### ISSUE THREAD

**Issue by omenv** [heptio/velero#1314]
**What steps did you take and what happened:**
I tested Velero with the example of minio server wich works in the same namespace and it worked fine. When I tried to use an external minio server(which works out of the kubernetes cluster) I got an error `code = Unknown desc = SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method. status code: 403`

**What did you expect to happen:**
I expected that Valero should work with an external minio server as a minio server in the same namespace. 

**The output of the following commands will help us better understand what's going on**:
`kubectl logs deployment/velero -n velero
time="2019-03-25T14:47:04Z" level=info msg="setting log-level to INFO"
time="2019-03-25T14:47:04Z" level=info msg="Starting Velero server v0.11.0 (ab2fc65c02ecdcb9bb1690e3afe67a3b3196aebc)" logSource="pkg/cmd/server/server.go:134"
time="2019-03-25T14:47:04Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/registry.go:98" name=pod
time="2019-03-25T14:47:04Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/registry.go:98" name=pv
time="2019-03-25T14:47:04Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/registry.go:98" name=serviceaccount
time="2019-03-25T14:47:04Z" level=info msg="registering plugin" command=/velero kind=BlockStore logSource="pkg/plugin/registry.go:98" name=aws
time="2019-03-25T14:47:04Z" level=info msg="registering plugin" command=/velero kind=BlockStore logSource="pkg/plugin/registry.go:98" name=azure
time="2019-03-25T14:47:04Z" level=info msg="registering plugin" command=/velero kind=BlockStore logSource="pkg/plugin/registry.go:98" name=gcp
time="2019-03-25T14:47:04Z" level=info msg="registering plugin" command=/velero kind=ObjectStore logSource="pkg/plugin/registry.go:98" name=aws
time="2019-03-25T14:47:04Z" level=info msg="registering plugin" command=/velero kind=ObjectStore logSource="pkg/plugin/registry.go:98" name=azure
time="2019-03-25T14:47:04Z" level=info msg="registering plugin" command=/velero kind=ObjectStore logSource="pkg/plugin/registry.go:98" name=gcp
time="2019-03-25T14:47:04Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/registry.go:98" name=job
time="2019-03-25T14:47:04Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/registry.go:98" name=pod
time="2019-03-25T14:47:04Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/registry.go:98" name=restic
time="2019-03-25T14:47:04Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/registry.go:98" name=service
time="2019-03-25T14:47:04Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/registry.go:98" name=serviceaccount
time="2019-03-25T14:47:04Z" level=info msg="Checking existence of namespace" logSource="pkg/cmd/server/server.go:322" namespace=velero
time="2019-03-25T14:47:04Z" level=info msg="Namespace exists" logSource="pkg/cmd/server/server.go:328" namespace=velero
time="2019-03-25T14:47:07Z" level=info msg="Checking existence of Velero custom resource definitions" logSource="pkg/cmd/server/server.go:357"
time="2019-03-25T14:47:07Z" level=info msg="All Velero custom resource definitions exist" logSource="pkg/cmd/server/server.go:391"
time="2019-03-25T14:47:07Z" level=info msg="Checking that all backup storage locations are valid" logSource="pkg/cmd/server/server.go:398"
An error occurred: some backup storage locations are invalid: backup store for location "default" is invalid (if upgrading from a pre-v0.10 version of Velero, please refer to https://heptio.github.io/velero/v0.10.0/storage-layout-reorg-v0.10 for instructions): rpc error: code = Unknown desc = SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
	status code: 403, request id: 158F3AF6CF41FABA, host id: 
`

**Anything else you would like to add:**
```
---
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
spec:
  provider: aws
  objectStorage:
    bucket: velero
  config:
    region: minio
    s3ForcePathStyle: "true"
    s3Url: https://minio.domain.com
    publicUrl: https://minio.domain.com
```
I checked the url `https://minio.domain.com`, access to the link from the kubernetes namespaces and  the credentials of the minio server and they work fine. I guess it can be a wrong parameter of `s3Url`. 

**Environment:**

- Velero version:
Version: 0.11.0 
- Kubernetes version:
```
Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.4", GitCommit:"c27b913fddd1a6c480c229191a087698aa92f0b1", GitTreeState:"clean", BuildDate:"2019-03-01T23:34:27Z", GoVersion:"go1.12", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.5", GitCommit:"51dd616cdd25d6ee22c83a858773b607328a18ec", GitTreeState:"clean", BuildDate:"2019-01-16T18:14:49Z", GoVersion:"go1.10.7", Compiler:"gc", Platform:"linux/amd64
```
- Kubernetes installer & version:
kubespray 2.8
- Cloud provider or hardware configuration:
KVM instances
- OS (e.g. from `/etc/os-release`):
Centos 7.5

**Comment by nrb** [comment]
Hi @omenv - do you control the minio deployment outside of the kubernetes namespace? Would you be able to look in those logs for the request ID logged (`158F3AF6CF41FABA`)?

Also, is the Minion configuration using the same signature algorithm? That can be changed on the Velero side with this parameter: https://heptio.github.io/velero/v0.11.0/api-types/backupstoragelocation.html#aws

**Comment by omenv** [comment]
Hi @nrb 
Thanks a lot for your help. The problem was with my incorrect nginx configuration. 
After I corrected my nginx configuration according to `https://docs.minio.io/docs/setup-nginx-proxy-with-minio.html` everything works fine. We can close the issue.
