### ISSUE TITLE
Add a `make local` target to plugin example makefile

### ISSUE THREAD

**Issue by carlisia** [heptio/velero#1315]
This is helpful when running the plugin example with a local version of the velero server in any non-*nix environment.

**Comment by skriss** [comment]
shouldn't this issue go in the example repo?

**Comment by carlisia** [comment]
I just realized that but also not sure it'd be trackable.

**Comment by carlisia** [comment]
Tracking here: https://github.com/heptio/velero-plugin-example/issues/19
