### ISSUE TITLE
Hault velero server if no plugin was loaded

### ISSUE THREAD

**Issue by carlisia** [heptio/velero#1320]
Now that we are going to halt the velero server if any plugin being passed in is out of sync with the current version, I am thinking that we should also halt the server if a value is passed to `--plugin-dir` but there’s no executable plugin.

**Comment by skriss** [comment]
By default this flag has a value, `/plugins`, but the directory is empty unless a user adds plugins.  I assume you're saying to remove the default value (so we don't error in the normal case)? If so, you'll also need to update `velero plugin add` and `velero plugin remove` to toggle this flag on/off as plugins are added.

**Comment by carlisia** [comment]
Yes and no. Half of what I said what that, but with your explanation that half is irrelevant. The other half is this: if we go thru the directory and don't find a plugin to use, then return an error. I'm thinking a user could point the directory to an empty folder (forget to build the plugin) or to a path name that contains misspellings, things like that.

**Comment by nrb** [comment]
> The other half is this: if we go thru the directory and don't find a plugin to use, then return an error.

By default, we point to an empty directory like Steve said (see [a deployment example](https://github.com/heptio/velero/blob/master/examples/aws/10-deployment.yaml#L46-L47)), so if we halt startup, we'll need to adjust how this default behavior works.

**Comment by carlisia** [comment]
We agreed to better document for the user to check the logs to ensure the plugin was loaded. Closing.
