### ISSUE TITLE
Cannot build Velero

### ISSUE THREAD

**Issue by amanw** [heptio/velero#1324]
**What steps did you take and what happened:**
Cannot build the repo locally.

Did a `git clone` and then a `make`. This results in the following output:

I got an build error output regarding `./hack/build.sh` not being found:

`bin/bash^M: bad interpreter: No such file or directory`
**What did you expect to happen:**
The build to work

It is resolved with this resolution:
https://stackoverflow.com/questions/2920416/configure-bin-shm-bad-interpreter/11019077

**Comment by skriss** [comment]
@amanw what desktop platform are you using?

**Comment by skriss** [comment]
Closing as inactive, reopen as needed.
