### ISSUE TITLE
Logs from restore plugins are getting lost

### ISSUE THREAD

**Issue by sseago** [heptio/velero#1328]
**What steps did you take and what happened:**
Running a restore with a custom plugin registered, log messages from the restore Execute action are not being logged to the restore log. For comparison, backup logs from plugin Execute actions are showing up in the velero logs as expected.

**What did you expect to happen:**
I expected that 'velero restore logs <my-restore>' would show the log messages from my plugin.

I tracked this down to controller/restore_controller.go. For the backup plugin, this all works properly. First the logger is re-initialized, setting logger.out to an io.MultiWriter: https://github.com/heptio/velero/blob/master/pkg/controller/backup_controller.go#L407-L409
*then* the pluginManager is initialized with newPluginManager, passing in the new logger: https://github.com/heptio/velero/blob/master/pkg/controller/backup_controller.go#L419
All of this happens within runBackup, which is called by processBackup.

For restore, however, things are more complicated, but the root of the problem is that the pluginManager is initialized *before* the logger is re-initialized, so anything written to the log configured for the pluginManager gets lost. For restore, newPluginManager is called in processRestore, and this manager is passed into the call to runRestore, which then re-initializes logs before running the restore.

PluginManager is initialized here: https://github.com/heptio/velero/blob/master/pkg/controller/restore_controller.go#L207
passed into runRestore here: https://github.com/heptio/velero/blob/master/pkg/controller/restore_controller.go#L244-L249
Logger is re-initialized here: https://github.com/heptio/velero/blob/master/pkg/controller/restore_controller.go#L464-L470

I have a fix in our velero fork which seems to work, but it's somewhat messy. I essentially had to merge the logic of processRestore and runRestore in order to get the pluginManager initialization to work properly without changing anything else, but it's at the expense of readability. I'll submit this as a PR here -- if this fix isn't appropriate for an upstream commit, it will at least point you in the right direction as to what's wrong and what needs to change.

**Environment:**

- Velero version (use `velero version`): master branch
- Kubernetes version (use `kubectl version`): 1.12
- Kubernetes installer & version:
- Cloud provider or hardware configuration: Running in an Openshift 4.0 environment in AWS
- OS (e.g. from `/etc/os-release`):

**Comment by skriss** [comment]
Thanks for reporting this, and for the PR! I'll take a look in the next day or two.
