### ISSUE TITLE
GCP has no valid config keys defined

### ISSUE THREAD

**Issue by nrb** [heptio/velero#1345]
**What steps did you take and what happened:**
When testing PR #1287, I noticed my pod was in crash loop back off. This seems to be caused by 
#1388.

```
time="2019-04-03T18:27:55Z" level=info msg="Checking that all backup storage locations are valid" logSource="pkg/cmd/server/server.go:398"
An error occurred: some backup storage locations are invalid: error getting backup store for location "default": rpc error: code = Unknown desc = config has invalid keys [region bucket]; valid keys are []
```

My backupstoragelocation looks like this:

```
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  creationTimestamp: 2019-04-03T18:24:27Z
  generation: 1
  labels:
    component: velero
  name: default
  namespace: velero
  resourceVersion: "593"
  selfLink: /apis/velero.io/v1/namespaces/velero/backupstoragelocations/default
  uid: b74398fb-563d-11e9-9341-0242eb3beca5
spec:
  config:
    region: us-west2
  objectStorage:
    bucket: <bucketname>
    prefix: ""
  provider: gcp
status:
  lastSyncedTime: null
```

**What did you expect to happen:**
The pod would start successfully.

**Comment by skriss** [comment]
Hmm. so failing on `bucket` is definitely a bug - I think I know what's going on there - but pretty sure `region` is not a valid key for GCP BSL's

**Comment by nrb** [comment]
Yeah, I'm trying to reproduce this with an instance running locally with `master`, and it's not happening using the same BSL. With the `master` image on my KinD cluster, though, it's continuing to happen.

I wonder if I've got an issue with the install code.

**Comment by nrb** [comment]
Hm, yeah, against the exact same cluster, the pod keeps restarting with the error, but my local instance works fine. Both are using a BSL generated by my install command.

**Comment by skriss** [comment]
I can look into this some more tomorrow afternoon since it's my PR that introduced it :)

**Comment by fabito** [comment]
I'm getting the same error on my local dev environment. I'm using minio and my `backupstoragelocation`  look like this:

```yaml
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"velero.io/v1","kind":"BackupStorageLocation","metadata":{"annotations":{},"name":"default","namespace":"velero"},"spec":{"config":{"public
  creationTimestamp: "2019-03-13T01:10:15Z"
  generation: 46
  name: default
  namespace: velero
  resourceVersion: "839889"
  selfLink: /apis/velero.io/v1/namespaces/velero/backupstoragelocations/default
  uid: c2b9744c-452c-11e9-857f-847bebfe2edf
spec:
  config:
    publicUrl: http://localhost/
    region: minio
    s3ForcePathStyle: "true"
    s3Url: http://localhost/
  objectStorage:
    bucket: velero
  provider: aws
status:
  lastSyncedRevision: 16580672-fd52-4f6f-b7bf-40f73aa2981c
  lastSyncedTime: "2019-03-25T12:01:47.499584133Z"
```

**Comment by nrb** [comment]
@fabito Is it the same error? Which keys is it reporting as invalid there?

**Comment by skriss** [comment]
I'll look at getting a fix up for this this afternoon, since it's gonna be an issue for anyone developing/testing.

**Comment by fabito** [comment]
Not exactly the same, only `bucket` is considered invalid:

```
An error occurred: some backup storage locations are invalid: error getting backup store for location "default": rpc error: code = Unknown desc = config has invalid keys [bucket]; valid keys are [region s3Url publicUrl kmsKeyId s3ForcePathStyle signatureVersion]
```
