### ISSUE TITLE
Unable to see backups in velero backup get

### ISSUE THREAD

**Issue by jprecuch** [heptio/velero#1346]
**What steps did you take and what happened:**
We deployed velero to velero namespace and scheduled daily + halfdaily backups. Backups are created fine on S3. However when we want to list them it shows none in cli.
`time="2019-04-04T06:03:24Z" level=info msg="Backup completed successfully" backup=velero/daily-full-backup-20190404060000 logSource="pkg/backup/backup.go:295"
time="2019-04-04T06:03:24Z" level=info msg="Backup completed" backup=velero/daily-full-backup-20190404060000 logSource="pkg/controller/backup_controller.go:460"
time="2019-04-04T06:03:40Z" level=info msg="Syncing contents of backup store into cluster" backupLocation=default controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:173"
time="2019-04-04T06:03:40Z" level=info msg="Got backups from backup store" backupCount=0 backupLocation=default controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:181"`

`velero backup get -n velero` is empty

**What did you expect to happen:**
All completed backups are displayed

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
These are fresh logs after I restarted velero pod:
`# kubectl logs deployment/velero -n velero
time="2019-04-04T06:25:54Z" level=info msg="setting log-level to INFO"
time="2019-04-04T06:25:54Z" level=info msg="Starting Velero server v0.11.0 (ab2fc65c02ecdcb9bb1690e3afe67a3b3196aebc)" logSource="pkg/cmd/server/server.go:134"
time="2019-04-04T06:25:54Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/registry.go:98" name=pod
time="2019-04-04T06:25:54Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/registry.go:98" name=pv
time="2019-04-04T06:25:54Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/registry.go:98" name=serviceaccount
time="2019-04-04T06:25:54Z" level=info msg="registering plugin" command=/velero kind=BlockStore logSource="pkg/plugin/registry.go:98" name=aws
time="2019-04-04T06:25:54Z" level=info msg="registering plugin" command=/velero kind=BlockStore logSource="pkg/plugin/registry.go:98" name=azure
time="2019-04-04T06:25:54Z" level=info msg="registering plugin" command=/velero kind=BlockStore logSource="pkg/plugin/registry.go:98" name=gcp
time="2019-04-04T06:25:54Z" level=info msg="registering plugin" command=/velero kind=ObjectStore logSource="pkg/plugin/registry.go:98" name=aws
time="2019-04-04T06:25:54Z" level=info msg="registering plugin" command=/velero kind=ObjectStore logSource="pkg/plugin/registry.go:98" name=azure
time="2019-04-04T06:25:54Z" level=info msg="registering plugin" command=/velero kind=ObjectStore logSource="pkg/plugin/registry.go:98" name=gcp
time="2019-04-04T06:25:54Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/registry.go:98" name=job
time="2019-04-04T06:25:54Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/registry.go:98" name=pod
time="2019-04-04T06:25:54Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/registry.go:98" name=restic
time="2019-04-04T06:25:54Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/registry.go:98" name=service
time="2019-04-04T06:25:54Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/registry.go:98" name=serviceaccount
time="2019-04-04T06:25:54Z" level=info msg="Checking existence of namespace" logSource="pkg/cmd/server/server.go:322" namespace=velero
time="2019-04-04T06:25:54Z" level=info msg="Namespace exists" logSource="pkg/cmd/server/server.go:328" namespace=velero
time="2019-04-04T06:25:56Z" level=info msg="Checking existence of Velero custom resource definitions" logSource="pkg/cmd/server/server.go:357"
time="2019-04-04T06:25:56Z" level=info msg="All Velero custom resource definitions exist" logSource="pkg/cmd/server/server.go:391"
time="2019-04-04T06:25:56Z" level=info msg="Checking that all backup storage locations are valid" logSource="pkg/cmd/server/server.go:398"
time="2019-04-04T06:25:56Z" level=warning msg="Velero restic daemonset not found; restic backups/restores will not work until it's created" logSource="pkg/cmd/server/server.go:457"
time="2019-04-04T06:25:56Z" level=info msg="Starting controllers" logSource="pkg/cmd/server/server.go:503"
time="2019-04-04T06:25:56Z" level=info msg="Starting metric server at address [:8085]" logSource="pkg/cmd/server/server.go:511"
time="2019-04-04T06:25:56Z" level=info msg="Starting controller" controller=backup-sync logSource="pkg/controller/generic_controller.go:76"
time="2019-04-04T06:25:56Z" level=info msg="Waiting for caches to sync" controller=backup-sync logSource="pkg/controller/generic_controller.go:79"
time="2019-04-04T06:25:56Z" level=info msg="Starting controller" controller=backup logSource="pkg/controller/generic_controller.go:76"
time="2019-04-04T06:25:56Z" level=info msg="Waiting for caches to sync" controller=backup logSource="pkg/controller/generic_controller.go:79"
time="2019-04-04T06:25:56Z" level=info msg="Starting controller" controller=gc-controller logSource="pkg/controller/generic_controller.go:76"
time="2019-04-04T06:25:56Z" level=info msg="Waiting for caches to sync" controller=gc-controller logSource="pkg/controller/generic_controller.go:79"
time="2019-04-04T06:25:56Z" level=info msg="Starting controller" controller=backup-deletion logSource="pkg/controller/generic_controller.go:76"
time="2019-04-04T06:25:56Z" level=info msg="Starting controller" controller=schedule logSource="pkg/controller/generic_controller.go:76"
time="2019-04-04T06:25:56Z" level=info msg="Waiting for caches to sync" controller=schedule logSource="pkg/controller/generic_controller.go:79"
time="2019-04-04T06:25:56Z" level=info msg="Starting controller" controller=downloadrequest logSource="pkg/controller/generic_controller.go:76"
time="2019-04-04T06:25:56Z" level=info msg="Waiting for caches to sync" controller=backup-deletion logSource="pkg/controller/generic_controller.go:79"
time="2019-04-04T06:25:56Z" level=info msg="Starting controller" controller=restore logSource="pkg/controller/generic_controller.go:76"
time="2019-04-04T06:25:56Z" level=info msg="Waiting for caches to sync" controller=downloadrequest logSource="pkg/controller/generic_controller.go:79"
time="2019-04-04T06:25:56Z" level=info msg="Waiting for caches to sync" controller=restore logSource="pkg/controller/generic_controller.go:79"
time="2019-04-04T06:25:56Z" level=info msg="Starting controller" controller=restic-repository logSource="pkg/controller/generic_controller.go:76"
time="2019-04-04T06:25:56Z" level=info msg="Waiting for caches to sync" controller=restic-repository logSource="pkg/controller/generic_controller.go:79"
time="2019-04-04T06:25:56Z" level=info msg="Starting controller" controller=serverstatusrequest logSource="pkg/controller/generic_controller.go:76"
time="2019-04-04T06:25:56Z" level=info msg="Waiting for caches to sync" controller=serverstatusrequest logSource="pkg/controller/generic_controller.go:79"
time="2019-04-04T06:25:56Z" level=info msg="Creating schedule halfday-sde-backup" controller=schedule logSource="pkg/controller/schedule_controller.go:105"
time="2019-04-04T06:25:56Z" level=info msg="Creating schedule daily-full-backup" controller=schedule logSource="pkg/controller/schedule_controller.go:105"
time="2019-04-04T06:25:56Z" level=info msg="Caches are synced" controller=schedule logSource="pkg/controller/generic_controller.go:83"
time="2019-04-04T06:25:56Z" level=info msg="Caches are synced" controller=serverstatusrequest logSource="pkg/controller/generic_controller.go:83"
time="2019-04-04T06:25:57Z" level=info msg="Caches are synced" controller=restic-repository logSource="pkg/controller/generic_controller.go:83"
time="2019-04-04T06:25:57Z" level=info msg="Caches are synced" controller=backup-sync logSource="pkg/controller/generic_controller.go:83"
time="2019-04-04T06:25:57Z" level=info msg="Caches are synced" controller=backup logSource="pkg/controller/generic_controller.go:83"
time="2019-04-04T06:25:57Z" level=info msg="Server started successfully" logSource="pkg/cmd/server/server.go:705"
time="2019-04-04T06:25:57Z" level=info msg="Caches are synced" controller=gc-controller logSource="pkg/controller/generic_controller.go:83"
time="2019-04-04T06:25:57Z" level=info msg="Caches are synced" controller=backup-deletion logSource="pkg/controller/generic_controller.go:83"
time="2019-04-04T06:25:57Z" level=info msg="Checking for expired DeleteBackupRequests" controller=backup-deletion logSource="pkg/controller/backup_deletion_controller.go:449"
time="2019-04-04T06:25:57Z" level=info msg="Caches are synced" controller=restore logSource="pkg/controller/generic_controller.go:83"
time="2019-04-04T06:25:57Z" level=info msg="Done checking for expired DeleteBackupRequests" controller=backup-deletion logSource="pkg/controller/backup_deletion_controller.go:477"
time="2019-04-04T06:25:57Z" level=info msg="Caches are synced" controller=downloadrequest logSource="pkg/controller/generic_controller.go:83"
time="2019-04-04T06:27:23Z" level=info msg="Processing new ServerStatusRequest" controller=serverstatusrequest key=velero/velero-cli-5mg4l logSource="pkg/serverstatusrequest/process.go:41"
time="2019-04-04T07:04:12Z" level=info msg="Syncing contents of backup store into cluster" backupLocation=default controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:173"
time="2019-04-04T07:04:12Z" level=info msg="Got backups from backup store" backupCount=0 backupLocation=default controller=backup-sync logSource="pkg/controller/backup_sync_controller.go:181"`
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
`# velero backup describe daily-full-backup-20190404060000 -n velero
An error occurred: backups.velero.io "daily-full-backup-20190404060000" not found
root@aws-staging-jump:/tmp/velero/templates# kubectl get backup/daily-full-backup-20190404060000 -n velero
Error from server (NotFound): backups.velero.io "daily-full-backup-20190404060000" not found`
* `velero backup logs <backupname>`
`# velero backup logs daily-full-backup-20190404060000
An error occurred: timed out waiting for download URL
`
apiVersion: v1
items:
- apiVersion: velero.io/v1
  kind: BackupStorageLocation
  metadata:
    clusterName: ""
    creationTimestamp: 2019-04-03T12:52:32Z
    generation: 1
    name: default
    namespace: velero
    resourceVersion: "19071042"
    selfLink: /apis/velero.io/v1/namespaces/velero/backupstoragelocations/default
    uid: 589834d9-560f-11e9-b8b9-026a80fceb4a
  spec:
    config:
      region: us-east-1
    objectStorage:
      bucket: cv-stage-velero-backup/us-east1/
    provider: aws
  status:
    lastSyncedRevision: b37dc008-5fe7-45c2-911f-da9129557079
    lastSyncedTime: 2019-04-04T08:04:37.564570026Z
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
`Client:
	Version: v0.11.0
	Git commit: ab2fc65c02ecdcb9bb1690e3afe67a3b3196aebc
Server:
	Version: v0.11.0`
- Kubernetes version (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:17:47Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.6", GitCommit:"a21fdbd78dde8f5447f5f6c331f7eb6f80bd684e", GitTreeState:"clean", BuildDate:"2018-07-26T10:04:08Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}`
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):
`DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.1 LTS"
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic`

**Comment by jprecuch** [comment]
```
# kubectl -n velero get backups.velero.io -o yaml
apiVersion: v1
items: []
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
root@aws-staging-jump:~# velero schedule get -o yaml
apiVersion: velero.io/v1
items:
- apiVersion: velero.io/v1
  kind: Schedule
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"velero.io/v1","kind":"Schedule","metadata":{"annotations":{},"name":"daily-full-backup","namespace":"velero"},"spec":{"schedule":"0 6 * * *","template":{"excludedNamespaces":["cbs"],"excludedResources":null,"hooks":{"resources":null},"includeClusterResources":null,"includedNamespaces":["*"],"includedResources":null,"labelSelector":null,"snapshotVolumes":true,"ttl":"168h0m0s"}}}
    creationTimestamp: 2019-04-03T13:33:16Z
    generation: 1
    name: daily-full-backup
    namespace: velero
    resourceVersion: "19355551"
    selfLink: /apis/velero.io/v1/namespaces/velero/schedules/daily-full-backup
    uid: 096d1685-5615-11e9-b24e-12f9c7b4c926
  spec:
    schedule: 0 6 * * *
    template:
      excludedNamespaces:
      - cbs
      excludedResources: null
      hooks:
        resources: null
      includeClusterResources: null
      includedNamespaces:
      - '*'
      includedResources: null
      labelSelector: null
      snapshotVolumes: true
      storageLocation: ""
      ttl: 168h0m0s
      volumeSnapshotLocations: null
  status:
    lastBackup: 2019-04-05T06:00:57Z
    phase: Enabled
    validationErrors: null
- apiVersion: velero.io/v1
  kind: Schedule
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"velero.io/v1","kind":"Schedule","metadata":{"annotations":{},"name":"halfday-sde-backup","namespace":"velero"},"spec":{"schedule":"00 */12 * * *","template":{"excludedNamespaces":["monitoring","backup","default","cbs"],"excludedResources":null,"hooks":{"resources":null},"includeClusterResources":null,"includedNamespaces":["sde"],"includedResources":null,"labelSelector":null,"snapshotVolumes":false,"ttl":"720h0m0s"}}}
    creationTimestamp: 2019-04-03T13:30:30Z
    generation: 1
    name: halfday-sde-backup
    namespace: velero
    resourceVersion: "19277674"
    selfLink: /apis/velero.io/v1/namespaces/velero/schedules/halfday-sde-backup
    uid: a6a3a8fe-5614-11e9-b807-0a80a3c2295c
  spec:
    schedule: 00 */12 * * *
    template:
      excludedNamespaces:
      - monitoring
      - backup
      - default
      - cbs
      excludedResources: null
      hooks:
        resources: null
      includeClusterResources: null
      includedNamespaces:
      - sde
      includedResources: null
      labelSelector: null
      snapshotVolumes: false
      storageLocation: ""
      ttl: 720h0m0s
      volumeSnapshotLocations: null
  status:
    lastBackup: 2019-04-05T00:00:57Z
    phase: Enabled
    validationErrors: null
kind: ScheduleList
metadata:
  resourceVersion: "19409479"
  selfLink: /apis/velero.io/v1/namespaces/velero/schedules

```

**Comment by jprecuch** [comment]
Thanks @skriss . Seems this resolved my issue. I'm able to see backups now and have them in separate folders using prefix.

**Comment by skriss** [comment]
Closing this issue as resolved; we'll track any change to how prefixes are specified via #1176.
