### ISSUE TITLE
Restic backup error with RancherOS

### ISSUE THREAD

**Issue by ipochi** [heptio/velero#1347]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
In RancherOS the the default location of `/var/lib/kubelet/pods` is not correct.
Rather it is `/opt/rke/var/lib/kubelet/pods`

Hence the restic-daemonset.yaml needs a documentation so that before deployment the yaml is edited to reflect the above change

      ```- name: host-pods
          hostPath:
            path: /var/lib/kubelet/pods
      ```
to

      ```
        - name: host-pods
          hostPath:
            path: /opt/rke/var/lib/kubelet/pods
      ```

**What did you expect to happen:**

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
* `velero backup logs <backupname>`
* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
* `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):  v0.11.0
- Kubernetes version (use `kubectl version`): v1.13.5
- Kubernetes installer & version: RKE
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): RancherOS

**Comment by skriss** [comment]
Closed by #1348
