### ISSUE TITLE
Restoring from AWS to Azure using Restic, backup storage location pointing to S3

### ISSUE THREAD

**Issue by ipochi** [heptio/velero#1356]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
Trying to restore Wordpress from AWS cluster to a cluster in Azure using Restic

Restore remains in InProgress State , PVC's get stuck in pending state.

1. Restore expects the storage class (gp2 from aws cluster) in azure cluster as well, I guess Velero not stripping the storage class name when taking backup

Backup completed successfully , when taking restore PV stuck in pending state.

**What did you expect to happen:**
successful restore.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
https://gist.github.com/ipochi/14d571373cc6529b57c94d716c8f6189
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`

```
apiVersion: velero.io/v1
kind: Backup
metadata:
  creationTimestamp: "2019-04-09T07:46:06Z"
  generation: 1
  labels:
    velero.io/storage-location: default
  name: wp-bkp-3
  namespace: velero
  resourceVersion: "348822"
  selfLink: /apis/velero.io/v1/namespaces/velero/backups/wp-bkp-3
  uid: 88676610-5a9b-11e9-88ea-0a73aec14de6
spec:
  excludedNamespaces: null
  excludedResources: null
  hooks:
    resources: null
  includeClusterResources: null
  includedNamespaces:
  - wordpress
  includedResources: null
  labelSelector: null
  storageLocation: default
  ttl: 720h0m0s
  volumeSnapshotLocations:
  - aws-default
status:
  completionTimestamp: "2019-04-09T07:46:23Z"
  expiration: "2019-05-09T07:46:06Z"
  phase: Completed
  startTimestamp: "2019-04-09T07:46:06Z"
  validationErrors: null
  version: 1
  volumeSnapshotsAttempted: 0
  volumeSnapshotsCompleted: 0
```
* `velero backup logs <backupname>`
https://gist.github.com/ipochi/8717254c531a4ce55b60817acec9b4ad
* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
``` kubectl get restore/az-restore -n velero -o yaml
apiVersion: velero.io/v1
kind: Restore
metadata:
  creationTimestamp: "2019-04-09T07:50:12Z"
  generation: 1
  name: az-restore
  namespace: velero
  resourceVersion: "4847554"
  selfLink: /apis/velero.io/v1/namespaces/velero/restores/az-restore
  uid: 1aa93d48-5a9c-11e9-9c62-5e522f2a7040
spec:
  backupName: wp-bkp-3
  excludedNamespaces: null
  excludedResources:
  - nodes
  - events
  - events.events.k8s.io
  - backups.ark.heptio.com
  - backups.velero.io
  - restores.ark.heptio.com
  - restores.velero.io
  includedNamespaces:
  - '*'
  includedResources: null
  namespaceMapping: {}
status:
  errors: 0
  failureReason: ""
  phase: InProgress
  validationErrors: null
  warnings: 0```

* `velero restore logs <restorename>`
```An error occurred: unable to retrieve logs because restore is not complete```

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]


**Environment:**

- Velero version (use `velero version`):  Version: v0.11.0
- Kubernetes version (use `kubectl version`):v1.12.5
- Kubernetes installer & version: 
- Cloud provider or hardware configuration: Azure
- OS (e.g. from `/etc/os-release`):

**Comment by ipochi** [comment]
Question: 

when I do `kubectl get backup -n velero`

In AWS cluster I see a list of backups that I took.

Why the same list appears in the Azure cluster ? I haven't taken backups there , the only thing both the clusters have in common is the S3 bucket pointing to the location.

the output is also different.

example: from  AWS cluster , where the backup was taken

```kubectl get backup/wp-bkp -n velero -o yaml
apiVersion: velero.io/v1
kind: Backup
metadata:
  creationTimestamp: "2019-04-06T11:28:38Z"
  generation: 1
  labels:
    velero.io/storage-location: default
  name: wp-bkp
  namespace: velero
  resourceVersion: "6195"
  selfLink: /apis/velero.io/v1/namespaces/velero/backups/wp-bkp
  uid: 1fb13087-585f-11e9-824e-0a6f85141ba8
spec:
  excludedNamespaces: null
  excludedResources: null
  hooks:
    resources: null
  includeClusterResources: null
  includedNamespaces:
  - default
  includedResources: null
  labelSelector: null
  storageLocation: default
  ttl: 720h0m0s
  volumeSnapshotLocations:
  - aws-default
status:
  completionTimestamp: "2019-04-06T11:28:56Z"
  expiration: "2019-05-06T11:28:38Z"
  phase: Completed
  startTimestamp: "2019-04-06T11:28:38Z"
  validationErrors: null
  version: 1
  volumeSnapshotsAttempted: 0
  volumeSnapshotsCompleted: 0```



below is from Azure cluster where I intend to take restore.

```
 kubectl get backup/wp-bkp -n velero -o yaml
apiVersion: velero.io/v1
kind: Backup
metadata:
  creationTimestamp: "2019-04-06T19:24:40Z"
  generation: 1
  labels:
    velero.io/storage-location: awst
  name: wp-bkp
  namespace: velero
  resourceVersion: "4490260"
  selfLink: /apis/velero.io/v1/namespaces/velero/backups/wp-bkp
  uid: 9fc97e8a-58a1-11e9-9c62-5e522f2a7040
spec:
  excludedNamespaces: null
  excludedResources: null
  hooks:
    resources: null
  includeClusterResources: null
  includedNamespaces:
  - default
  includedResources: null
  labelSelector: null
  storageLocation: awst
  ttl: 720h0m0s
  volumeSnapshotLocations:
  - aws-default
status:
  completionTimestamp: "2019-04-06T11:28:56Z"
  expiration: "2019-05-06T11:28:38Z"
  phase: Completed
  startTimestamp: "2019-04-06T11:28:38Z"
  validationErrors: null
  version: 1
  volumeSnapshotsAttempted: 0
  volumeSnapshotsCompleted: 0
```


diff fromazure.yaml fromaws.yaml
4c4
<   creationTimestamp: "2019-04-06T19:24:40Z"
---
>   creationTimestamp: "2019-04-06T11:28:38Z"
7c7
<     velero.io/storage-location: awst
---
>     velero.io/storage-location: default
10c10
<   resourceVersion: "4490260"
---
>   resourceVersion: "6195"
12c12
<   uid: 9fc97e8a-58a1-11e9-9c62-5e522f2a7040
---
>   uid: 1fb13087-585f-11e9-824e-0a6f85141ba8
23c23
<   storageLocation: awst
---
>   storageLocation: default

**Comment by nrb** [comment]
> Why the same list appears in the Azure cluster ? I haven't taken backups there , the only thing both the clusters have in common is the S3 bucket pointing to the location.

The S3 bucket is the authoritative source for backup information. Backups stored there are synced into any cluster pointing at the bucket, so that velero can find them in order to do the restore. When importing a backup into a cluster, the storageLocation field is set to the name of the backup storage location in the current cluster. The creationtimestamp, resourceversion, and uid fields on each backup are unique to the cluster they live in, since these are managed by Kubernetes for its own accounting. So these backup objects point to the same backup, but with slightly different metadata.

@skriss This seems to be attempting to replicate your webinar demo - how did you get around the storage class issue for that?

**Comment by ipochi** [comment]
so an update on this , thanks to debugging from @skriss 

Even creating a test PVC wit default storage class fails to provision a PV.

**Comment by skriss** [comment]
@ipochi were you able to resolve this?

**Comment by skriss** [comment]
Closing as unresponsive, reopen as needed!

**Comment by ipochi** [comment]
@skriss yes It was an issue with permissions on azure cluster.
