### ISSUE TITLE
Openebs PV not taking snapshot

### ISSUE THREAD

**Issue by davidq2q** [heptio/velero#1359]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
Creating a backup with velero of my elasticsearch cluster. That currently uses openebs cstor as storage provider. Openebs official documentation mentions velero to be used for backing up data. But it doesn't work, backup status says complete but is empty. Currently using minio that is hooked up to my NAS with a nfs pvc and setting up minio as a gateway for my nas. Logs state: 
```time="2019-04-10T14:29:36Z" level=info msg="PersistentVolume is not a supported volume type for snapshots, skipping." backup=velero/elasticsearch-10-4-2019-15-42 group=v1 groupResource=pods logSource="pkg/backup/item_backupper.go:436" name=pvc-d5c9beba-5ad3-11e9-be2c-8030e09cb251 namespace=qooqie-testing-resources persistentVolume=pvc-d5c9beba-5ad3-11e9-be2c-8030e09cb251```

**What did you expect to happen:**
Full backup of all resources that have label app=elasticsearch

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
* `velero backup logs <backupname>`
* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
* `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by nrb** [comment]
Hi @davidq2q.

Reading https://docs.openebs.io/docs/next/backup.html, I think their steps are incomplete.

At the bottom, it says

>The above backup and restore procedure is done using Restic, where the entire data is copied and restored in a bulk manner. More efficient backup and restore possible through incremental data snapshots using the OpenEBS ARK storage plugin which is planned for OpenEBS 0.9 release

However, they miss annotating the pod with the PV names. See our [restic docs](https://heptio.github.io/velero/v0.11.0/restic#back-up) for how to do that.

**Comment by skriss** [comment]
Note that OpenEBS has also recently published a Velero plugin for getting native snapshots of OpenEBS volumes - see https://github.com/openebs/velero-plugin.

I'm closing this issue for now due to prior comments + inactivity, but feel free to reopen as needed!
