### ISSUE TITLE
GCP: Configurable Snapshot location

### ISSUE THREAD

**Issue by ctrox** [heptio/velero#1361]
**Describe the solution you'd like**
Currently the snapshots of compute disks on GCP created by Velero are always multi-regional.  This can be changed in the `Snapshot` [struct](https://godoc.org/google.golang.org/api/compute/v1#Snapshot) by supplying `StorageLocations`.

**Anything else you would like to add:**
This has been added to the compute API very recently so I guess the vendored files would have to be updated. Also a new [VolumeSnapshotLocation config parameter](https://heptio.github.io/velero/v0.11.0/api-types/volumesnapshotlocation.html#gcp) would need to be added.

I might open a PR if you agree with the approach.

**Environment:**

- Velero version: v0.11.0
- Cloud provider or hardware configuration: GCP

**Comment by skriss** [comment]
@ctrox just to make sure I'm understanding - you're requesting the ability to specify the storage location for GCP volume snapshots (either a multi-regional location, or a region), as described in https://cloud.google.com/compute/docs/disks/create-snapshots#selecting_a_storage_location?

**Comment by ctrox** [comment]
Yes exactly, sorry for not being more precise.

This comes mostly from a compliance requirement that data stored in a region should not leave that region, which is currently not possible with Velero.

**Comment by skriss** [comment]
Got it. sounds reasonable to me to add an optional parameter to `config` for the GCP `VolumeSnapshotLocation`, and to use that as the value of `StorageLocations`.  The field is a slice - does that mean >1 location can be specified?

**Comment by ctrox** [comment]
I could not find a lot about this but it looks like you can store a snapshot in any location(s) you want with that: https://cloud.google.com/compute/docs/disks/create-snapshots#custom_location
