### ISSUE TITLE
Backup locations are invalid after plugin name changes

### ISSUE THREAD

**Issue by nrb** [heptio/velero#1363]
**What steps did you take and what happened:**
Running on `master`, the provider name `gcp` is no longer valid inside of a backupstoratelocation.

However, `velero.io/gcp` is.

` GOOGLE_APPLICATION_CREDENTIALS=~/credentials-velero-gke v server --default-volume-snapshot-locations gcp:gcp-default --log-level debug`

and the following BackupStorageLocation definition:

```yaml
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  creationTimestamp: 2019-04-12T16:14:17Z
  generation: 4
  labels:
    component: velero
  name: default
  namespace: velero
  resourceVersion: "1851"
  selfLink: /apis/velero.io/v1/namespaces/velero/backupstoragelocations/default
  uid: 05d00579-5d3e-11e9-80f1-0242aa5bd293
spec:
  config: {}
  objectStorage:
    bucket: <mybucket>
    prefix: ""
  provider: gcp
status:
  lastSyncedRevision: a56d8e68-7017-4fb6-9a80-ec09433ae517
  lastSyncedTime: 2019-04-12T16:16:20.160871498Z
```

results in

`An error occurred: some backup storage locations are invalid: error getting backup store for location "default": unable to locate ObjectStore plugin named gcp`

and the server halting.

```yaml
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  creationTimestamp: 2019-04-12T16:14:17Z
  generation: 4
  labels:
    component: velero
  name: default
  namespace: velero
  resourceVersion: "1851"
  selfLink: /apis/velero.io/v1/namespaces/velero/backupstoragelocations/default
  uid: 05d00579-5d3e-11e9-80f1-0242aa5bd293
spec:
  config: {}
  objectStorage:
    bucket: <mybucket>
    prefix: ""
  provider: velero.io/gcp
status:
  lastSyncedRevision: a56d8e68-7017-4fb6-9a80-ec09433ae517
  lastSyncedTime: 2019-04-12T16:16:20.160871498Z
```

allows the server to start up as expected.

**What did you expect to happen:**
At least for the in-tree plugins, the user should only have to specify the provider name, not the `velero.io` domain prefix.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
```
Client:
        Version: master
        Git commit: abee09aa2d64813f9971a0103dcca6d5f4ab370a
```

**Comment by nrb** [comment]
It looks like this is coming from [this line](https://github.com/heptio/velero/blob/master/pkg/plugin/clientmgmt/manager.go#L127). Need to think on how best to address this, since a) we want qualified plugin names and b) we don't want users to type all the qualified names out every time.

**Comment by skriss** [comment]
Ah, yeah, this is obvious in retrospect. Obviously :) One option is in the `GetObjectStore`, `GetVolumeSnapshotter`, etc. methods in `manager.go`, we check for a domain prefix on `name`, and if none is specified, we automatically prefix with `velero.io/`.  This means the plugins *are* actually still registered as `velero.io/aws`, etc., but the user doesn't have to specify `velero.io/` in their `provider` field.

**Comment by nrb** [comment]
Yeah, that was kind of what I was thinking. However, for non-Velero plugins, it means users still have to provide the fully qualified name, so it makes a distinction.  I also thought about just prepending `velero.io` to the provider in the `install` command, but that means any YAML provided would have to add it manually, too...

I'm inclined to do what you said for 1.0, though. It means however the BSL was made, we can still fetch it just fine for most users. Partners will need to update their docs, though.

**Comment by skriss** [comment]
Yeah, I'd prefer not to break existing installations for the built-in providers on upgrading to 1.0, so retaining the ability to just specify `aws`, etc. is nice. But yeah, this is definitely a breaking change for external plugin authors + users that we'll need to publicize.

**Comment by nrb** [comment]
Ok, I'll get a patch in for this.
