### ISSUE TITLE
Ability to declare multiple sets of credentials per provider

### ISSUE THREAD

**Issue by dymurray** [heptio/velero#1368]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Currently Velero only looks for one secret `cloud-credentials` and references this secret when a provider is referenced in a backupstoragelocation. This is problematic because a user might want to configure multiple S3 buckets with multiple backupstoragelocations. AWS recommends that unique credentials should be used for each bucket so it is a bad approach to expect one set of credentials for each provider.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

A BSL should be able to declare a secret reference on creation so that multiple sets of credentials can be created in the velero namespace and referenced on backup.

**Comment by nrb** [comment]
This may be a duplicate of #1064

**Comment by dymurray** [comment]
Yes it is, thanks! I will close.

**Comment by dinesh** [comment]
It seems #1064 would solve the problem if all of the backup-locations are based on AWS. What if I want to have 2 AWS based locations with different keys and one Azure-based location. Will the secret `cloud-credentials` allow such scenario? I guess we should have a field in backup-location CRD to reference the secret containing the credentials.

**Comment by dinesh** [comment]
@skriss thanks for the input, wasn't aware of the environment variables. For Aws based credentials I can add multiple profiles to manage different credentials. Does `AZURE_CREDENTIALS_FILE ` also support multiple profiles?

**Comment by skriss** [comment]
no, the Azure file does not support a similar concept - it's just one set of credentials.
