### ISSUE TITLE
Velero fails on microk8s with S3 storage

### ISSUE THREAD

**Issue by paralika** [heptio/velero#1381]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
I am trying to configure Velero on microk8s to restore the backup. My backup is on aws S3.

BackupStorageLocation looks like:

> apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  name: default
  namespace: velero
spec:
  provider: aws
  objectStorage:
    bucket: test-backup-ue2
  config:
    region: us-east-2

I am getting below error:
`An error occurred: some backup storage locations are invalid: backup store for location "default" is invalid (if upgrading from a pre-v0.10 version of Velero, please refer to https://heptio.github.io/velero/v0.10.0/storage-layout-reorg-v0.10 for instructions): rpc error: code = Unknown desc = RequestError: send request failed
caused by: Get https://test-backup-ue2.s3.us-east-2.amazonaws.com/?delimiter=%!F(MISSING)&list-type=2&prefix=: dial tcp: lookup test-backup-ue2.s3.us-east-2.amazonaws.com on 132.186.71.142:53: read udp 10.1.1.10:50203->132.186.71.142:53: i/o timeout`

**What did you expect to happen:**
Right now I cannot backup or restore to existing S3 from microk8s.  It should work without any issue. 

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
* `velero backup logs <backupname>`
* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
* `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
Client:
	Version: v0.11.0
	Git commit: ab2fc65c02ecdcb9bb1690e3afe67a3b3196aebc
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:52:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:41:57Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
- Cloud provider or hardware configuration: 
   microk8s on local VM and storage at AWS S3. 
- OS (e.g. from `/etc/os-release`):
Ubuntu 16.04.4 LTS (Xenial Xerus)

**Comment by nrb** [comment]
Hi @paralika, can you provide the BackupStorageLocation YAML with the indentation?

**Comment by paralika** [comment]
@nrb please see the attached requested file. 
[05-backupstoragelocation.yaml.txt](https://github.com/heptio/velero/files/3102312/05-backupstoragelocation.yaml.txt)

**Comment by skriss** [comment]
it sounds like maybe there's a DNS issue within your cluster? Are you able to reach the S3 URL from within a non-velero pod running in your cluster?

**Comment by paralika** [comment]
Thanks for pointing this out. Its is DNS issue in microk8s.

**Comment by cmmani** [comment]
Can you please explain what's the DNS issue you faced. Because Im also face the same error. please explain what is the DNS Issue....?       
That DNS issue is in backup storage location yaml file...??

**Comment by brokencode64** [comment]
Also having this issue with "x509: certificate is valid for . . . not . . .".

**Comment by airmonitor** [comment]
yup, version velero server v.1.42 returning same error on my microk8s cluster
