### ISSUE TITLE
config/azure/ yaml files and other providers missing in velero-v1.0.0-alpha.2-darwin-amd64

### ISSUE THREAD

**Issue by arianitu** [heptio/velero#1402]
**What steps did you take and what happened:**
I downloaded the latest .tar.gz and noticed config/azure or any other providers are no longer there. Was this expected, is `install` suppose to replace it?

If so, I don't know how to use `install` to only push only `deployment.yml`  and `restic` since those were the only two things I need to push. 

`install` expects some config values that I think are in secrets at the moment for us.

**What did you expect to happen:**
config/azure and other config/ yaml files should be there.

**Comment by skriss** [comment]
@arianitu yeah, we're replacing the static YAML files with `velero install`.  If you look at the `docs/` dir in `master`, you can find examples of how to run that. If you're trying to update an existing install, you'll probably want to `velero install [flags] --dry-run -o yaml`, and then `kubectl apply` it.

Alternately, you can just update the image tag in your deployment and daemonset to `v1.0.0-alpha.2` - I think that should be the only change required.

**Comment by arianitu** [comment]
Okay thought so, I ended up just changing the image tags. It seems to be running now and I've ran my first backup. I ran into a different issue, but I'll create a new issue for it.
