### ISSUE TITLE
Restic data not deleted when deleting backup

### ISSUE THREAD

**Issue by vitobotta** [heptio/velero#1408]
**What steps did you take and what happened:**
I'm not sure if it's a bug, but I can't see why this behavior would be intended. Basically if I take a backup including volumes with Restic to S3, the data is stored in the restic subdirectory as expected. However, when I delete a backup the associated restic data is not deleted and remains in the bucket.

**What did you expect to happen:**
I would expect all the data concerning a backup to be deleted when I delete the backup.

**The output of the following commands will help us better understand what's going on**:

* `kubectl logs deployment/velero -n velero`
https://ybin.me/p/0e40ccf80b0067b7#5BGOTIeE/IgyFGK54R+1bbKixhdDXtfgZV9yjqnEpk0=

**Environment:**

- Velero version (use `velero version`): 

Client:
	Version: 0.11.0
	Git commit: -
Server:
	Version: v0.11.0

- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.0", GitCommit:"641856db18352033a0d96dbc99153fa3b27298e5", GitTreeState:"clean", BuildDate:"2019-03-26T00:04:52Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes installer & version:
Cluster deployed with Rancher 2.2.2.

- Cloud provider or hardware configuration:
Hetzner Cloud, nodes with 4 cores and 16 GB of ram.

- OS (e.g. from `/etc/os-release`):
Ubuntu 18.04

**Comment by skriss** [comment]
When the backup is deleted we run "restic forget" which removes the restic snapshot metadata, but the actual data blocks are not removed until we run "restic prune" which is a periodic thing (it takes awhile).

**Comment by vitobotta** [comment]
@skriss Oh I must have missed it in the docs. Thanks! What happens if I have the same storage configured with two clusters (to do a migration for example)? Will the prune task be run by both clusters?

**Comment by skriss** [comment]
by default, yeah. we have an issue in the backlog to enable backup storage locations to be "read-only" for specific clusters, so this wouldn't happen.

**Comment by vitobotta** [comment]
Ok. I'm gonna close this then. Thanks!
