### ISSUE TITLE
Docs enhancement: Restic vs native cloud provider

### ISSUE THREAD

**Issue by jonasrosland** [heptio/velero#1409]
I think it could be useful for both new and current users to understand the when and why of restic backups vs native cloud provider snapshots.

Example:

If you're on AWS, Azure, GCE etc., you can easily rely on the cloud provider's native snapshot functionality. Restic could be used for cross-cloud migration of data

For on-premises K8s implementations, you would most likely use full restic backups as the native snapshot functionality in your environment might not be supported yet.

**Comment by skriss** [comment]
@jonasrosland we do discuss this a little bit in https://heptio.github.io/velero/v0.11.0/restic - do you think what we have is sufficient, or does it miss things?

**Comment by skriss** [comment]
@jonasrosland interested in whether you think what we have documented now is sufficient, or misses things.

**Comment by jonasrosland** [comment]
I think it's been documented properly, closing, thank you!
