### ISSUE TITLE
download backup command: check if backup exists first

### ISSUE THREAD

**Issue by immesys** [heptio/velero#1410]
**What steps did you take and what happened:**
I created a backup (called "initial"), which completed successfully.
I then tried to download the backup and got
```
An error occurred: timed out waiting for download URL
```

The velero pod logs has
```
time="2019-04-27T01:38:11Z" level=error msg="Error in syncHandler, re-adding item to queue" controller=downloadrequest error="backup.velero.io \"inital\" not found" error.file="download_request_controller.go:166" error.function="(*downloadRequestController).generatePreSignedURL" key=velero/inital-20190426183811 logSource="pkg/controller/generic_controller.go:137"
```

**What did you expect to happen:**
I expected it to download. 

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
Relevant message pasted above

* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
```
Name:         initial
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"velero.io/v1","kind":"Backup","metadata":{"annotations":{},"creationTimestamp":null,"name":"initial","namespace":"velero"},"spec":{"excludedNamespaces":null,"excludedResources":null,"hooks":{"resources":null},"includeClusterResources":null,"includedNamespaces":["*"],"includedResources":null,"labelSelector":null,"storageLocation":"","ttl":"720h0m0s","volumeSnapshotLocations":null}}


Phase:  Completed

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2019-04-26 18:23:02 -0700 PDT
Completed:  2019-04-26 18:25:33 -0700 PDT

Expiration:  2019-05-26 18:23:01 -0700 PDT

Validation errors:  <none>

Persistent Volumes:  5 of 5 snapshots completed successfully (specify --details for more information)
```
* `velero backup logs <backupname>`
That's quite long, I can provide if it's relevant

**Environment:**

- Velero version (use `velero version`): 
0.11.0
- Kubernetes version (use `kubectl version`):
1.11.9
- Kubernetes installer & version:
kops 1.11
- Cloud provider or hardware configuration:
AWS

**Comment by immesys** [comment]
The backup definitely exists:
```
kubectl -n velero get backup
NAME                         AGE
initial                      36m
```

**Comment by skriss** [comment]
@immesys looks like a typo in your `velero backup download` command - note the error message says backup `inital` not found (missing `i`). Try `velero backup download initial`.

**Comment by immesys** [comment]
Ah, so this is user error, my bad. Perhaps it might be nice if it checked if the backup exists and returned a helpful message rather than saying "timed out waiting for download URL". I've noticed some other velero commands do that check (like restore)

**Comment by skriss** [comment]
good idea, should be easy to add.

**Comment by skriss** [comment]
The `velero restore create` command validates that the specified backup exists (see https://github.com/heptio/velero/blob/master/pkg/cmd/cli/restore/create.go#L161).  We should do the same for the `velero backup download` command.  We should:
- [ ] update the Validate func (https://github.com/heptio/velero/blob/master/pkg/cmd/cli/backup/download.go#L73) to take a `client.Factory` as a third parameter
- [ ] update the Validate func to check that the specified backup is gettable via the client, similarly to the restore command linked above
