### ISSUE TITLE
Unable to restore volume with Restic in K3S cluster

### ISSUE THREAD

**Issue by vitobotta** [heptio/velero#1411]
I am having trouble restoring a backup that includes volumes in a K3S cluster. Restore fails and in the logs I see this error:

```
pod volume restore failed: error restoring volume: error identifying path of volume: expected one matching path, got 0
```
Any idea of what I could do or how I could investigate the issue more? Thanks!

**Comment by KellyGriffin** [comment]
I suspect this may because the kublet plugin directory is different in K3S - but can't confirm where/how Velero uses or looks for the plugin

**Comment by skriss** [comment]
@vitobotta can you confirm that K3s uses `/var/lib/kubelet` as its kubelet base dir? Also, this sometimes comes up when mount propagation isn't enabled - can you confirm whether or not it's enabled in K3s?  We can look at some additional things beyond that but I'd start there.

**Comment by KellyGriffin** [comment]
The Kubelet base dir is "/var/lib/rancher/k3s/agent/kubelet".

**Comment by skriss** [comment]
ah - so then the velero daemonset needs to be updated -- it has a `hostPath` mount of `/var/lib/kubelet` by default - I'd try updating that to `/var/lib/rancher/k3s/agent/kubelet`

**Comment by skriss** [comment]
minor correction: the daemonset mounts `/var/lib/kubelet/pods`, so make sure to include the `/pods` on the end of the updated path

**Comment by vitobotta** [comment]
YAY! It works :D I set the `hostPath` to `/var/lib/rancher/k3s/agent/kubelet/pods` and I was able to restore a deployment with a volume successfully. No errors and the data is there. 💯 

Thanks a lot guys!

**Comment by skriss** [comment]
woohoo! :tada:
