### ISSUE TITLE
GCP directory and .yaml files not included in v1.0.0-alpha.2 tar balls

### ISSUE THREAD

**Issue by AndyBaird** [heptio/velero#1412]
The current downloads of v1.0.0-alpha.2 tar balls did not have the necessary gcp directory or .yaml files. I used the files from v1.0.0-alpha.1 to continue my backup but they need to be restored so the otherwise [stellar docs](https://heptio.github.io/velero/v0.11.0/gcp-config.html) can be followed.

**Comment by skriss** [comment]
hey @AndyBaird thanks for trying out our alphas! We're moving away from including static YAML for deployment, and have replaced it with the `velero install` command, which can either apply YAML directly to your cluster or can output it for you to review/modify/apply using the `--dry-run -o yaml` flags.  Please see our updated docs at https://heptio.github.io/velero/v1.0.0-alpha.2/gcp-config and let us know if you have any questions/issues!

**Comment by skriss** [comment]
Closing as this is by design - please reopen if you need any further assistance!
