### ISSUE TITLE
Can subfolders be created in buckets within which backups can be created

### ISSUE THREAD

**Issue by dushyant03** [heptio/velero#1419]
**Describe the solution you'd like**
I have setup velero on one of my gke clusters on gcp, storing the backups on google storage per namespace.
I would like to store the backups/schedules that are created within subfolders for each namespace.

example: 
Bucket name : <test-velero>
One folder for each namespace within the bucket, and the schedules per namespace to be stored in the respective folders.

Is there anyway velero would let me create these subfolders within the buckets to separate my backups based on namespace?

**Environment:**

- Velero version (use `velero version`): v1.0.0-alpha.2
- Kubernetes version (use `kubectl version`): v1.11.3
- Kubernetes installer & version:
- Cloud provider or hardware configuration: GCP
- OS (e.g. from `/etc/os-release`): MacOS mojave

**Comment by skriss** [comment]
@dushyant03 this is possible, using `BackupStorageLocations`.  You'd need to create several of these up-front, one per namespace.  For each one, you'd give it the bucket name and then a unique prefix -- something like:

```
velero backup-location create ns-1 \
    --provider gcp \
    --bucket my-bucket \
    --prefix ns-1-prefix
```

Then, when you create your schedules, make sure to specify the `--storage-location` flag for each, with the name of the appropriate `BackupStorageLocation` as the value.

**Comment by dushyant03** [comment]
Perfect! thank you 👍

**Comment by dushyant03** [comment]
@skriss 

Hi Skriss,

Is there a way to delete backup locations? i followed the instructions above to create backup locations, and created schedules, it worked initially but now i get the following error in the velero pods.

```time="2019-05-02T11:28:02Z" level=info msg="All Velero custom resource definitions exist" logSource="pkg/cmd/server/server.go:424"
time="2019-05-02T11:28:02Z" level=info msg="Checking that all backup storage locations are valid" logSource="pkg/cmd/server/server.go:431"
An error occurred: some backup storage locations are invalid: backup store for location "default" is invalid (if upgrading from a pre-v0.10 version of Velero, please refer to https://heptio.github.io/velero/v0.10.0/storage-layout-reorg-v0.10 for instructions): Backup store contains 4 invalid top-level directories: [ingress kube-system kubeless ...]```

**Comment by skriss** [comment]
you can use `kubectl -n velero delete backupstoragelocation.velero.io NAME` to delete it from Velero. It sounds like maybe you still have one pointing to the top-level bucket?

**Comment by dushyant03** [comment]
Yeah just figured it out too, and deleted the backup-locations. The pods are fine now.
Also created the backuplocations again. Should the default backup-location be removed? Below are the ones i have now.

```╰─$ velero get backup-location
NAME             PROVIDER   BUCKET/PREFIX
default          gcp        cpt-velero-development
ingress-backup   gcp        cpt-velero-development/ingress-daily
staging-backup   gcp        cpt-velero-development/staging-daily

**Comment by skriss** [comment]
yeah, if you're using prefixes under `cpt-velero-development`, then you don't want to have a location that points to the root of `cpt-velero-development`.  Where do you want backups to go if the user doesn't specify a location when creating a schedule/backup? I'd update the `default` BSL to point there -- maybe just use a "default" prefix under your bucket.  You can `kubectl edit` the YAML to add the prefix.

**Comment by dushyant03** [comment]
ok great, i was able to clean it up nice. And have create schedules also. Looks good so far.
I will check it out for a few days. Thank you so much for your help.
Also is there going to be UI in the future?

**Comment by skriss** [comment]
Sounds good! We don't have any current plans to create a GUI, no. It'd be a nice project for someone to work on!

**Comment by skriss** [comment]
Sounds like this is resolved for you so closing the issue. Feel free to reopen or open new issues as needed.

**Comment by banyalasuresh** [comment]
Assist me with the solution.
I have setup velero on one of my EKS clusters on AWS, storing the backups on AWS S3bucket inside sub folder per namespace.
I would like to store the backups/schedules that are created within subfolders for each namespace.

example:
Bucket name :
One folder for each namespace within the bucket, and the schedules per namespace to be stored in the respective folders.

i created sub folder in my EKS cluster using below commands but its showing like PHASE is UNKONWN last VALIDATION  is UNKONWN and backups is getting fail please assist me to push backups inside the AWS S3bucket subfolders. thanks you so much in advance seeking help please let me know if need any additional information thank you so much.
