### ISSUE TITLE
Exclude folders for backing up

### ISSUE THREAD

**Issue by tyrinwu** [heptio/velero#1430]
**Describe the solution you'd like**
I am looking for a way to exclude some files that I want to backup in a persistent volume.

There are ways for `restic` to exclude files from backing up (See https://restic.readthedocs.io/en/latest/040_backup.html#including-and-excluding-files), We would hope to see something like this in Velero, say by adding an extra label to a pod telling this pod what folders you don't want to include in the backup process of that persistent volumes.

**Proposed Solution**

Given 
`kubectl -n foo annotate pod/sample backup.velero.io/backup-volumes=PERSISTENT_VOLUME_NAME`

we may further to do

`kubectl -n foo annotate pod/sample backup.velero.io/PERSISTENT_VOLUME_NAME/backup-exclude=FOLDER_1,FOLDER_2` to tell Velero and the underlying restic to ignore FOLDER_1 and FOLDER_2 when backing up.

**Comment by bfabec** [comment]
As a workaround, is there anyway to pass the flags we want to restic via the ExtraFlags option shown here: https://github.com/heptio/velero/blob/master/pkg/restic/command_factory.go#L37

**Comment by bfabec** [comment]
Hi @skriss - are there any workarounds that you are aware of that you could share that could potentially do this? The problem that is we are trying to backup a Cassandra PersistentVolume but that has a database we want to exclude because the size can grow to an enormous size, but we want to backup other databases.

**Comment by skriss** [comment]
I don't think there are any workarounds without making a code change at this point.

**Comment by skriss** [comment]
The team has discussed and we're not planning to support individual file/directory backup or exclusion, so closing this issue.

**Comment by talhalatifkhan** [comment]
bump, are there any plans to introduce it now?

**Comment by TheQueenIsDead** [comment]
:+1: for directory exclusion, restic supports this natively, it would be great to be able to pass restic flags through from Velero
https://restic.readthedocs.io/en/latest/040_backup.html#excluding-files

**Comment by halaMayday** [comment]
Are there any plans to introduce it now?
