### ISSUE TITLE
Pass arguments to the restic backup/restore commands

### ISSUE THREAD

**Issue by bfabec** [heptio/velero#1431]
**Describe the solution you'd like**
We'd like the ability to exclude files/directories from the restic backup, potentially by passing the exclude arguments into the backup command. 

Examples in restic with arguments:
https://restic.readthedocs.io/en/latest/040_backup.html#including-and-excluding-files

We didn't see anything in the velero documentation that showed this could be done. Thanks!

**Comment by skriss** [comment]
@bfabec is this a duplicate of #1430?

**Comment by bfabec** [comment]
Yup, thanks @skriss !
