### ISSUE TITLE
"Locations" documentation seems out of place

### ISSUE THREAD

**Issue by alexbrand** [heptio/velero#1449]
The [Locations](https://heptio.github.io/velero/v0.11.0/locations) documentation is currently in the "Upgrade" section of the documentation. 

Information about Backup Storage Locations and Volume Snapshot Locations seems to be unrelated to upgrading.

**Comment by skriss** [comment]
Thanks @alexbrand, this is absolutely true. In the latest docs (https://heptio.github.io/velero/v1.0.0-beta.1/), we've done some rearranging and moved this page under Introduction. Does that seem more reasonable?

**Comment by alexbrand** [comment]
Oh awesome! I was looking at the v0.11 docs. This looks great 👍
