### ISSUE TITLE
API documentation is not accessible from the documentation site's sidebar

### ISSUE THREAD

**Issue by alexbrand** [heptio/velero#1450]
There does not appear to be a link to the API documentation from the documentation site's sidebar.

**Comment by nrb** [comment]
@alexbrand What API documentation are you looking for? A REST API, or the Go API?

**Comment by alexbrand** [comment]
I was thinking about this:
https://heptio.github.io/velero/v0.11.0/api-types/

Interestingly other API types are missing, such as:
https://heptio.github.io/velero/v0.11.0/api-types/backupstoragelocation.html

**Comment by nrb** [comment]
Got it! I think it's reasonable to get these linked in. We can look at doing this.

**Comment by OceanChen2012** [comment]
Hi Nolan, Where Can I see the REST API of Velero? I need to know the relevant input and output parameters.

**Comment by carlisia** [comment]
Hey @OceanChen2012, Velero does not expose a REST API. You may use some Go packages as libraries (but please see this: https://github.com/vmware-tanzu/velero/issues/2654). You may also use the kubernetes API to access and manipulate the Velero custom resources.
