### ISSUE TITLE
Unable to deploy velero 

### ISSUE THREAD

**Issue by gkdba87** [heptio/velero#1452]
HI 
I am trying to install Velero  on kubernates using below url
(https://github.com/heptio/velero/blob/master/docs/ibm-config.md)

command: velero install --bucket team-cicd --provider aws --secret-file ./credentials-velero --backup-location-config s3ForcePathStyle="true",s3Url=http://laas.com --namespace=dev.
following are the deploy and pod logs
deploy logs:
![image](https://user-images.githubusercontent.com/22393158/57222552-a5891680-7020-11e9-8b43-87781b5de90c.png)

pod logs :
![image](https://user-images.githubusercontent.com/22393158/57222676-129cac00-7021-11e9-967f-824d67d553cb.png)

Please look into this issue, do the needful.

**Comment by typhoonrr** [comment]
Hey, i have exactly the same error. 

An error occurred: some backup storage locations are invalid: error getting backup store for location "default": rpc error: code = Unknown desc = unable to get all required environment variables: the following keys do not have values: AZURE_TENANT_ID, AZURE_CLIENT_ID, AZURE_CLIENT_SECRET, AZURE_SUBSCRIPTION_ID; error getting backup store for location "velero": rpc error: code = Unknown desc = config has invalid keys [region]; valid keys are [resourceGroup storageAccount bucket]

Anyone has an idea how to edit those values?

Marc

**Comment by skriss** [comment]
@gkdba87 can you provide the output of `velero backup-location get -o yaml`?

**Comment by skriss** [comment]
@typhoonrr it sounds like you're missing a bunch of the necessary credentials and config for Azure.  If you're using the v1.0 beta, did you follow the instructions here? https://heptio.github.io/velero/v1.0.0-beta.1/azure-config

**Comment by typhoonrr** [comment]
@skriss yeah i had an issue with my secret, it's working now.

**Comment by gkdba87** [comment]
![image](https://user-images.githubusercontent.com/22393158/57283426-bb541580-70cc-11e9-8b6d-1e588ffec983.png)
@skriss 
i could try to install Velero from scratch. please do needful

**Comment by gkdba87** [comment]
@skriss 
 Its pointed to wrong s3URL, can i change ?

**Comment by gkdba87** [comment]
@skriss 
please find updated state
![image](https://user-images.githubusercontent.com/22393158/57297911-7c36bc00-70ee-11e9-83d9-6494aa7d006c.png)

**Comment by skriss** [comment]
@gkdba87 I'm a little confused now.  Are you trying to install `v0.11.0` or `v1.0.0-beta.1`?  Also, in your latest screenshot it looks like the `cloud-credentials` secret does not exist in the `velero` namespace or doesn't have the right content.  Are you still using `velero install`, or something else?

**Comment by gkdba87** [comment]
@skriss Now i have successfully installed Velero  v1.0.0-beta.1.
![image](https://user-images.githubusercontent.com/22393158/57431683-334b4880-7251-11e9-965a-556697ea6ba9.png)
* Above setup was required empty bucket

**Comment by gkdba87** [comment]
@skriss Now i am trying to to create backup of namespace , using following command
 ### velero backup create bkp1 --include-namespaces -demo1
But aim geeting errors. Can you please look into this and give suggestion.
![image](https://user-images.githubusercontent.com/22393158/57441536-c98a6900-7267-11e9-86fc-cdf0ff98c76b.png)

**Comment by skriss** [comment]
@gkdba87 we don't have a `VolumeSnapshotter` for IBM - if you want to do volume backups, you'll need to use restic.  You should `kubectl -n velero delete volumesnapshotlocations --all` to remove any configs for the VolumeSnapshotters.

**Comment by gkdba87** [comment]
@skriss Thanks for the update. Can i install With restic( Re-install velero and Install velero with Restic)
please correct me if i am wrong

**Comment by skriss** [comment]
yeah, you can reinstall and use the `--use-restic` flag. Note that you'll still need to `kubectl -n velero delete volumesnapshotlocations --all` afterwards - we don't yet have a way to disable those from being created. It's being worked on in #1462

**Comment by gkdba87** [comment]
root@cdldvawxvat0001:/home/venugva> kubectl  delete volumesnapshotlocations --all -n cicd
No resources found

**Comment by gkdba87** [comment]
@skriss  Now i have try to  install velero with "-use-restic" flag. And getting  following error and it seems to be Demon set availability ZERO.
![image](https://user-images.githubusercontent.com/22393158/57475556-2a3e9380-72b2-11e9-8334-debb6600d65b.png)
Notified some of restic pods going to  CrashLoopBackOff
![image](https://user-images.githubusercontent.com/22393158/57475708-7db0e180-72b2-11e9-987c-04b5498a590e.png)

**Comment by skriss** [comment]
is that the namespace you have velero deployed into? you can also try `kubectl delete volumesnapshotlocations --all --all-namespaces` -- but as long as there are none, you're good.

**Comment by gkdba87** [comment]
@skriss unable to delete "snapshot-location" . can you please look into below
![image](https://user-images.githubusercontent.com/22393158/57612928-606e6280-7593-11e9-89bf-ac82bffbf7c6.png)

**Comment by gkdba87** [comment]
@skriss  i have deployed velero + restic in one of our namespace. Some of pods are going to error state. and also Damon-set also not available state. I have limited CPUs and Memory for Namespace. How i can restrict Resources @ "velero install" command level . Can plese look into following error(**velero Pod is up and running fine)

![image](https://user-images.githubusercontent.com/22393158/57616932-1b4f2e00-759d-11e9-9170-1ca66df59408.png)

**Comment by skriss** [comment]
Can you `kubectl describe` the pods that are crashing?

Right now we don't have support for adding requests/limits via `velero install`.  You can always dump the generated YAML via `velero install ... --dry-run -o yaml` and manually add what you need, then `kubectl apply` it.

cc @nrb -- do we want to add request/limit support?

**Comment by gkdba87** [comment]
@skriss un-healthy describe pod 
![image](https://user-images.githubusercontent.com/22393158/57641589-fe355200-75d2-11e9-8a4e-bad657c50375.png)
healthy describe pod output
![image](https://user-images.githubusercontent.com/22393158/57641625-17d69980-75d3-11e9-87ec-469e4dee8c54.png)

**Comment by skriss** [comment]
I don't see anything showing What the problem is -- what about `kubectl logs`?

**Comment by gkdba87** [comment]
unhealthy pod logs
![image](https://user-images.githubusercontent.com/22393158/57642306-9da71480-75d4-11e9-8245-d71601d24e6e.png)
Heathy pod logs
![image](https://user-images.githubusercontent.com/22393158/57642331-b0b9e480-75d4-11e9-8d61-d04d4b9a1137.png)

Now i get yaml file using  dry-run, and i will set cpu limits and resource. see wat happend?

**Comment by nrb** [comment]
@skriss I’m not sure on adding those flags to the install command. Wouldn’t be hard to do, but the more we add the more we’re maintaining in parallel to the Helm chart

**Comment by skriss** [comment]
xref #94

**Comment by VihanAgarwal97** [comment]
I'm having a similar issue. 
```
$ velero backup-location get
WARNING: error retrieving namespace from config file: stat /Users/vihanagarwal/.config/velero/config.json: permission denied
NAME      PROVIDER   BUCKET/PREFIX
default   aws        test-cluster-velero-backups
```

**Comment by skriss** [comment]
@VihanAgarwal97 did you use `velero install`? I would double-check that the content of the file you provided for the `--credentials-file` flag is a valid AWS access key

**Comment by VihanAgarwal97** [comment]
Do you mean  the `--secret-file` flag? 

Here's my policy from IAM
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeVolumes",
                "ec2:DescribeSnapshots",
                "ec2:CreateTags",
                "ec2:CreateVolume",
                "ec2:CreateSnapshot",
                "ec2:DeleteSnapshot"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:DeleteObject",
                "s3:PutObject",
                "s3:AbortMultipartUpload",
                "s3:ListMultipartUploadParts"
            ],
            "Resource": [
                "arn:aws:s3:::test-cluster-velero-backups.s3.amazonaws.com/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::test-cluster-velero-backups.s3.amazonaws.com"
            ]
        }
    ]
}
```

Here is my credentials file (double checked for validity)
```
[default]
aws_access_key_id=<REDACTED>
aws_secret_access_key=<REDACTED>
```

Install command 
```
	velero install \
    --provider aws \
    --bucket test-cluster-velero-backups \
    --secret-file ./velero-credentials \
    --backup-location-config region=${AWS_REGION} \
    --snapshot-location-config region=${AWS_REGION} \
```

**Comment by skriss** [comment]
Is `test-cluster-velero-backups.s3.amazonaws.com` valid syntax for specifying a bucket as a resource in IAM? I think you may want this to just be `test-cluster-velero-backups`.

**Comment by VihanAgarwal97** [comment]
Ahh!! Thank you, that fixed it. The issue was with my terraform!

**Comment by gkdba87** [comment]
@skriss it is possible to take backup of pv and pvc without restic. could you please guide me.

**Comment by skriss** [comment]
Closing as inactive; the feature request to add flags to `velero install` has been noted in #94.
