### ISSUE TITLE
Consider adding a flag to `velero install` to disable volume snapshots

### ISSUE THREAD

**Issue by skriss** [heptio/velero#1453]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Add a flag, e.g. `--use-volume-snapshots`, that's `true` by default, that if false, doesn't create any `VolumeSnapshotLocations`.  This would be useful for our quick-start, where we make the user delete the VSL after setup, or for any other users who don't want to use snapshots.

cc @nrb

**Comment by nrb** [comment]
What are your thoughts on how this interacts with the `--use-restic` flag?  Would it make sense to use that flag and not create a VSL if it's set? I actually don't think so, as it's possible users would want native snapshots for some data and restic for others.

**Comment by skriss** [comment]
Yeah, I think it's probably independent, that way they can have no snapshots/no restic, have either snapshots or restic, or have both.  Not sure what the most clear name for this new flag is -- `--use-snapshots`, `--use-native-snapshots`, etc.

**Comment by nrb** [comment]
I was thinking `--create-snapshot-location`, as that's what's being controlled, but I don't know that it maps to intention well or not.

I've got working code, but the name is the sticking point now.
