### ISSUE TITLE
Create a command to easily select volumes to back up with restic

### ISSUE THREAD

**Issue by nrb** [heptio/velero#1460]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]

Right now, users must use `kubectl annotate` to annotate pods (or `kubectl edit` for Deployments/DaemonSets/StatefulSets) to select volumes to be backed up by restic.

A command that adds the annotation to the appropriate place for the user would be helpful. As an an example:

```bash
# select only vol1 and vol2 on a pod
velero restic select pod/podname vol1,vol2

# add all volumes on a pod to the annotation
velero restic select pod/podname --all-volumes

# add the annotation to a deployment's pod template spec
velero restic select deploy/deployname --all-volumes
```

`velero restic select` was chosen here to hide the implementation detail, in case volume selection is changed from the annotation to some other way of specification.

**Comment by skriss** [comment]
@nrb I think this is probably a dupe of https://github.com/heptio/velero/issues/605?

**Comment by nrb** [comment]
Ah, yes. Closing.
