### ISSUE TITLE
Endless CrashLoopBackoff in helper.go:153

### ISSUE THREAD

**Issue by timfpark** [heptio/velero#1463]
**What steps did you take and what happened:**

Set up and ran Velero over the course of a week.

**What did you expect to happen:**

Velero consistently worked over a long lifecycle.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`

kubectl logs velero-5f5cc8bcd7-ww95d -n velero
time="2019-05-08T22:31:58Z" level=info msg="setting log-level to INFO"
time="2019-05-08T22:31:58Z" level=info msg="Starting Velero server v1.0.0-alpha.1 (39bab5ada91f1ed6fc03006a9f1d73dd356b28a5)" logSource="pkg/cmd/server/server.go:165"
time="2019-05-08T22:31:58Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
time="2019-05-08T22:31:58Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pv
time="2019-05-08T22:31:58Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/serviceaccount
time="2019-05-08T22:31:58Z" level=info msg="registering plugin" command=/velero kind=VolumeSnapshotter logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/aws
time="2019-05-08T22:31:58Z" level=info msg="registering plugin" command=/velero kind=VolumeSnapshotter logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/azure
time="2019-05-08T22:31:58Z" level=info msg="registering plugin" command=/velero kind=VolumeSnapshotter logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/gcp
time="2019-05-08T22:31:58Z" level=info msg="registering plugin" command=/velero kind=ObjectStore logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/aws
time="2019-05-08T22:31:58Z" level=info msg="registering plugin" command=/velero kind=ObjectStore logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/azure
time="2019-05-08T22:31:58Z" level=info msg="registering plugin" command=/velero kind=ObjectStore logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/gcp
time="2019-05-08T22:31:58Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/addPVCFromPod
time="2019-05-08T22:31:58Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/addPVFromPVC
time="2019-05-08T22:31:58Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/job
time="2019-05-08T22:31:58Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
time="2019-05-08T22:31:58Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/restic
time="2019-05-08T22:31:58Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service
time="2019-05-08T22:31:58Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/serviceaccount
time="2019-05-08T22:31:58Z" level=info msg="Checking existence of namespace" logSource="pkg/cmd/server/server.go:355" namespace=velero
time="2019-05-08T22:31:58Z" level=info msg="Namespace exists" logSource="pkg/cmd/server/server.go:361" namespace=velero
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0xd8 pc=0x10a045c]

goroutine 1 [running]:
github.com/heptio/velero/pkg/discovery.refreshServerPreferredResources(0x7ff221c403c0, 0xc000460c60, 0x0, 0x0, 0xc000460c60, 0x0, 0x0, 0xc000046570, 0xc000046500)
	/go/src/github.com/heptio/velero/pkg/discovery/helper.go:153 +0x11c
github.com/heptio/velero/pkg/discovery.(*helper).Refresh(0xc00062ba00, 0x0, 0x0)
	/go/src/github.com/heptio/velero/pkg/discovery/helper.go:114 +0x38d
github.com/heptio/velero/pkg/discovery.NewHelper(0x2344040, 0xc000460c60, 0x2366260, 0xc0000a8500, 0x0, 0x0, 0xc00060da88, 0xc00060da90)
	/go/src/github.com/heptio/velero/pkg/discovery/helper.go:76 +0x5e
github.com/heptio/velero/pkg/cmd/server.(*server).initDiscoveryHelper(0xc0004b9040, 0xc0000530f8, 0x6)
	/go/src/github.com/heptio/velero/pkg/cmd/server/server.go:368 +0x54
github.com/heptio/velero/pkg/cmd/server.(*server).run(0xc0004b9040, 0x0, 0x0)
	/go/src/github.com/heptio/velero/pkg/cmd/server/server.go:324 +0xf8
github.com/heptio/velero/pkg/cmd/server.NewCommand.func1(0xc000341900, 0x36e7f28, 0x0, 0x0)
	/go/src/github.com/heptio/velero/pkg/cmd/server/server.go:188 +0x5b0
github.com/heptio/velero/vendor/github.com/spf13/cobra.(*Command).execute(0xc000341900, 0x36e7f28, 0x0, 0x0, 0xc000341900, 0x36e7f28)
	/go/src/github.com/heptio/velero/vendor/github.com/spf13/cobra/command.go:766 +0x2ae
github.com/heptio/velero/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc000430780, 0x6, 0xc000430780, 0x6)
	/go/src/github.com/heptio/velero/vendor/github.com/spf13/cobra/command.go:852 +0x2ec
github.com/heptio/velero/vendor/github.com/spf13/cobra.(*Command).Execute(...)
	/go/src/github.com/heptio/velero/vendor/github.com/spf13/cobra/command.go:800
main.main()
	/go/src/github.com/heptio/velero/cmd/velero/main.go:34 +0x8a

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): 

Starting Velero server v1.0.0-alpha.1

- Kubernetes version (use `kubectl version`):

1.13.5

- Kubernetes installer & version:

Azure AKS

- Cloud provider or hardware configuration:

Azure AKS 

- OS (e.g. from `/etc/os-release`):

Ubuntu

**Comment by skriss** [comment]
I believe you're hitting the issue that we fixed in https://github.com/heptio/velero/pull/1399, try upgrading to `v1.0.0-beta.1` :)

**Comment by skriss** [comment]
Closing as I'm pretty sure we've resolved this, but feel free to reopen if you still have issues with a newer version.
