### ISSUE TITLE
No config/common/00-prereqs.yaml

### ISSUE THREAD

**Issue by FranzAndreas** [heptio/velero#1471]
**What steps did you take and what happened:**
When installing Velero and following the install doc there should be an config/common/00-prereqs.yaml in the repository, but this is not the case.

**Comment by skriss** [comment]
@franzandreas if you're installing v1.0.0-rc.1, please make sure you're using the matching docs using the version drop down on the docs website. We are now using the velero install command rather than static YAML.

**Comment by skriss** [comment]
Closing as this is as designed. Feel free to reopen if you need further assistance!
