### ISSUE TITLE
Add support for ppc64le (power architecture)

### ISSUE THREAD

**Issue by prajyotparab** [heptio/velero#1493]
**Describe the solution you'd like**

- Get Velero to work on power machines, by adding support for ppc64le.

**Anything else you would like to add:**

- I did build Velero binary and Velero image from source on power architecture and it worked as expected. 

**Environment:**

- Velero version (use `velero version`): v0.11.0
- Kubernetes version (use `kubectl version`): v1.12.4
- Kubernetes installer & version: ICP 3.1.2
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`): Ubuntu 16.04

**Comment by Prajyot-Parab** [comment]
PR: https://github.com/heptio/velero/pull/1605
