### ISSUE TITLE
velero-policy.json has an extra space in front of every line causing parsing error

### ISSUE THREAD

**Issue by ali5ter** [heptio/velero#1494]
**What steps did you take and what happened:**
Following instructions to add AWS IAM policies to velero user, using
aws iam put-user-policy \
   --user-name velero \
   --policy-name velero \
   --policy-document file://velero-policy.json

**What did you expect to happen:**
Expected successful response given the instructions

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

"An error occurred (MalformedPolicyDocument) when calling the PutUserPolicy operation: The policy failed legacy parsing"

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

The velero-policy.json described in the v1.0.0 documentation has an extra space in front of every line, so AWS service fails to parse the json and the policy is not applied.

**Environment:**

- Velero version (use `velero version`): v1.0.0-rc.1
- Kubernetes version (use `kubectl version`): v1.14.1
- Kubernetes installer & version:
- Cloud provider or hardware configuration: VMware CloudPKS
- OS (e.g. from `/etc/os-release`): MacOS 10.14.4

**Comment by skriss** [comment]
@ali5ter I think this is just how the markdown gets rendered -- looks like every code block has an extra space in front of each line. Will check with the designers to see if there's anything we can do here.

**Comment by jonasrosland** [comment]
Looking into this, thanks @ali5ter for reporting this bug.
