### ISSUE TITLE
Prometheus monitoring 

### ISSUE THREAD

**Issue by vitobotta** [heptio/velero#1500]
Hi! This isn't really a bug but I didn't know what to choose. I've read some mentions here in the issues about Prometheus integration so that metrics can be used to monitor backup jobs. However I can't find any documentation anywhere on how to actually do this. What I'm trying to do is find a way to receive alerts when backup jobs are completed so that I can know if a backup was successful or not. Can anyone point me to some resource on how to do this with either Prometheus or something else? Thanks a lot in advance.

**Comment by sebastien-prudhomme** [comment]
You can use hooks to do that but i don't know if it is easy to get the backup result: https://velero.io/docs/v1.0.0/hooks/

At my work, we're working on the backup strategy for our new Kubernetes cluster and you're going to use Velero and Argo project (https://github.com/argoproj/argo) to manage backups.

With Argo we will be able to build from simple to complex backup, and restore, workflows.

In the Argo workflow we will have a step which simply launches the ```velero backup``` command with the ```--wait``` option and other steps can react to the result of this step, for instance launching a notification alert when there is a problem.

**Comment by skriss** [comment]
@vitobotta do you need anything further here? This doesn't seem like a bug or feature request.

**Comment by skriss** [comment]
Per previous comment, I'm closing this issue as it no longer seems active, however feel free to reopen/open additional issues as needed, thanks.
