### ISSUE TITLE
Blog author link is broken

### ISSUE THREAD

**Issue by carlisia** [heptio/velero#1522]
![image](https://user-images.githubusercontent.com/16508/58372506-ffb82180-7ed2-11e9-9690-1d86861fabd3.png)

Clicking on the name of the author gives a 404.

**Comment by coonsd** [comment]
I added the author as a tag on the blog post, which should fix the 404 error.  I forgot to do the sign-off on my first pull request, so I closed it and resubmitted it with it correctly included.

**Comment by skriss** [comment]
@carlisia @coonsd is this issue now resolved? If so, please close this issue (and thanks @coonsd for the PR!)

**Comment by carlisia** [comment]
Ah there wasn't a reference. Closing. Fixed by: https://github.com/heptio/velero/pull/1550

**Comment by skriss** [comment]
OK, closing.
