### ISSUE TITLE
Website should have a "Contact us" page

### ISSUE THREAD

**Issue by carlisia** [heptio/velero#1523]
There is no clear way to find how to get in touch with the team. The (tiny) links at the bottom are good, but there could be a menu item "Contact us" that leads to a page explicitly listing all forms of contact.

This page could also have the schedule of our community meetings.

**Comment by jonasrosland** [comment]
Do you think rewriting the information at https://velero.io/community/ would work? If anyone wants to chat with the team, they could go to the #velero channel on the K8s Slack, for instance.

**Comment by carlisia** [comment]
Ah. How did I miss this page.

Yes, that's fine.

I would add the links to the meetings on that page, instead of making ppl go to another website to find community meeting info.

I'd add the link to the zenhub board there too.
