### ISSUE TITLE
Velero is Restic restore  in another cluster

### ISSUE THREAD

**Issue by estefancaique** [heptio/velero#1524]
It is possible to restore the cluster data to another using restic

**Environment:**

- Velero version (use `velero version`): v.1.0.0

**Comment by skriss** [comment]
Yes, it is possible. This document partly describes the procedure: https://velero.io/docs/v1.0.0/migration-case/

Note that you'll also need to have a storage class in Cluster B with the same name as the storage class in cluster A.

**Comment by skriss** [comment]
Closing issue but feel free to reopen as needed.
