### ISSUE TITLE
add alibabacloud provider support

### ISSUE THREAD

**Issue by haoshuwei** [heptio/velero#1525]
**Describe the solution you'd like**

Currently the velero does not support back up and restore kubernetes cluster resources and persistent volumes on alibaba cloud. This can be supported by adding a alibabacloud provider.

**Anything else you would like to add:**

A new provider will be added and the vendor files would have to be updated.

**Comment by carlisia** [comment]
Thanks for opening this issue @haoshuwei. For now I'll be closing the original PR. Please follow the directions below to add an alibaba plugin for Velero:

https://velero.io/docs/v1.0.0/plugins/

**Comment by haoshuwei** [comment]
> Thanks for opening this issue @haoshuwei. For now I'll be closing the original PR. Please follow the directions below to add an alibaba plugin for Velero:
> 
> https://velero.io/docs/v1.0.0/plugins/

ok, thanks a lot

**Comment by skriss** [comment]
@haoshuwei definitely reach out if you need any input getting the plugin created / published - we're excited to have it and to link to it from https://velero.io/docs/v1.0.0/support-matrix/.

**Comment by carlisia** [comment]
@haoshuwei is there anything we can help you with?

Also, as an FYI, all of the Velero plugins will live outside of tree, please see: https://github.com/heptio/velero/issues/1537

**Comment by haoshuwei** [comment]
@carlisia @skriss  thanks a lot for your comments, I have published the velero plugin for alibabacloud. Another issue is opened to add a link to [https://github.com/heptio/velero/blob/master/site/docs/master/support-matrix.md](https://github.com/heptio/velero/blob/master/site/docs/master/support-matrix.md)

please see: [#1542](https://github.com/heptio/velero/issues/1542)
