### ISSUE TITLE
Remove the server cmd from the velero/restic CLI

### ISSUE THREAD

**Issue by carlisia** [heptio/velero#1527]
![image](https://user-images.githubusercontent.com/16508/58507894-a4db3000-8147-11e9-8d54-eb8c5aa003b2.png)

The `velero restic server` has no utility for the Velero CLI user. While it doesn't need to be removed from the list of commands, it should be removed from the help text so users don't think there is use for it.

Update: also remove `velero server`, for the same reason.

**Comment by ffahri** [comment]
Hey, i created pr for this issue https://github.com/heptio/velero/pull/1529

**Comment by skriss** [comment]
If we're doing this, we may as well remove `velero server` from the list of visible commands as well.

**Comment by carlisia** [comment]
Good point. Updated the description.

**Comment by skriss** [comment]
This requires setting the `Hidden` attribute on the relevant cobra command, like https://github.com/heptio/velero/blob/master/pkg/cmd/server/plugin/plugin.go#L37.
