### ISSUE TITLE
Report Status Backups for Slack or anothers

### ISSUE THREAD

**Issue by estefancaique** [heptio/velero#1528]
The velero  has some plugin or featured that send backup statuses via slack or email.

Thanks.

**Comment by skriss** [comment]
@estefancaique while I can definitely see this having value, I don't think it's something we'll be building into the core Velero codebase. Given that Velero is CRD-based, it's possible for someone to develop an integration that watches the status of the Velero API objects and sends statuses to slack/email or takes some other action, without needing to be part of Velero itself.  See #1500 for another user's approach to this.  We also have #1150 logged for adding generic pre/post backup/restore plugins.  With that in mind, closing this issue.
