### ISSUE TITLE
Template IAM policy doesn't allow required s3 perms.

### ISSUE THREAD

**Issue by gurpalw** [heptio/velero#1544]
**What steps did you take and what happened:**
I created a velero IAM user as per the instructions in the doc and copied and pasted the policy from the same doc, replacing it with my own bucket name.

Here is the doc i am referring to: https://velero.io/docs/v1.0.0/aws-config/

Created a secret as per helm instructions.

Pod starts but fails with this error:
_"time="2019-06-05T11:11:38Z" level=info msg="Checking that all backup storage locations are valid" logSource="pkg/cmd/server/server.go:431"
**An error occurred: some backup storage locations are invalid: backup store for location "default" is invalid: rpc error: code = Unknown desc = AccessDenied: Access Denied
	status code: 403, request id: 70BAB74B37C444FF, host id:** /5Ph9iz66oS1jf931Eos8WpagErcMYfO04xFFFtYkB6JpDYn9yFgRwoDD8SYn9QXvuRxVTVF4UA="_

**What did you expect to happen:**
Expected the pod to start without errors and have access to the bucket.

**Anything else you would like to add:**
Changing the actions in the iam policy document to " "Action": [
                "s3:*"
            ],"

fixes the issue but obviously isn't ideal.

**Environment:**

- Velero version (use `velero version`): 1.0.0
- Kubernetes version (use `kubectl version`): v1.12.1
- Cloud provider or hardware configuration: AWS

**Comment by skriss** [comment]
I'd be interested to see the exact IAM policy that didn't work -- as far as I know the policy in the docs has worked in our testing.

**Comment by skriss** [comment]
@gurpalw following up here - could you paste the exact policy that you had in IAM that didn't work?

**Comment by skriss** [comment]
@gurpalw if you can provide the verbatim policy that didn't work, that'd be helpful. Otherwise, AFAIK the policy in the docs works fine (Joe Beda used it in TGIK last Friday). Closing this issue for now, pending more detail on what didn't work.

**Comment by IuriGarcia** [comment]
Im facing the same Issue. Im trying to install stable/velero since once i have tried to install vmware-tanzu/velero just gotten that error
`Error: YAML parse error on velero/templates/volumesnapshotlocation.yaml: error converting YAML to JSON: yaml: line 14: could not find expected ':'`

So, just tryed to install stable/velero using the same procedure, reading Readme(v2.7.4), basing on the helm install command line to make alterations to my values.yaml.

Once i did have installed velero, just got the same errors as @gurpalw . So, the policy that i am using is the one specified in the prerequisities [here](https://github.com/vmware-tanzu/velero-plugin-for-aws#Install-and-start-Velero).

So, after doing all of that setup, just tried to install using stable/velero and here i am :(

**Comment by skriss** [comment]
@luriGarcia I've used that AWS policy many times, in fact am using it right now, and it's working fine, so I'm not sure why you're getting the error.

To start, could you paste the output of `aws iam get-user-policy --user-name velero --policy-name velero`? You can redact the bucket name if you need.

**Comment by saicharana731** [comment]
@skriss  I am getting the same error and my output of the above cmd is :
PolicyDocument:
  Statement:
  - Action:
    - ec2:DescribeVolumes
    - ec2:DescribeSnapshots
    - ec2:CreateTags
    - ec2:CreateVolume
    - ec2:CreateSnapshot
    - ec2:DeleteSnapshot
    Effect: Allow
    Resource: '*'
  - Action:
    - s3:GetObject
    - s3:DeleteObject
    - s3:PutObject
    - s3:AbortMultipartUpload
    - s3:ListMultipartUploadParts
    Effect: Allow
    Resource:
    - arn:aws:s3:::velerobackup/*
  - Action:
    - s3:ListBucket
    Effect: Allow
    Resource:
    - arn:aws:s3:::velerobackup
  Version: '2012-10-17'
PolicyName: velero
UserName: velero

**Comment by VihanAgarwal97** [comment]
I am also seeing this with the IAM Policy @saicharana731 posted.

**Comment by VihanAgarwal97** [comment]
Update: The below policy works.  
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeVolumes",
                "ec2:DescribeSnapshots",
                "ec2:CreateTags",
                "ec2:CreateVolume",
                "ec2:CreateSnapshot",
                "ec2:DeleteSnapshot"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:DeleteObject",
                "s3:PutObject",
                "s3:AbortMultipartUpload",
                "s3:ListMultipartUploadParts"
            ],
            "Resource": [
                "arn:aws:s3:::<bucket>/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::<bucket>"
            ]
        }
    ]
}
```
The issue might be related to using a prefix?

**Comment by VihanAgarwal97** [comment]
I installed velero using 
```
	velero install \
	--provider aws \
	--plugins velero/velero-plugin-for-aws:v1.0.1 \
	--bucket ${VELERO_BUCKET} \
	--prefix ${VELERO_PREFIX} \
	--secret-file ./credentials-velero \
	--pod-annotations cluster-autoscaler.kubernetes.io/safe-to-evict=true \
	--backup-location-config region=${AWS_REGION} \
	--snapshot-location-config region=${AWS_REGION} \
	--velero-pod-mem-limit "512Mi" \
	--velero-pod-mem-request "256Mi"
```

**Comment by VihanAgarwal97** [comment]
Tried using the 1.1.0 plugin too. Same issue. 
```
> velero version --client-only
Client:
	Version: v1.4.2
	Git commit: -

```
I have also verified in the IAM console that the credentials are being pulled.

**Comment by ashish-amarnath** [comment]
@VihanAgarwal97 I am using the exact same policy that you mention in [your comment](https://github.com/vmware-tanzu/velero/issues/1544#issuecomment-681881909) without issues.
In the same comment, you mention that the policy works for you. I am not sure if you are still having the same issue.

As I mentioned, the exact same policy works for me. Can you please confirm:
1. Correct credentials are being passed to Velero in the `./credentials-velero` file
1. Contents of the ./credentials-velero` file are formatted correctly like aws-credentials. Like
    ```
    [default]
    aws_access_key_id=AKIAIOSFODNN7EXAMPLE
    aws_secret_access_key=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    ```
    https://docs.aws.amazon.com/cli/latest/userguide/cli-configure-files.html
1. Confirm that the contents of the `cloud-credentials` secret and `./credentials-velero` file are exactly the same.
    You can view the contents of the secret using 
    ```
    $ kubectl -n velero get secrets cloud-credentials -ojson | jq .data.cloud -r | base64 --decode
    ```

**Comment by VihanAgarwal97** [comment]
I have verified all your steps. I have also verified through IAM that the access key has been used each time I deploy velero.

The policy from the docs works, however, I am unable to use the same policy and get velero to work when using a `bucket prefix`. My first [comment](https://github.com/vmware-tanzu/velero/issues/1544#issuecomment-681870148) is the policy I thought would work but doesn't. Ive edited that same policy to be similar to one that works , but it doesn't when we have that additional "prefix". I've updated my comments to hopefully clarify.

**Comment by VihanAgarwal97** [comment]
@ashish-amarnath Are you using an S3 bucket `prefix`? If so, can you share your policy with me please?

**Comment by ashish-amarnath** [comment]
@VihanAgarwal97 Yes, this is where my backups go `ashisha-velero-backup/velero-backup` the bucket is `ashisha-velero-backup` and the prefix is `velero-backup`
I am using exactly the same policy as you are. I copy-pasted from your comment into my policy document.
```json
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ec2:DescribeVolumes",
                "ec2:DescribeSnapshots",
                "ec2:CreateTags",
                "ec2:CreateVolume",
                "ec2:CreateSnapshot",
                "ec2:DeleteSnapshot"
            ],
            "Resource": "*"
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:GetObject",
                "s3:DeleteObject",
                "s3:PutObject",
                "s3:AbortMultipartUpload",
                "s3:ListMultipartUploadParts"
            ],
            "Resource": [
                "arn:aws:s3:::ashisha-velero-backup/*"
            ]
        },
        {
            "Effect": "Allow",
            "Action": [
                "s3:ListBucket"
            ],
            "Resource": [
                "arn:aws:s3:::ashisha-velero-backup"
            ]
        }
    ]
}
```

**Comment by VihanAgarwal97** [comment]
How are you installing velero? What version are you using?

**Comment by ashish-amarnath** [comment]
I've used `1.4.2`

**Comment by VihanAgarwal97** [comment]
I'm doing exactly this with a different `velero install`. Only difference is I'm not using restic.

**Comment by ashish-amarnath** [comment]
@VihanAgarwal97 I am unable to troubleshoot this further. The last couple of things I would try is:
1. Confirm the credentials are correct.
2. Confirm that the IAM user has permission to access this bucket. Suggest creating a new IAM user to try this out from scratch.

**Comment by VihanAgarwal97** [comment]
Verified. I am still facing the same issue.
