### ISSUE TITLE
Backing up private openshift cluster in Azure

### ISSUE THREAD

**Issue by tvaradan** [heptio/velero#1554]
Hi - This is related to issue #841 (https://github.com/heptio/velero/issues/841).  I too have a private openshift cluster running on on-prem Datacenter nodes. Can I still take a back-up of this and store it in Azure? Ours is behind a firewall and not open to internet. We have a proxy to reach the outside world. Where do I provide the proxy details in Velero-Ark in order to back up my cluster in Azure?

Thanks!

**Comment by tvaradan** [comment]
I was able to get the tar backup of my Dat Cluster onto Azure. So this can be closed.

**Comment by tvaradan** [comment]
I was able to get the tar backup of my Dat Cluster onto Azure. So this can be closed. Just had to enable proxy in the velero pod.

**Comment by skriss** [comment]
@tvaradan glad you got this sorted out. It would be helpful if you could add some details here about exactly what you had to do to get this working, for future reference :)

**Comment by tvaradan** [comment]
Hi - As stated earlier, I just had to apply proxy in the env variables section in the pod yaml and restarted the pod to trigger DAT openshift velero backup and the backup location was in Azure. Hope this clarifies. Let know if any further questions.

Thx,
Varadh

________________________________
