### ISSUE TITLE
Disable volume snapshotting plugin for CSI volumes

### ISSUE THREAD

**Issue by nrb** [heptio/velero#1567]
When a volume is snapshotted using CSI, Velero should not try to execute it's own volume snapshot plugins.

This could be accomplished a variety of ways, but I'm quite sure which is the best yet.

Some ideas:

* disable the volume snapshot plugin via a `velero plugin remove` command. 
* add a configmap that the volume snapshot plugins check before running (requires opt-in by the plugin authors)
* change in-tree velero logic to detect CSI support on a volume (not ideal, but doable)
* Add a field to VolumeSnapshotLocations flagging them as a CSI location (VSLs actually don't get used with the current CSI plugin code, however)
* Add a field on the Backup object as to whether CSI or the volume snapshot plugin should be used
* Annotate pods, similar to restic. Requires in-tree changes to use the annotation. however.

**Comment by skriss** [comment]
I **believe** that the current volume snapshotters will already ignore CSI PVs -- for EBS, for example, the snapshotter looks for the `spec.awsElasticBlockStore.volumeID` field to determine if the PV is a supported one -- which won't exist for a CSI-provisioned EBS volume.  When no volume snapshotter is found that supports the CSI PV, "normal" snapshotting will just be skipped.

**Comment by nrb** [comment]
So far, I’m getting PartiallyFailed backups in my cluster, despite CSI snapshots happening. The errors are coming from the volume snapshotter plugin.

I’ll double check things; perhaps removing the VSL will be enough for now and this can be moved from the prototype.

**Comment by nrb** [comment]
Deleting the VSL is enough to skip any Velero provider plugins, so I'll move this out of v1.1

**Comment by nrb** [comment]
Closing this out, as in researching for the proposal, we can detect if a `PersistentVolume` is backed by a CSI driver. The existing volume snapshotters will indeed ignore them for the reasons Steve stated before.
