### ISSUE TITLE
Full blog posts show excerpt separator

### ISSUE THREAD

**Issue by seemonicago** [heptio/velero#1575]
When viewing a full blog post, the text '' is visible.

Example: https://velero.io/velero-is-an-open-source-tool-to-back-up-and-migrate-kubernetes-clusters/

The text '' should not be visible. This text is used to identify the end of a post excerpt shown in the blog-post-cards page. 

https://github.com/heptio/velero/blob/master/site/_includes/blog-post-card.html

velero version 1.0

**Comment by carlisia** [comment]
![image](https://user-images.githubusercontent.com/16508/59372914-64f67a00-8cfd-11e9-9cdc-4c40993992b2.png)

**Comment by skriss** [comment]
Closed by #1578
