### ISSUE TITLE
Refactor pkg/restore to match pkg/backup structure

### ISSUE THREAD

**Issue by ncdc** [heptio/velero#158]

**Comment by rosskukulinski** [comment]
@ncdc this wasn't on your 1.0 punchlist. Essential tech-debt paydown?  Good first issue for a new developer?

**Comment by ncdc** [comment]
I want to clean up pkg/restore. It's not strictly required for 1.0 as it's
all internal stuff. It would not be a good first issue.

**Comment by skriss** [comment]
Thanks for this request. We are not currently prioritizing this item within our roadmap, and as such will be closing out the issue. Please feel free to reach out as needed in this issue or a new one.
