### ISSUE TITLE
failure of volumes --snapshot-volumes0

### ISSUE THREAD

**Issue by gkdba87** [heptio/velero#1590]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

**What did you expect to happen:**

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
* `velero backup logs <backupname>`
* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
* `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by gkdba87** [comment]
We are trying to take backup of namespace in k8 cluster. For that we have using velero(--restic). .
but  did not get chance to take pod volumes.
Any one please look into this.
**command**:  velero backup create bkp4 --include-namespaces cicd-dev --snapshot-volumes
OutPut: 

  
![image](https://user-images.githubusercontent.com/22393158/59707976-67873100-9221-11e9-8b3f-bba8f7c6183a.png)

and restic DeamonSet :

NAME      DESIRED   CURRENT   READY     UP-TO-DATE   AVAILABLE   NODE SELECTOR                   AGE
restic    0         0         0         0            0           beta.kubernetes.io/arch=amd64   26m
root@cdldvawxvat0001:/home/venugva>

**Comment by skriss** [comment]
What object storage system are you using? Can you also provide the output of `velero restic repo get -o yaml`?

**Comment by gkdba87** [comment]
@skriss , i have used IBM S3 Object storage.
Output of restic repo :

![image](https://user-images.githubusercontent.com/22393158/59733049-2ff0a700-926a-11e9-8b5f-8f2ecae24703.png)

**Comment by skriss** [comment]
oh, it looks like there are no pods for the restic daemonset...do you have any node taints that are preventing pods from being scheduled on each node?

**Comment by gkdba87** [comment]
No , i didn't taint any nodes. My K8 cluster have different types of node flavors like suse-linux-nodes and IBM-Z-linux nodes.  so that  I have  use Node-selector to  spin the pods in Suse-linux .

**Comment by gkdba87** [comment]
@skriss No , i didn't taint any nodes. My K8 cluster have different types of node flavors like suse-linux-nodes and IBM-Z-linux nodes. so that I have use Node-selector to spin the pods in Suse-linux .

**Comment by skriss** [comment]
OK - well the restic daemonset currently is not running any pods, so I'd look at why that's the case.

**Comment by skriss** [comment]
@gkdba87 did you need anything further here?

**Comment by skriss** [comment]
Closing as inactive, reopen as needed!
