### ISSUE TITLE
 Restore namespace backup in another (new) namespace

### ISSUE THREAD

**Issue by frederiksf** [heptio/velero#1592]
**Describe the solution you'd like**
[A clear and concise description of what you want to happen.]
i would like to restore namespace backup in another (new) namespace. Is this scenario possible? And how can i tweak the restore config before actual restore it?

**Environment:**

- Velero version (use `velero version`):
ark version
Version: v0.10.0
Git commit: v0.10.0
Git tree state: clean
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.2", GitCommit:"17c77c7898218073f14c8d573582e8d2313dc740", GitTreeState:"clean", BuildDate:"2018-10-24T06:54:59Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.6-eks-d69f1b", GitCommit:"d69f1bf3669bf00b7f4a758e978e0e7a1e3a68f7", GitTreeState:"clean", BuildDate:"2019-02-28T20:26:10Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes installer & version:
EKS
- Cloud provider or hardware configuration:
AWS
- OS (e.g. from `/etc/os-release`):
EKS NODE

**Comment by skriss** [comment]
You'll want to do something along these lines:

```
velero restore create  --from-backup BACKUP_NAME --namespace-mappings OLD_NS:NEW_NS
```

One caveat is that if you're trying to create a second copy of `OLD_NS` in the same cluster, and that namespace uses persistent volumes, Velero is currently unable to create a second copy of that persistent volume (see #192)

**Comment by skriss** [comment]
I'm going to close this issue, but feel free to reopen/open another if you have further issues.

**Comment by roshithrajan** [comment]
Hi 
Even i faced same error with velero:v1.8.1 when i tried to restore it in new name space the pods is not creating in new name space , orginal POD has PV s
velero restore create wpns1 --from-backup dailyfullbackup-20230404133620 --namespace-mappings wpns:wpns1
