### ISSUE TITLE
Could Not Recover the PVC data 

### ISSUE THREAD

**Issue by kannanvr** [heptio/velero#1596]
Hi,
  I am new to velero. Also, I understood that we can take the backup of Cluster resources and the PVC data(using restic). 
 I have created the Secure docker Registry PVC and daemonset. I have pushed the data to secure docker registry PVC. 
For the testing purpose, i have removed the secure docker registry all the resources including PVC.
Then I am trying to recover the cluster resources of secure docker registry.

I am able to recover secure docker registry daemonset and PVC. But I could not recover the data stored within PVC. I am using Glusterfs storage to create the PVC.

I have used following command to install,backup and restore from velero 

-------------------

velero install     --provider aws     --bucket velero     --secret-file ./credentials-velero      --backup-location-config region=us-east-1,s3ForcePathStyle="false",s3Url=http://10.7.9.7:32277 --use-restic

velero backup create secure-registry --selector app=secure-docker-registry

velero restore create --from-backup secure-registry

------------

If it is possible to recover the PVC data from velero, kindly help us to know the way for recovering the PVC data....

**Comment by skriss** [comment]
Did you follow the instructions here - https://velero.io/docs/v1.0.0/restic/ - specifically, did you annotate your workload pod with the `backup.velero.io/backup-volumes=YOUR_VOLUME_NAME_1,YOUR_VOLUME_NAME_2,...` annotation?

If so, then please attach the backup & restore logs (`velero backup logs NAME` and `velero restore logs NAME`) for further troubleshooting.

**Comment by kannanvj** [comment]
Its working fine... Please close this issue... 
Thanks for your support

**Comment by skriss** [comment]
OK great! closing.
