### ISSUE TITLE
Adding --yes confirmation flag for velero commands

### ISSUE THREAD

**Issue by Aracki** [heptio/velero#1613]
Have you though about adding this for create/delete commands?

eg. 
* `velero backup create` would just output how the backup will be created (prints that `--snapshot-volumes` is set to `true` and other important stuff that may cause backup to last longer or do some unwanted actions) - something like 'dry-run'.

* Adding `--yes` to the command would actually execute it.

I think this practice would increase the caution about sensitive commands. <br>It is used in `kops` and `terraform` as well.

**Comment by nrb** [comment]
We do have `--confirm` for delete commands, but not for creation. I can appreciate the concern, though I'm reticent to change this behavior at this stage because it's changing our primary interface for users. If we did make such a change, it would be a major release such as 2.0.

**Comment by Aracki** [comment]
Seems reasonable 👍
