### ISSUE TITLE
Velero install failed (pls close)

### ISSUE THREAD

**Issue by Berndinox** [heptio/velero#1618]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.
Install as explaint in docs

time="2019-07-02T16:04:48Z" level=info msg="Checking that all backup storage locations are valid" logSource="pkg/cmd/server/server.go:431"
An error occurred: some backup storage locations are invalid: backup store for location "default" is invalid: rpc error: code = Unknown desc = NoSuchKey: 
	status code: 404, request id: tx000000000000007c1c769-005d1b80a0-1b7a15-fra1a, host id:

**Comment by nrb** [comment]
The `NoSuchKey` description and 404 look to me like the bucket doesn't exist. `velero install` does not create a bucket for you, it must be made manually.

**Comment by skriss** [comment]
One other possibility - are you hitting [this](https://github.com/heptio/velero/issues/1176)? (using `<bucket>/<prefix>` in the `bucket` field)

**Comment by Berndinox** [comment]
Hy, thanks for the fast response.

Installed via: 
`velero install --provider aws --bucket velero --secret-file ./credentials-velero --use-volume-snapshots=false --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=https://myurl.fra1.digitaloceanspaces.com`

my credentials-files:
[default]
aws_access_key_id = 123456
aws_secret_access_key = 78910

Inside my DO Space i've created the folder "velero"
