### ISSUE TITLE
Typo: velero.exe man

### ISSUE THREAD

**Issue by Berndinox** [heptio/velero#1623]
https://github.com/heptio/velero/blob/b3c6e5e483278384f630b89c5a6304887dfd4f52/pkg/cmd/cli/schedule/create.go

`velero create schedule NAME --schedule="@every 1d" --included-namespaces web`

should be:
`velero create schedule NAME --schedule="@every 1d" --include-namespaces web`

It seems like "@every 1d" is also not working and the schedule fails to be created.

BR Bernd

**Comment by skriss** [comment]
Thanks for reporting the typo! Re: the "@every 1d" - yeah, you have to express it in hours, so "@every 24h" should work. I'll get a PR up shortly to fix the docs.

**Comment by Berndinox** [comment]
@skriss "@every 1d" is also not recogniced.

for example, "@weekly" does work

**Comment by skriss** [comment]
Correct, "@every 1d" doesn't work - you need to use hours, e.g. "@every 24h"
