### ISSUE TITLE
Snapshot prefixes

### ISSUE THREAD

**Issue by brondum** [heptio/velero#1627]
**Describe the solution you'd like**
When running Velero in multiple cluster the possibility to prefix snapshots, would create a lot of transparency in the backup storage account.

**Environment:**

- Velero version (use `velero version`):
   1.0.0

- Kubernetes version (use `kubectl version`):
   v1.13.5

- Cloud provider or hardware configuration:
   Azure AKS

**Comment by skriss** [comment]
@brondum can you describe the problem you're trying to solve here? I'm not entirely clear on that. Also, can you add some more detail on what sort of "prefix" you're looking for? 

Also note that we do add labels to PV snapshots with metadata about where they're coming from - does that help at all?

**Comment by brondum** [comment]
@skriss What we were trying to solve was actually to identify the snapshots based on their naming. So if we could prefix them with eg. cluster-name or backup-name or something. 
But i had totally overlooked the fact that you provided a lot of tags! this will do it for us for sure.

Thank you so much the answer :)
