### ISSUE TITLE
Backup only single kubernetes object 

### ISSUE THREAD

**Issue by prasenforu** [heptio/velero#1628]
Not sure it is available or not but want if .. 

we can take a Backup ONLY single kubernetes object [for example kubernetes service (svc)]

**Comment by skriss** [comment]
@prasenforu if you're trying to back up all services, you can do `velero backup create services-only --include-resources services`. Or, you can apply a label to the specific service you want to back up, then do `velero backup create labeled-service-only --include-resources services --selector foo=bar`.

**Comment by prasenforu** [comment]
Service I given as a example.

Basically looking for any type of kubernetes object. Could be PVC or pod or ingress .

Anything

**Comment by skriss** [comment]
You can specify any resource type(s) as the value of `--included-resources`

**Comment by prasenforu** [comment]
Can you give me some examples.

Backup specific resource in particular namespace.

PVC or PV in "ABC" namespace

**Comment by skriss** [comment]
Back up PVCs in the namespace "abc":
`velero backup create foo --include-namespaces abc --include-resources persistentvolumeclaims`

Back up PVCs and services in the namespace "abc":
`velero backup create foo --include-namespaces abc --include-resources persistentvolumeclaims,services`

Back up PVCs in all namespaces:
`velero backup create foo --include-resources persistentvolumeclaims`

**Comment by prasenforu** [comment]
Thanks.

Appreciate your indetail response.

**Comment by cloudcafetech** [comment]
@skriss 
Is there any way I can take backup following cluster resources (crd,clusterrole) ... 

```
[root@sync-cluster setup-files]# oc get clusterrole | grep strimzi
strimzi-cluster-operator-global                                        2020-10-04T12:46:05Z
strimzi-cluster-operator-namespaced                                    2020-10-04T12:46:05Z
strimzi-entity-operator                                                2020-10-04T12:46:05Z
strimzi-kafka-broker                                                   2020-10-04T12:46:05Z
strimzi-topic-operator                                                 2020-10-04T12:46:05Z
[root@sync-cluster setup-files]# oc get crd | grep strimzi
kafkabridges.kafka.strimzi.io         2020-10-04T12:46:03Z
kafkaconnectors.kafka.strimzi.io      2020-10-04T12:46:03Z
kafkaconnects.kafka.strimzi.io        2020-10-04T12:46:03Z
kafkaconnects2is.kafka.strimzi.io     2020-10-04T12:46:03Z
kafkamirrormaker2s.kafka.strimzi.io   2020-10-04T12:46:03Z
kafkamirrormakers.kafka.strimzi.io    2020-10-04T12:46:03Z
kafkarebalances.kafka.strimzi.io      2020-10-04T12:46:03Z
kafkas.kafka.strimzi.io               2020-10-04T12:46:03Z
kafkatopics.kafka.strimzi.io          2020-10-04T12:46:04Z
kafkausers.kafka.strimzi.io           2020-10-04T12:46:04Z
```
