### ISSUE TITLE
Can velero help migrate a k8s cluster with pv/pvc from AWS to Azure?

### ISSUE THREAD

**Issue by shuitingjianle** [heptio/velero#1634]
I am not sure if velero can help migrate a k8s cluster with pv/pvc from AWS to Azure?

**Comment by shuitingjianle** [comment]
@carlisia @skriss

**Comment by skriss** [comment]
Potentially, yes. You can watch a demo of a cross-provider migration using Velero + restic here: https://www.youtube.com/watch?v=q2FCxheA8VI&feature=youtu.be.

The main requirements are:
- use restic to back up your volumes in the AWS cluster
- Azure cluster needs to be configured with access to the BackupStorageLocation used by the AWS cluster (Azure cluster needs both the BSL config *and* credentials)
- Azure cluster needs a storage class whose name matches the storage class uses in the AWS cluster, *or* you need to write a plugin to map storage classes (see #1621 for an in-progress implementation of this)

**Comment by skriss** [comment]
Closing as inactive, let us know if you need anything further!
