### ISSUE TITLE
Clarify docs around environment cloning since in-cluster PV cloning is not currently supported

### ISSUE THREAD

**Issue by arianitu** [heptio/velero#1635]
**What steps did you take and what happened:**
I want to clone an environment (such as dev to staging) and it does not seem to work since the containers never start due to the PVCs using the same disk as the other environment.

**What did you expect to happen:**
I expected the PVCs to somehow be cloned. Instead the PVCs said that the PVs have been bound twice and the containers never start.

**Environment:**
Kubernetes on Google Cloud

- Velero version (use `velero version`): v1.0.0
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.2", GitCommit:"81753b10df112992bf51bbc2c2f85208aad78335", GitTreeState:"clean", BuildDate:"2018-05-12T04:12:47Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.6-gke.13", GitCommit:"fcbc1d20b6bca1936c0317743055ac75aef608ce", GitTreeState:"clean", BuildDate:"2019-06-19T20:50:07Z", GoVersion:"go1.11.5b4", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version:
GKE

- Cloud provider or hardware configuration:
Google Cloud

**Comment by skriss** [comment]
In your setup, does an "environment" correspond to a separate cluster, or a separate namespace?

We don't currently support cloning a PV/PVC within the same cluster -- see #192. If you're trying to clone into a separate cluster, and you're using PV snapshots, then this should work - we can dig in some more.

**Comment by arianitu** [comment]
@skriss It's the same cluster. I think this is a very important feature for dev environments since it's one of Veleros claims in its documentation.

Under Overview (https://github.com/heptio/velero):

- Replicate your production environment for development and testing environments.

I believe this point should be removed since it was one of the points for picking Velero in the first place, but later we find out we can't do that! I think PVCs are used in most environments, so that point doesn't hold.

I'll take a look at https://github.com/heptio/velero/issues/192.

**Comment by skriss** [comment]
@arianitu sorry this was unclear :/ the intent with that bullet was to describe cross-cluster environment cloning, but we can probably clarify.
