### ISSUE TITLE
Velero does not authenticate to multipule clusters when switching contexts

### ISSUE THREAD

**Issue by switchboardOp** [heptio/velero#1637]
**What steps did you take and what happened:**
I installed velero in an on-prem cluster. with backup storage located in Azure.

I have multiple kube contexts in multiple files that are unified with the `KUBECONFIG` environment variable.

Velero does not authenticate to both clusters when switching contexts, but does work when the kubeconfig file is specified.

In `dev` context I can list pods and issue `velero` commands:
```shell
$ [☸ dev:velero] k get pods 
NAME                      READY   STATUS    RESTARTS   AGE
velero-5dd4bbdd9c-dtrsz   1/1     Running   0          22h
$ [☸ dev:velero] velero version 
Client:
	Version: v1.0.0
	Git commit: -
Server:
	Version: v1.0.0
```

After switching to `prod` context I can list pods but not issue `velero` commands:
```shell
$ [☸ dev:velero] kubectx prod
Switched to context "prod".
$ [☸ prod:velero] k get pods 
NAME                      READY   STATUS    RESTARTS   AGE
velero-5dd4bbdd9c-59jxr   1/1     Running   0          22h
$ [☸ prod:velero] velero version   
Client:
	Version: v1.0.0
	Git commit: -
<error getting server version: the server has asked for the client to provide credentials (post serverstatusrequests.velero.io)>
```

When explicitly specifying a kube config file I can issue `velero` commands in `prod` context:
```shell
$ [☸ prod:velero] KUBECONFIG=~/.kube/prod-kube-config velero version 
Client:
	Version: v1.0.0
	Git commit: -
Server:
	Version: v1.0.0

```

**What did you expect to happen:**
I expected Velero to pick up the context from kubectl and authenticate against the api server

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
https://gist.github.com/switchboardOp/6bbfaad04fd3cd560bd19737794f4b8c
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
* `velero backup logs <backupname>`
* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
* `velero restore logs <restorename>`

**Anything else you would like to add:**
I'm using [kubectx](https://github.com/ahmetb/kubectx) to switch contexts, but the results are the same with the native `kubectl config` commands.
Both clusters are essentially identical as far as configuration.
Both `dev` and `prod` contexts are set up to use the Rancher auth proxy.

**Environment:**

- Velero version (use `velero version`): 
```
Client:
	Version: v1.0.0
	Git commit: -
Server:
	Version: v1.0.0
```
- Kubernetes version (use `kubectl version`): 
```
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCommit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:"2019-05-16T18:56:40Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes installer & version: Rancher 2.2.4
- Cloud provider or hardware configuration: Nutanix AHV VMs
- OS (e.g. from `/etc/os-release`): RancherOS v1.5.2

**Comment by nrb** [comment]
I made the following change on my local machine to see what context was being passed into Velero's client.

```diff
--- i/pkg/client/client.go
+++ w/pkg/client/client.go
@@ -34,6 +34,8 @@ func Config(kubeconfig, kubecontext, baseName string) (*rest.Config, error) {
        loadingRules.ExplicitPath = kubeconfig
        configOverrides := &clientcmd.ConfigOverrides{CurrentContext: kubecontext}
        kubeConfig := clientcmd.NewNonInteractiveDeferredLoadingClientConfig(loadingRules, configOverrides)
+       rawConfig, _ := kubeConfig.RawConfig()
+       fmt.Printf("kubecontext: %s\n", rawConfig.CurrentContext)
        clientConfig, err := kubeConfig.ClientConfig()
        if err != nil {
                return nil, errors.WithStack(err)
```

I'm currently operating with a single kubeconfig file.

On my normal context, I see this:

```bash
x1c in /home/nrb/go/src/github.com/heptio/velero (git) master U
% velero version
kubecontext: admin@kubernetes
Client:
        Version: master
        Git commit: 63964fc6f9df327919d27facccf31448bb36f07f-dirty
Server:
        Version: master
```

Next, I try to make a new, empty context and use it.

```bash
x1c in /home/nrb/go/src/github.com/heptio/velero (git) master U
% k config set-context context2
Context "context2" created.

x1c in /home/nrb/go/src/github.com/heptio/velero (git) master U
% k config use-context context2
Switched to context "context2".

x1c in /home/nrb/go/src/github.com/heptio/velero (git) master U
% velero version
kubecontext: context2
An error occurred: invalid configuration: no configuration has been provided
```

The same with `kubectx`:

```
x1c in /home/nrb/go/src/github.com/heptio/velero (git) master U
% kubectx admin@kubernetes
Switched to context "admin@kubernetes".

x1c in /home/nrb/go/src/github.com/heptio/velero (git) master U
% velero version
kubecontext: admin@kubernetes
Client:
        Version: master
        Git commit: 63964fc6f9df327919d27facccf31448bb36f07f-dirty
Server:
        Version: master

x1c in /home/nrb/go/src/github.com/heptio/velero (git) master U
% kubectx context2
Switched to context "context2".

x1c in /home/nrb/go/src/github.com/heptio/velero (git) master U
% velero version
kubecontext: context2
An error occurred: invalid configuration: no configuration has been provided
```

Interestingly, this variable doesn't get resolved as I'd expect if I use Velero's `--kubecontext` parameter. The `RawConfig` should have the override value where I print, but what's there is not the value explicitly passed in.

```
x1c in /home/nrb/go/src/github.com/heptio/velero (git) master U
% kubectx admin@kubernetes
Switched to context "admin@kubernetes".

x1c in /home/nrb/go/src/github.com/heptio/velero (git) master U
% velero version --kubecontext context2
kubecontext: admin@kubernetes
An error occurred: invalid configuration: no configuration has been provided
```

So, so far I'm unable to reproduce this, but I likely need to dig deeper into the client-go code to figure out what's going on.

**Comment by skriss** [comment]
I tested this out and was unable to reproduce. I have a `$KUBECONFIG` with a value of `~/.kube/aws-config:~/.kube/gke-config`, one context in each of those files, and I'm able to switch contexts using `kubectx` and properly run both `kubectl` and `velero` commands against both clusters/contexts.

@switchboardOp wondering if there's something else going on? What's different in your setup vs. what I described?

**Comment by switchboardOp** [comment]
It looks like I was actually running into a know issue with how Rancher constructs its kubeconfig files for multiple clusters. It was strange though because at the time I only had the issue when using `velero`. Since implementing a workaround i don't have the issue anymore. I don't think there's anything wrong with how `velero` is handling kubeconfig.

Sorry for the confusion.

https://github.com/rancher/rancher/issues/19342
