### ISSUE TITLE
Restic cannot backup EFS volume - expected one matching path

### ISSUE THREAD

**Issue by AdamMichaelLong** [heptio/velero#1638]
**What steps did you take and what happened:**

- I have a minimal nginx deployment which I am using to test Velero and Restic integration. [gist](https://gist.github.com/AdamMichaelLong/aa06e2febfcb9552516060d67a0e1e9a)

- The nginx pod has a pvc (EFS) mount on /tmp

- The volumeMount and volume name is "tmp"

- The pod is annotated `backup.velero.io/backup-volumes: tmp`

When I run a backup
`velero backup create sandbox-backup --include-namespaces sandbox `

I get a `PartiallyFailed` phase. 
`velero backup describe sandbox-backup`
[gist](https://gist.github.com/AdamMichaelLong/8aad9280ab8e237d86689e0f803018bd)

In restic pod logs I can see `Error uniquely identifying volume path" backup=velero/sandbox-backup controller=pod-volume-backup error="expected one matching path, got 0"`
[gist](https://gist.github.com/AdamMichaelLong/6735e59b4697b08a0ca96c23e6d7c134)

**Anything else you would like to add:**
- wondering if this is pointing to any issue with mountPropagation in Kubernetes. 

**Environment:**

- `velero Version: v1.0.0`
- `kubernetes v1.9.1+a0ce1bc657`
- `OpenShift 3.9`
- AWS

**Comment by skriss** [comment]
> wondering if this is pointing to any issue with mountPropagation in Kubernetes.

Definitely possible - mount propagation is a required feature for restic, and it became a `beta` feature (meaning enabled by default) in Kubernetes v1.10. Since you're on 1.9, you would need to explicitly enable the feature gate for it (https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/).

**Comment by AdamMichaelLong** [comment]
mountPropagation feature gate is now enabled and the same error is output in Restic daemonset pod logs

`time="2019-07-11T00:57:55Z" level=info msg="Backup starting" backup=velero/sandbox-backup controller=pod-volume-backup logSource="pkg/controller/pod_volume_backup_controller.go:171" name=sandbox-backup namespace=velero | time="2019-07-11T00:57:55Z" level=error msg="Error uniquely identifying volume path" backup=velero/sandbox-backup controller=pod-volume-backup error="expected one matching path, got 0" error.file="/go/src/github.com/heptio/velero/pkg/controller/pod_volume_backup_controller.go:312" error.function=github.com/heptio/velero/pkg/controller.singlePathMatch logSource="pkg/controller/pod_volume_backup_controller.go:199" name=sandbox-backup-xk5rh namespace=velero
`
Is there any Restic prerequisite for the volumeMount to configure the feature, assuming these are not privileged containers.
eg. `mountPropagation: HostToContainer`  ?

**Comment by AdamMichaelLong** [comment]
Velero has the privileged serviceaccount as described [here](https://velero.io/docs/v1.0.0/restic/)
"/var/lib/origin/openshift.local.volumes/pods" is inaccessible (permission denied on `ls -l /host_pods`) as a hostPath mounted in daemonset pods, SELinux maybe playing a part in this.

**Comment by AdamMichaelLong** [comment]
This can be closed setting sc on pod does the job. 

```          
securityContext:
  privileged: true
  runAsUser: 0
  seLinuxOptions:
    level: 's0:c123,c456'
```
