### ISSUE TITLE
Create support feature for IBM cloud storage disk snapshot

### ISSUE THREAD

**Issue by estefancaique** [heptio/velero#1642]
Create support feature for IBM cloud storage disk snapshot

**Comment by nrb** [comment]
Hi @estefancaique!

This is unlikely to be implemented in-tree, however someone could create a VolumeSnapshot plugin supporting IBM Cloud's snapshots.

**Comment by skriss** [comment]
@estefancaique as @nrb said, the core team won't be implementing this but we would love to have a community member work on it and could provide guidance. This would be implemented outside of the Velero repository. Closing this issue.
