### ISSUE TITLE
Velero on Prem : Not clear

### ISSUE THREAD

**Issue by rohitvarma1986** [heptio/velero#1643]
Hi,

Its not clear how to install Velero server on the on Prem running Kubernetes cluster.
Tried using the velero install command but need to provide in the PROVIDER, cannot leave provider blank. I don't want to give a provider, would be using Minio ( its running ) and Restic.

Can you help ?

**Comment by skriss** [comment]
You can more or less follow https://velero.io/docs/v1.0.0/get-started/ -- to answer your specific question, the provider will be "aws" since minio is an S3-compatible object store.

**Comment by rohitvarma1986** [comment]
Thanks. I followed the same link as you mentioned above.
My confusion is my whole setup is on Prem. I don't want to use AWS ( cloud ).

It also asks for aws access and secret, which is my confusion. Since I am not using AWS, why do I have to give that ? Can you help

**Comment by skriss** [comment]
that would be the keys to authenticate to minio - how do you usually do that?

**Comment by rohitvarma1986** [comment]
Thanks it worked. Closing ticket now.
