### ISSUE TITLE
Kube Context Flag not respected

### ISSUE THREAD

**Issue by djtaylor** [heptio/velero#1651]
**What steps did you take and what happened:**
I am running the `velero install` command, but it does not appear to be respecting the `--kubecontext` flag.

**What did you expect to happen:**
I have three contexts in my local kubeconfig, `APP-Dev` and `APP-Gotham` are the two I am interested in. Even with my current context set to `APP-Gotham`, when I run the command, it still applies to the cluster that my local `kubectl` has setup as the default context. I expect the `--kubecontext` flag to be used regardless of what my current default context is.

**The output of the following commands will help us better understand what's going on**:
The following gist shows that my current default context is set to `APP-Gotham`. Prior to running `velero install` there are no pods (nothing exists yet). When I run the command with the `--kubecontext` set to `APP-Dev`, it still installs using the `APP-Gotham` context. You can see that the pod was created in the `velero` namespace.

https://gist.github.com/djtaylor/f26fafd1be6a42d5084e24fdf7c8dd54

**Anything else you would like to add:**
This appears to be client side only. If I can provide any other troubleshooting information please let me know.

**Environment:**

velero version:
```
Client:
	Version: v1.0.0
	Git commit: 72f5cadc3a865019ab9dc043d4952c9bfd5f2ecb
```

kubectl client and server version:
```
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:57:14Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.3", GitCommit:"435f92c719f279a3a67808c80521ea17d5715c66", GitTreeState:"clean", BuildDate:"2018-11-26T12:46:57Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
```

We are running on bare-metal using Ubuntu 18.04.2 with Kubernetes version 1.12.3.

**Comment by skriss** [comment]
xref #1637

**Comment by skriss** [comment]
@nrb can you look into this some more? I took a quick look and saw that [here](https://github.com/heptio/velero/blob/master/pkg/cmd/cli/install/install.go#L181) we're explicitly constructing a config, using empty strings for kubeconfig/kubecontext, rather than using the `client.Factory` passed into `NewCommand(...)` which gets those values bound to the flags. It looks like we might want to add a `DynamicClient(...)` method to the `client.Factory` type to make this easier, that uses the proper kubeconfig/kubecontext values.

**Comment by nrb** [comment]
That does indeed look like the right fix. PR incoming shortly.
