### ISSUE TITLE
Backup not working for Persistent Volume

### ISSUE THREAD

**Issue by rohitvarma1986** [heptio/velero#1658]
Velero backup is giving partial failure. Logs indicate following below :-

g="**Error backing up item" backup=velero/nginx-backup6 error="pod volume backup failed: error getting volume path on host: expected one matching path, got 0**" err

**Comment by skriss** [comment]
Can you provide some more information:

- the YAML for the pod and persistent volume that you're backing up
- what Kubernetes platform and version are you running on?

**Comment by skriss** [comment]
Closing as inactive.
