### ISSUE TITLE
Update velero install package to use apps/v1 API Group

### ISSUE THREAD

**Issue by nrb** [heptio/velero#1672]
In Kubernetes 1.16, the [extensions/v1beta1 API group will no longer be served by default](https://groups.google.com/forum/#!topic/kubernetes-dev/je0rjyfTVyc/discussion).

`velero install` currently uses this group for its Deployment, so it will need to be updated. The Helm chart already uses this API group.

**Comment by prydonius** [comment]
I believe we're using app/v1beta1 instead of extensions/v1beta1 which will be served longer than the latter, but still probably worth updating this to apps/v1.

**Comment by nrb** [comment]
You're correct! Extensions is in use for CRDs, which also need to be examined for the [structural schema](https://kubernetes.io/blog/2019/06/20/crd-structural-schema/) support coming down the pipe.

#1673 does the appropriate thing.

**Comment by prydonius** [comment]
Actually I just noticed that apps/v1beta1 will also no longer be served in apps/v1 so we definitely do need to update this!
