### ISSUE TITLE
Turn off legacy gh-pages site

### ISSUE THREAD

**Issue by skriss** [heptio/velero#1676]
We've moved our docs to velero.io but the legacy github pages site is still around. We should turn this off  once we're sure we've  gotten all of our links updated.

**Comment by nrb** [comment]
My first Google hit for "velero restic" is the github.io site...I wonder if it would be preferable to change the site to be permanent redirects for a short period of time.

Upside is that it gets the search engines updated and would redirect users who have old bookmarks.

Downside is leaving it active longer while it's not really maintained.

**Comment by nrb** [comment]
Another downside - it looks like there's not an easy way to just make pages redirects. Have to jump through the Jekyll hoops.

**Comment by skriss** [comment]
cc @jonasrosland

**Comment by skriss** [comment]
this is done.
