### ISSUE TITLE
[Question] Backup validation vs backup restore testing

### ISSUE THREAD

**Issue by solomson** [heptio/velero#1688]
**Describe the problem/challenge you have**

For context I am a believer in the saying "Untested data backup is no backup at all".

I have a production cluster scheduled to taking snapshots of four namespaces every night. This includes four persistent volumes in total. Now I have done some manual test restores in my dev cluster which have been successful. Ideally I would like automated restore tests based on backups from my prod cluster, while not affecting the actual resources used in production (I realize this might not be the easiest thing to implement).

Based on the Backup workflow chapter in the [Docs](https://velero.io/docs/v1.0.0/about/) it is unclear for me how reliable the built-in validation is compared to doing manual restore tests. Is regularly doing restore tests still necessary? Are there any plans to automate restore tests in future releases?

**Comment by skriss** [comment]
I would definitely encourage you to continue testing restores regularly. I think doing them into a dev or alternate prod cluster makes sense.

I'm not sure what further automation you think Velero could use to help with restore testing - could you elaborate?

**Comment by solomson** [comment]
I'm imagining this for a workflow:

- Backup of ns prod_xxx @ 4.00 am - in prod cluster
- Once backup is successfully completed -  Velero can automatically test backup restore of this backup in a temporary namespace (either in a dev cluster or a duplicate namespace with another name)
- After the restore is complete - somehow compare the restored backup to what is currently in production. For some resources perhaps checksums are possible. For my use case the most important thing is to verify that no contents of my persistent volumes have been lost in the backup process.

I'm imagining some problems with implementing this model, specifically URL conflicts (imagine both a production pod and a duplicate pod wanting to run a web-server on the same public URL).
Some of this might be doable with a shell script though. (E.g. running velero restore create --from-schedule xxx as a cronjob, then manually verifying that contents are in place)

I haven't found any related issues or fitting resources in this repo, Which I find strange as I imagine others are looking to automate backup testing as well.

**Comment by skriss** [comment]
This seems like a sensible workflow. My view is that this is something that can be implemented outside Velero itself, using the CRD API or the CLI to trigger actions as needed.

**Comment by skriss** [comment]
Closing this out.
