### ISSUE TITLE
--secret-file is optionnal for AWS deployment.

### ISSUE THREAD

**Issue by pierreozoux** [heptio/velero#1689]
Currently when you issue the install command, it requires you to give a `--secret-file` argument.

If you deploy on AWS, the aws sdk go might be able to use the kube2iam or instance role if you don't pass this env var.

As it is a possibility, I think the `secret-file` parameter should be optional and the documentation updated to reflect that.

**Comment by nrb** [comment]
@pierreozoux Thanks, I've been meaning to file this issue and have a note to make secret-file optional. See #1674 for a discussion of some options. You can currently pass in an empty file, but that's obviously not ideal.

I'll get a PR in for this soon.
