### ISSUE TITLE
Velero kubernetes pod is in container creating 

### ISSUE THREAD

**Issue by deekshith-elear** [heptio/velero#1701]
After doing velero install. I got below logs
`Velero is installed! ⛵ Use 'kubectl logs deployment/velero -n velero' to view the status.`
By checking `kubectl get all -n velero` pod status is still in container creating
I checked out all slaves there is no docker image of velero was pulled.
Can anyone help me out to solve this issue

**Comment by skriss** [comment]
Can you provide the output of `kubectl -n velero describe pods`? And also the exact `velero install` command that you ran, including all the flags?

**Comment by skriss** [comment]
Inactive - closing, reopen as needed.
