### ISSUE TITLE
Need update velero image

### ISSUE THREAD

**Issue by haoshuwei** [heptio/velero#1719]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
does the latest image `gcr.io/heptio-images/velero:latest` include fix about issue[#1395](https://github.com/heptio/velero/issues/1395)?

I find that the PR [https://github.com/heptio/velero/pull/1560](https://github.com/heptio/velero/pull/1560) is merged on 11 Jun , but image is 2 months ago
```
docker images|grep velero
gcr.io/heptio-images/velero                                                latest                       d5e9c67d8c1b        2 months ago        163MB
```

**What did you expect to happen:**

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
* `velero backup logs <backupname>`
* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
* `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by skriss** [comment]
The fix for #1395 will be released in v1.1, which should be coming out within the next few weeks.
