### ISSUE TITLE
unknown shorthand flag: 'n' in -n

### ISSUE THREAD

**Issue by drzero42** [heptio/velero#1720]
**What steps did you take and what happened:**
According to `velero --help` you can specify the namespace with either `-n` or `--namespace`.
When running `velero install -n NAMESPACE` this error is given: `unknown shorthand flag: 'n' in -n`.
It works correctly when I run: `velero instal --namespace NAMESPACE`.

**What did you expect to happen:**
I expected `-n` to work as specified in the help output.

**Environment:**

- Velero version (use `velero version`): v1.0.0

**Comment by skriss** [comment]
Yep, looks like we're not using the persistent `namespace` flag that's bound to the root velero command in `velero install`, but instead re-binding it without a shorthand flag.
