### ISSUE TITLE
using with 'skaffold deploy' made duplicated deployment

### ISSUE THREAD

**Issue by skame** [heptio/velero#1746]
**Describe the problem/challenge you have**

I want to use [skaffold](https://skaffold.dev) for deploying manifest files.

1. skaffold deploy
2. backup by velero
3. delete namespace
4. restore by velero
5. skaffold deploy

It resulted in duplicated deployments.

**Describe the solution you'd like**

A skaffold checks the change of deployed manifests and only deploy difference manifests.

**Anything else you would like to add:**

**Environment:**

- Velero version (use `velero version`): v1.0.0
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:v1.14.0
- Cloud provider or hardware configuration:On-Prem
- OS (e.g. from `/etc/os-release`):Ubuntu 16.04.6 LTS

**Comment by prydonius** [comment]
@skame if I understand correctly, skaffold is not recognising the restored manifests and is just re-deploying everything? Do you know what skaffold uses to track manifests?

**Comment by skame** [comment]
Yes, your understanding is correct.

I'm looking for what parameter skaffold tracks but I couldn't.

ref. https://skaffold.dev/docs/

I think that label or something may be used for tracking, there I want to know what parameters are omitted in backup/restore.

ref. https://github.com/GoogleContainerTools/skaffold/pull/644

**Comment by prydonius** [comment]
Hmm, I'm not able to reproduce this with skaffold's getting-started example:

```
> skaffold deploy
Loading images into kind cluster nodes...
Images loaded in 65.157µs
Starting deploy...
kubectl client version: 1.15
pod/getting-started created
Deploy complete in 369.995439ms

> velero create backup skaffold --include-namespaces skaffold
Backup request "skaffold" submitted successfully.
Run `velero backup describe skaffold` or `velero backup logs skaffold` for more details.

> kubectl delete ns skaffold
namespace "skaffold" deleted

> velero create restore --from-backup skaffold
Restore request "skaffold-20190813111246" submitted successfully.
Run `velero restore describe skaffold-20190813111246` or `velero restore logs skaffold-20190813111246` for more details.

> skaffold deploy
Loading images into kind cluster nodes...
Images loaded in 38.7µs
Starting deploy...
kubectl client version: 1.15
pod/getting-started unchanged
Deploy complete in 554.340876ms
```

**Comment by skame** [comment]
Thank you for your test. I also tried to reproduce the situation but I couldn't.
The duplication should be caused by other reason.
I'm sorry to bother you.

**Comment by prydonius** [comment]
@skame no worries! feel free to reopen or file a new issue if you see any issues again!
