### ISSUE TITLE
Back up a remote cluster

### ISSUE THREAD

**Issue by rbankston** [heptio/velero#1751]
**Describe the problem/challenge you have**
Trying to be able to provide a back up for a second cluster's workloads on a system like Gardener or Openstack from the main cluster without needing to install Velero on the workload cluster. Is this workflow not supported and Velero has to be installed in both clusters to provide a backup? 

**Describe the solution you'd like**
Install Velero on one cluster to back up a remote cluster

**What steps did you take and what happened:**

#### Clusters
1) Cluster A - 1.15.1
1) Cluster B - 1.15.1

#### Steps:
Installed minio example and Velero on cluster A by running 

```
./velero install     --provider aws     --bucket velero     --secret-file ./credentials-velero     --use-volume-snapshots=false     --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://minio.velero.svc:9000  --dry-run -o yaml > velero-clusterb.yaml
```
Edited the resulting velero-clusterb.yaml to add

* Secondary clusters kubeconfig mounted in the velero pod
* Set environment variable to point to the kubeconfig

When running a back up from cluster A that should be pointed to cluster B and run ./velero create backup all get the following errors in the log:

```
E0810 02:21:42.027769       1 reflector.go:134] github.com/heptio/velero/pkg/generated/informers/externalversions/factory.go:117: Failed to list *v1.VolumeSnapshotLocation: the server could not find the requested resource (get volumesnapshotlocations.velero.io)
E0810 02:21:42.042388       1 reflector.go:134] github.com/heptio/velero/pkg/generated/informers/externalversions/factory.go:117: Failed to list *v1.DeleteBackupRequest: the server could not find the requested resource (get deletebackuprequests.velero.io)
E0810 02:21:42.094915       1 reflector.go:134] github.com/heptio/velero/pkg/generated/informers/externalversions/factory.go:117: Failed to list *v1.ResticRepository: the server could not find the requested resource (get resticrepositories.velero.io)
E0810 02:21:42.133566       1 reflector.go:134] github.com/heptio/velero/pkg/generated/informers/externalversions/factory.go:117: Failed to list *v1.BackupStorageLocation: the server could not find the requested resource (get backupstoragelocations.velero.io)
E0810 02:21:42.203808       1 reflector.go:134] github.com/heptio/velero/pkg/generated/informers/externalversions/factory.go:117: Failed to list *v1.Schedule: the server could not find the requested resource (get schedules.velero.io)
E0810 02:21:42.245289       1 reflector.go:134] github.com/heptio/velero/pkg/generated/informers/externalversions/factory.go:117: Failed to list *v1.ServerStatusRequest: the server could not find the requested resource (get serverstatusrequests.velero.io)
E0810 02:21:42.292291       1 reflector.go:134] github.com/heptio/velero/pkg/generated/informers/externalversions/factory.go:117: Failed to list *v1.DownloadRequest: the server could not find the requested resource (get downloadrequests.velero.io)
E0810 02:21:42.335970       1 reflector.go:134] github.com/heptio/velero/pkg/generated/informers/externalversions/factory.go:117: Failed to list *v1.Backup: the server could not find the requested resource (get backups.velero.io)
E0810 02:21:42.389550       1 reflector.go:134] github.com/heptio/velero/pkg/generated/informers/externalversions/factory.go:117: Failed to list *v1.Restore: the server could not find the requested resource (get restores.velero.io)
E0810 02:21:42.425833       1 reflector.go:134] github.com/heptio/velero/pkg/generated/informers/externalversions/factory.go:117: Failed to list *v1.PodVolumeBackup: the server could not find the requested resource (get podvolumebackups.velero.io)
E0810 02:21:43.029498       1 reflector.go:134] github.com/heptio/velero/pkg/generated/informers/externalversions/factory.go:117: Failed to list *v1.VolumeSnapshotLocation: the server could not find the requested resource (get volumesnapshotlocations.velero.io)
E0810 02:21:43.043861       1 reflector.go:134] github.com/heptio/velero/pkg/generated/informers/externalversions/factory.go:117: Failed to list *v1.DeleteBackupRequest: the server could not find the requested resource (get deletebackuprequests.velero.io)
E0810 02:21:43.096819       1 reflector.go:134] github.com/heptio/velero/pkg/generated/informers/externalversions/factory.go:117: Failed to list *v1.ResticRepository: the server could not find the requested resource (get resticrepositories.velero.io)
E0810 02:21:43.134764       1 reflector.go:134] github.com/heptio/velero/pkg/generated/informers/externalversions/factory.go:117: Failed to list *v1.BackupStorageLocation: the server could not find the requested resource (get backupstoragelocations.velero.io)
E0810 02:21:43.205213       1 reflector.go:134] github.com/heptio/velero/pkg/generated/informers/externalversions/factory.go:117: Failed to list *v1.Schedule: the server could not find the requested resource (get schedules.velero.io)
E0810 02:21:43.246582       1 reflector.go:134] github.com/heptio/velero/pkg/generated/informers/externalversions/factory.go:117: Failed to list *v1.ServerStatusRequest: the server could not find the requested resource (get serverstatusrequests.velero.io)
E0810 02:21:43.293986       1 reflector.go:134] github.com/heptio/velero/pkg/generated/informers/externalversions/factory.go:117: Failed to list *v1.DownloadRequest: the server could not find the requested resource (get downloadrequests.velero.io)
E0810 02:21:43.337884       1 reflector.go:134] github.com/heptio/velero/pkg/generated/informers/externalversions/factory.go:117: Failed to list *v1.Backup: the server could not find the requested resource (get backups.velero.io)
E0810 02:21:43.391647       1 reflector.go:134] github.com/heptio/velero/pkg/generated/informers/externalversions/factory.go:117: Failed to list *v1.Restore: the server could not find the requested resource (get restores.velero.io)
E0810 02:21:43.427569       1 reflector.go:134] github.com/heptio/velero/pkg/generated/informers/externalversions/factory.go:117: Failed to list *v1.PodVolumeBackup: the server could not find the requested resource (get podvolumebackups.velero.io)
```

**What did you expect to happen:**
Expected cluster A to 

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* [`kubectl logs deployment/velero -n velero`](https://gist.github.com/rbankston/96c6b10e67aaea2e2c5693953bfef517)
* [`kubectl get backup/maybe -n velero -o yaml`](https://gist.github.com/rbankston/dae17470c11dbef2bedda655fd6a9131)
* `velero backup logs maybe`
  - Logs for backup "maybe" are not available until it's finished processing. Please wait until the backup has a phase of Completed or Failed and try again.`

**Environment:**

Both machines
- Kubernetes version (use `kubectl version`): v1.15.1
- Kubernetes installer & version: Kubeadm
- Cloud provider or hardware configuration: vm on vSphere 6.5 with 4 cpu's and 4gb of memory
- OS (e.g. from `/etc/os-release`): NAME="CentOS Linux" VERSION="7 (Core)"

Cluster A
- Velero version (use `velero version`):  	Version: v1.0.0

**Comment by skriss** [comment]
Ah, yeah so the Velero CRDs, namespace, and service account will all need to exist in the target cluster.  The Velero pod itself can run in a different cluster.

**Comment by rbankston** [comment]
@skriss would the backup location and secret also need to exist in the remote cluster for Velero to work correctly?

**Comment by skriss** [comment]
the backup location would, yes. The secret would not, since our standard deployment model mounts that into the pod wherever the pod is running.

**Comment by rbankston** [comment]
created the backup location but without adding the full deployment from Velero the backup stays at 

```
NAME   STATUS   CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
redo   New      0001-01-01 00:00:00 +0000 UTC   29d                          <none>
```
but the backup never seems to run

**Comment by ABHINAV-SUREKA** [comment]
> the backup location would, yes. The secret would not, since our standard deployment model mounts that into the pod wherever the pod is running.

Will the restoring the remote cluster also work when done from another cluster?

**Comment by rbankston** [comment]
@skriss will the remote cluster be able to be restored without having the Velero pod installed in it as well or does the Velero pod need to run in both the local and remote cluster for cross cluster backups and restore?

**Comment by prydonius** [comment]
@rbankston the Velero pod can exist in the remote cluster, but will need to read a kubeconfig to access the target cluster in order to restore into it. You can use the `--kubeconfig` on the Deployment to point to a mounted kubeconfig.

**Comment by rbankston** [comment]
Interesting. I've not been able to get a back up or restore to generate using such a configuration. I mounted the kubeconfig for the remote credentials in the deployment and set the path for it via the KUBECONFIG enviroment variable. Here is a copy of the [local cluster's config](https://gist.github.com/rbankston/51f202877f297a4726cbdd4887f6bc0d). On the remote cluster was only able to get a back up or restore to occur following the deployment of Velero pod on that cluster.

**Comment by prydonius** [comment]
@rbankston those CRDs will need to exist in the remote cluster, as well as the Backup/Restore custom resources (i.e. your local velero CLI needs to point to the remote cluster as well). The velero server will watch these resources on the remote cluster with the given kubeconfig. Does that make sense?

**Comment by rbankston** [comment]
@prydonius thanks for the information in regards to the velero cli pointing to the remote cluster
