### ISSUE TITLE
Move away from  'crypto/sha1' for AWS Sign Requests

### ISSUE THREAD

**Issue by davissp14** [heptio/velero#1757]
SHA1 has been deemed unsafe for a while now.  The use of HMAC-SHA1 is a little better, we should look to move to SHA2 or SHA3 for better security. 

**Describe the solution you'd like**
Move to SHA2 or SHA3

https://github.ibm.com/ibm-cloud-databases/velero/blob/6513e8f30e8314f2188159b3472fd627a9bd2619/pkg/cloudprovider/aws/v1_sign_request_handler.go#L21

**Comment by skriss** [comment]
@davissp14 the v1 signature handler you're referencing is **not** the default. https://github.com/heptio/velero/pull/998 will give you some more context on why that exists. v4 is used by default.

**Comment by skriss** [comment]
Closing this out as the default signing method is v4 which uses SHA-2, and the v1 handler is around for backwards compatibility for other providers and is opt-in only.
