### ISSUE TITLE
Digitalocean persistent volumes

### ISSUE THREAD

**Issue by dottodot** [heptio/velero#1771]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

I've setup the latest version of velero and can can create a backup of my digitalocean cluster but the persistent volumes are not included.

I'm not sure if I need to use restic or a plugin to make this happen.

**What did you expect to happen:**

persistent volumes to be included in backup

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `velero backup describe k8-test-backup`

```
Name:         k8-test-backup
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  <none>

Phase:  PartiallyFailed (run `velero backup logs k8-test-backup` for more information)

Errors:    7
Warnings:  0

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  <none>

Storage Location:  default

Snapshot PVs:  true

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2019-08-18 10:02:09 +0100 BST
Completed:  2019-08-18 10:02:16 +0100 BST

Expiration:  2019-09-17 10:02:09 +0100 BST

Persistent Volumes: <none included>
```

**Environment:**

- Velero version (use `velero version`): v1.0.0
- Kubernetes version (use `kubectl version`): v1.14.0
- Kubernetes installer & version: 1.13.5
- Cloud provider or hardware configuration: Digitalocean
- OS (e.g. from `/etc/os-release`):

**Comment by skriss** [comment]
hi @dottodot, there is a Digital Ocean plugin, but unfortunately it appears to be out of date. I would suggest filing an issue at https://github.com/StackPointCloud/ark-plugin-digitalocean.

In the mean time, you could use restic to be able to get backups of your volumes - the [restic docs](https://velero.io/docs/v1.0.0/restic/) should get you started.

**Comment by dottodot** [comment]
@skriss I was going to have a look at using restic, but I couldn't find any information on how to add it if velero has already been installed on the cluster.

**Comment by skriss** [comment]
You can run the `velero install` command again using the `--use-restic` flag, and it'll just add the necessary daemonset to the `velero` namespace while leaving everything else in place. Or you can use `--dry-run -o yaml` if you want to just dump the YAML and apply manually.

**Comment by skriss** [comment]
Closing this out, feel free to reach out again if needed!

**Comment by mvgrimes** [comment]
I'm trying to backup from digitalocean using AWS S3 for storage and the `--use-restic` flag. The backup completes without error, but no PVs are backed up:

```
$ velero backup describe kci-wiki | grep -E "Vol|PVs|Phase"
Phase:  Completed
Snapshot PVs:  auto
Persistent Volumes: <none included>
```

I believe I have the correct annotation on the pod:

```
$ kubectl -n kci describe pod kci-wiki-5c6f85cb6b-jfh62 | grep -EA 3 "Annotation|Mounts"
Annotations:    backup.velero.io/backup-volumes: kci-wiki-data
...
    Mounts:
      /srv/app/data from kci-wiki-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-htvzd (ro)
```

Velero: v1.0.0
Kubectl: v1.16.0
Kubernetes: v1.15.3
Cloud provider: Digitalocean

**Comment by Berndinox** [comment]
Another approach: https://www.digitalocean.com/docs/kubernetes/how-to/create-snapshots/
