### ISSUE TITLE
Restore error with restic

### ISSUE THREAD

**Issue by estefancaique** [heptio/velero#1773]
I had a problem with restore with rest pod and took the following error below

time="2019-08-16T21:54:04Z" level=error msg="unable to successfully complete restic restores of pod's volumes" error="timed out waiting for all PodVolumeRestores to complete" logSource="pkg/restore/restore.go:1060" restore=velero/jenkins1-20190816175403

Do you have solution about problem restore.
Thanks

**Comment by skriss** [comment]
To help diagnose this, can you provide the output of:

- `kubectl -n velero get pods`
- `velero restore describe jenkins1-20190816175403 --details`
- `kubectl -n velero get podvolumerestores -l velero.io/restore-name=jenkins1-20190816175403 -o yaml`

**Comment by estefancaique** [comment]
Follow

![image](https://user-images.githubusercontent.com/15111948/63276271-6e5e0e80-c279-11e9-91cc-490ea9024d0b.png)

![image](https://user-images.githubusercontent.com/15111948/63276359-99486280-c279-11e9-88e2-4ee6ac91e312.png)

![image](https://user-images.githubusercontent.com/15111948/63276473-d3b1ff80-c279-11e9-9e8f-b4181ba3715b.png)

**Comment by skriss** [comment]
Can you also provide `velero restore logs jenkins1-20190816175403` and `kubectl -n jenkins get pod jenkins-5697555549-r5ww4 -o yaml`?

**Comment by estefancaique** [comment]
[jenkins-7bf97b49d8-26t9p.log](https://github.com/heptio/velero/files/3516513/jenkins-7bf97b49d8-26t9p.log)
[jenkins1-20190816175403.log](https://github.com/heptio/velero/files/3516514/jenkins1-20190816175403.log)

**Comment by skriss** [comment]
It seems like maybe there was already another jenkins pod running when you attempted the restore. In order for the restore to work, you'll want to first delete any resources that you need to restore (e.g. the deployment, replicaset, pod, etc). I think what probably happened is that Velero restored the pod, but it was immediately deleted because the jenkins replicaset already had the 1 replica it needed.

**Comment by estefancaique** [comment]
Thank you @skriss 
we had already done the restore i will delete all jenkins resources in this cluster and restore again i will do it now i warn you if the test was successful

**Comment by skriss** [comment]
Closing as inactive, please reach out again as needed!
