### ISSUE TITLE
AWS:fail to deploy velero 

### ISSUE THREAD

**Issue by semimata** [heptio/velero#1787]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
I deployed velero in accordance withfollowing link.
https://velero.io/docs/v1.0.0/aws-config/

**What did you expect to happen:**
 I expected that the pod under the velero namespace but its failing

**The output of the following commands will help us better understand what's going on:**
(Pasting long output into a GitHub gist or other pastebin is fine.)

I confirmed pod status and pod's log.

kubectl get pods -n velero
NAME                      READY   STATUS             RESTARTS   AGE
velero-544459d479-c6nms   0/1     CrashLoopBackOff   12         40m

kubectl logs velero-544459d479-c6nms -n velero
time="2019-08-22T09:11:04Z" level=info msg="setting log-level to INFO"
time="2019-08-22T09:11:04Z" level=info msg="Starting Velero server v1.0.0 (72f5cadc3a865019ab9dc043d4952c9bfd5f2ecb)" logSource="pkg/cmd/server/server.go:165"
time="2019-08-22T09:11:04Z" level=error msg="reading plugin stderr" cmd=/velero error="read |0: file already closed" logSource="pkg/plugin/clientmgmt/logrus_adapter.go:89" pluginName=velero
time="2019-08-22T09:11:04Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
time="2019-08-22T09:11:04Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pv
time="2019-08-22T09:11:04Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/serviceaccount
time="2019-08-22T09:11:04Z" level=info msg="registering plugin" command=/velero kind=VolumeSnapshotter logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/aws
time="2019-08-22T09:11:04Z" level=info msg="registering plugin" command=/velero kind=VolumeSnapshotter logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/azure
time="2019-08-22T09:11:04Z" level=info msg="registering plugin" command=/velero kind=VolumeSnapshotter logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/gcp
time="2019-08-22T09:11:04Z" level=info msg="registering plugin" command=/velero kind=ObjectStore logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/aws
time="2019-08-22T09:11:04Z" level=info msg="registering plugin" command=/velero kind=ObjectStore logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/azure
time="2019-08-22T09:11:04Z" level=info msg="registering plugin" command=/velero kind=ObjectStore logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/gcp
time="2019-08-22T09:11:04Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/addPVCFromPod
time="2019-08-22T09:11:04Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/addPVFromPVC
time="2019-08-22T09:11:04Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/job
time="2019-08-22T09:11:04Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
time="2019-08-22T09:11:04Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/restic
time="2019-08-22T09:11:04Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service
time="2019-08-22T09:11:04Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/serviceaccount
time="2019-08-22T09:11:04Z" level=info msg="Checking existence of namespace" logSource="pkg/cmd/server/server.go:355" namespace=velero
time="2019-08-22T09:11:04Z" level=info msg="Namespace exists" logSource="pkg/cmd/server/server.go:361" namespace=velero
time="2019-08-22T09:11:07Z" level=info msg="Checking existence of Velero custom resource definitions" logSource="pkg/cmd/server/server.go:390"
time="2019-08-22T09:11:07Z" level=info msg="All Velero custom resource definitions exist" logSource="pkg/cmd/server/server.go:424"
time="2019-08-22T09:11:07Z" level=info msg="Checking that all backup storage locations are valid" logSource="pkg/cmd/server/server.go:431"
An error occurred: some backup storage locations are invalid: backup store for location "default" is invalid: rpc error: code = Unknown desc = AccessDenied: Access Denied
        status code: 403,  

installation command 
velero install --provider aws --bucket "mybucket name" --secret-file "my secretfile" --backup-location-config region="region name" --snapshot-location-config region="region name"

**Environment:**
Velero version (use velero version):
v1.0.0

Kubernetes version (use kubectl version):
Client Version: v1.15.3
Server Version: v1.15.3

Kubernetes installer & version:
kops : v 1.12.3

Cloud provider or hardware configuration:
AWS

**Comment by skriss** [comment]
@semimata I would double-check the contents of your secret file and the IAM policy that you have set up for your IAM account - it looks like something there is incorrect.

**Comment by semimata** [comment]
@skriss Thank you for your advice. After I recreated IAM and secret file,I deployd again.
i deployed it successfullly.

Thank you.

**Comment by skriss** [comment]
Great! closing out the issue.
