### ISSUE TITLE
Velero backup is partially failing for Azure

### ISSUE THREAD

**Issue by anushaj-neualto** [heptio/velero#1823]
When we specify **"*"** in the **included namespce** and **null** in the **excluded namespace** while creating backup in Azure it is showing status as **PartiallyFailed**.

```
metadata:
 creationTimestamp: '2019-08-29T07:46:28Z'
 generation: 1
 labels:
   velero.io/schedule-name: test
   velero.io/storage-location: test
 name: test-20190829074628
 namespace: velero
 resourceVersion: '2570'
 selfLink: /apis/velero.io/v1/namespaces/velero/backups/test-20190829074628
 uid: 1c5012e3-ca31-11e9-bdd4-064392a6e835
apiVersion: velero.io/v1
kind: Backup
spec:
 excludedNamespaces: null
 excludedResources: null
 hooks:
   resources: null
 includeClusterResources: null
 includedNamespaces:
   - '*'
 includedResources: null
 labelSelector: null
 snapshotVolumes: true
 storageLocation: test
 ttl: 168h0m0s
 volumeSnapshotLocations:
   - test
status:
 completionTimestamp: '2019-08-29T07:46:29Z'
 errors: 3
 expiration: '2019-09-05T07:46:28Z'
 phase: PartiallyFailed
 startTimestamp: '2019-08-29T07:46:28Z'
 validationErrors: null
 version: 1
 volumeSnapshotsAttempted: 0
 volumeSnapshotsCompleted: 0
 warnings: 0
```
When we specify **"*"** in the **included namespace** and **velero** in the **excluded namespace** the Backup's status is **"Completed"**. 

However, this issue is not found for AWS and Google. It is happening only when using **AZURE** and when using image v1.0.0 and above. While using v1.0.0-alpha.1 it works fine.

**Environment:**

- Velero version (use `velero version`): v1.0.0 and above
- Cloud provider or hardware configuration: Azure

**Comment by skriss** [comment]
Can you provide the output of `velero backup logs <BACKUP_NAME>` for both the successful and partially-failed backups?

**Comment by skriss** [comment]
@anushaj-neualto do you need any further help here?

**Comment by anushaj-neualto** [comment]
No I haven't observed this issue anymore.

**Comment by skriss** [comment]
OK thanks, closing! Feel free to reach out again as needed.

**Comment by asishr14** [comment]
We have this issue on azure backup is partially failed and here are the error logs for it. 

=error msg="Error backing up item" backup=velero/live error="clusterroles.rbac.authorization.k8s.io \"cluster-admin\" not found" error.file="/go/src/github.com/heptio/velero/pkg/backup/item_backupper.go:331" error.function="github.com/heptio/velero/pkg/backup.(*defaultItemBackupper).executeActions" group=v1 logSource="pkg/backup/resource_backupper.go:264" name=velero namespace= resource=serviceaccounts
time="2019-11-19T16:15:06Z" level=info msg="Backing up resource" backup=velero/live group=v1 logSource="pkg/backup/resource_backupper.go:104" resource=services




=error msg="Error backing up item" backup=velero/live error="clusterroles.rbac.authorization.k8s.io \"system:auth-delegator\" not found" error.file="/go/src/github.com/heptio/velero/pkg/backup/item_backupper.go:331" error.function="github.com/heptio/velero/pkg/backup.(*defaultItemBackupper).executeActions" group=v1 logSource="pkg/backup/resource_backupper.go:264" name=metrics-server namespace= resource=serviceaccounts
time="2019-11-19T16:15:06Z" level=info msg="Backing up item" backup=velero/live group=v1 logSource="pkg/backup/item_backupper.go:162" name=omsagent namespace=kube-system resource=serviceaccounts

**Comment by skriss** [comment]
@asishr14 it sounds like you have a non-existent cluster role that is bound to the `omsagent` service account in the `kube-system` namespace.  The following command should find it for you:

```
kubectl get clusterrolebindings -o wide | grep kube-system/omsagent
```

If you remove this invalid clusterrolebinding, the Velero error should go away.
