### ISSUE TITLE
Velro/Ark is not support specific replicaset/Backup set backup level restore 

### ISSUE THREAD

**Issue by satishsudini** [heptio/velero#1825]
**Describe the problem/challenge you have**
Trying to backup only few replicasets in backup but we only have namespace level or cluster level backup 

**Describe the solution you'd like**
We can add feature to backup and restore only few deployments/replicaset

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):v0.9
- Kubernetes version (use `kubectl version`):1.15 
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):ubuntu 16.04

**Comment by skriss** [comment]
@satishsudini you can use a label selector (`--selector`) to select a subset of items within a namespace or the cluster.

**Comment by skriss** [comment]
@satishsudini does using a label selector get you what you need?

**Comment by skriss** [comment]
We also have #904 in the backlog to support backing up/restoring individual items by name. Closing this issue out.
