### ISSUE TITLE
Confusing log fields when backing up additional items for an object

### ISSUE THREAD

**Issue by prydonius** [heptio/velero#1844]
When testing #1843, I noticed that the logger in the itemBackupper has the `resource` field preset from the resourceBackupper. If an item in a resource pulls in any additional items (e.g. a Pod's PVC or PV), the resource field continues to reflect the current resource (e.g. "pods" rather than "persistentvolumeclaims").

![Screenshot 2019-09-04 at 2 45 52 PM](https://user-images.githubusercontent.com/1544861/64296058-dbcf9780-cf27-11e9-8b13-2bc6c20e5bbd.png)

We should set the resource field using the groupResource passed into `backupItem` to ensure we're not confusingly displaying the wrong resource for the item.

We might also want to display the resource we're going through in a different field to make it more clear what resource pulled in an additional item, but I can't think of a good name for this field. Also, the logs around the additional item already help to indicate what the original resource/item is.

**Comment by spiffcs** [comment]
I'd love to pick up this issue to help you guys out!

Just for my own education, I don't think `groupResource` ever takes a new value between when it's declared and when `backupItem` could act on it.
https://github.com/heptio/velero/blob/5e22f9c1c87192b2cf23454a41aa4181d4f96ddb/pkg/backup/resource_backupper.go#L110

Doesn't this mean that if we use the `groupResource` passed into `backupItem` then the field would still be unchanged from before?

If you want to get the `Resource` of the `obj` that's being passed and account for the case listed in the issue, I think the best thing to do might be to `meta.TypeAccessor(obj)` at the top of `backupItem`.

**Comment by spiffcs** [comment]
PR added: https://github.com/heptio/velero/pull/1904
