### ISSUE TITLE
restore fails

### ISSUE THREAD

**Issue by vkrishr** [heptio/velero#1845]
Hi New to this backup have issue on restore, 

Want to know my pvc backup completed sucessfully or not and why restore fails 

I created a mongodb pod with pvc running once backup executed deleted some files in mongodb pvc and try to restore in same pod please advice were its failing

I have't configure restic 

1, Executed "velero describe backup pvc-backup" Snapshot PVs:  true but Persistent Volumes: <none included> ?

hostname:~# velero version
Client:
        Version: v1.0.0
        Git commit: 72f5cadc3a865019ab9dc043d4952c9bfd5f2ecb
Server:
        Version: v1.0.0

Steps followed for backup 
--------------------------

1, kubectl -n velero-backup-test annotate pod/mongodb-appops-ibm-mongodb-dev-575b49dcdc-9wh69 backup.velero.io/backup-volumes=mongodb-mongodb-ibm-appops-pvc --overwrite

2, velero create backup pvc-backup --selector release=mongodb-appops-ibm-mongodb-dev-575b49dcdc-9wh69 --snapshot-volumes=true

hostname:~# velero backup get
NAME         STATUS      CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
pvc-backup   Completed   2019-09-04 17:18:01 +0530 IST   29d       default            release=mongodb-appops-ibm-mongodb-dev-575b49dcdc-9wh69

hostname:~# velero describe backup pvc-backup
Name:         pvc-backup
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  <none>

Phase:  Completed

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  release=mongodb-appops-ibm-mongodb-dev-575b49dcdc-9wh69

Storage Location:  default

Snapshot PVs:  true

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2019-09-04 17:18:01 +0530 IST
Completed:  2019-09-04 17:18:08 +0530 IST

Expiration:  2019-10-04 17:18:01 +0530 IST

Persistent Volumes: <none included>

----------------------------------------------------------------------------------------------------------------------

Steps for restore

1, velero restore create --from-backup pvc-backup --restore-volumes=true

hostname:~# velero restore get
NAME                        BACKUP       STATUS            WARNINGS   ERRORS   CREATED                         SELECTOR
pvc-backup-20190904180916   pvc-backup   PartiallyFailed   0          1        2019-09-04 18:09:17 +0530 IST   <none>

hostname:~# velero describe restore pvc-backup-20190904180916
Name:         pvc-backup-20190904180916
Namespace:    velero
Labels:       <none>
Annotations:  <none>

Phase:  PartiallyFailed (run 'velero restore logs pvc-backup-20190904180916' for more information)

Errors:
  Velero:   backup does not contain top level resources directory
  Cluster:    <none>
  Namespaces: <none>

Backup:  pvc-backup

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        nodes, events, events.events.k8s.io, backups.velero.io, restores.velero.io, resticrepositories.velero.io
  Cluster-scoped:  auto

Namespace mappings:  <none>

Label selector:  <none>

Restore PVs:  true

hostname:~# velero restore logs pvc-backup-20190904180916
time="2019-09-04T12:39:18Z" level=info msg="starting restore" logSource="pkg/controller/restore_controller.go:440" restore=velero/pvc-backup-20190904180916
time="2019-09-04T12:39:18Z" level=info msg="Not including resource" groupResource=nodes logSource="pkg/restore/restore.go:128" restore=velero/pvc-backup-20190904180916
time="2019-09-04T12:39:18Z" level=info msg="Not including resource" groupResource=events logSource="pkg/restore/restore.go:128" restore=velero/pvc-backup-20190904180916
time="2019-09-04T12:39:18Z" level=info msg="Not including resource" groupResource=events.events.k8s.io logSource="pkg/restore/restore.go:128" restore=velero/pvc-backup-20190904180916
time="2019-09-04T12:39:18Z" level=info msg="Not including resource" groupResource=resticrepositories.velero.io logSource="pkg/restore/restore.go:128" restore=velero/pvc-backup-20190904180916
time="2019-09-04T12:39:18Z" level=info msg="Not including resource" groupResource=restores.velero.io logSource="pkg/restore/restore.go:128" restore=velero/pvc-backup-20190904180916
time="2019-09-04T12:39:18Z" level=info msg="Not including resource" groupResource=backups.velero.io logSource="pkg/restore/restore.go:128" restore=velero/pvc-backup-20190904180916
time="2019-09-04T12:39:18Z" level=info msg="Starting restore of backup velero/pvc-backup" logSource="pkg/restore/restore.go:364" restore=velero/pvc-backup-20190904180916
time="2019-09-04T12:39:18Z" level=info msg="restore completed" logSource="pkg/controller/restore_controller.go:442" restore=velero/pvc-backup-20190904180916
hostname:~#

**Comment by skriss** [comment]
@vkrishr it doesn't look like you have snapshots for your PVs -- you likely need to configure restic (see https://velero.io/docs/v1.1.0/restic/). Also, to do a restore, you'll need to first delete the app (i.e. the deployment), as Velero won't overwrite existing resources in the cluster.

**Comment by vkrishr** [comment]
Thanks Skriss, l will configure restic and delete mongodb and redeploy

**Comment by vkrishr** [comment]
Hi Skriss, have tried but still, no luck can you pls advice 

Reinstalled the velero with restic as below, redeployed the mongodb but still pvc is not backup 
-------------------------------------------------------------------------------------------------
velero install --provider aws --bucket appops-backup --secret-file ./minio.credentials --backup-location-config region=minio,s3ForcePathStyle="true",s3Url=http://9.193.199.45:32252 --use-restic --wait

kubectl -n velero-backup-test annotate pod/mongodb-app-ibm-mongodb-dev-b9bb86f56-qqfr4 backup.velero.io/backup-volumes=mongodb-mongodb-ibm-appops-pvc-new


velero create backup devtest-mongodb --selector release=mongodb-app-ibm-mongodb-dev-b9bb86f56-qqfr4 --snapshot-volumes=true


hostname:~# kubectl get pod -n velero
NAME                     READY   STATUS    RESTARTS   AGE
minio-6db48c5f4d-vb9f5   1/1     Running   0          14d
restic-8fc5p             1/1     Running   0          3h35m
restic-9hdxr             1/1     Running   0          3h35m
restic-gwfg9             1/1     Running   0          3h35m
velero-db6459bb-9cbfb    1/1     Running   0          3h35m
hostname:~#

hostname:~# kubectl get pod -n velero-backup-test
NAME                                          READY   STATUS    RESTARTS   AGE
mongodb-app-ibm-mongodb-dev-b9bb86f56-qqfr4   1/1     Running   0          140m
hostname:~# kubectl get pvc -n velero-backup-test
NAME                                 STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
mongodb-mongodb-ibm-appops-pvc-new   Bound    pvc-c92d61ad-d0ab-11e9-8dc5-005056bf5e2a   2Gi        RWO            glusterfs      3h12m
hostname:~# kubectl describe pod mongodb-app-ibm-mongodb-dev-b9bb86f56-qqfr4 -n velero-backup-test
Name:               mongodb-app-ibm-mongodb-dev-b9bb86f56-qqfr4
Namespace:          velero-backup-test
Priority:           0
PriorityClassName:  <none>
Node:               9.193.199.40/9.193.199.40
Start Time:         Fri, 06 Sep 2019 20:02:01 +0530
Labels:             app=mongodb-app-ibm-mongodb-dev
                    chart=ibm-mongodb-dev
                    heritage=Tiller
                    pod-template-hash=b9bb86f56
                    release=mongodb-app
Annotations:        backup.velero.io/backup-volumes: mongodb-mongodb-ibm-appops-pvc-new
                    kubernetes.io/psp: ibm-anyuid-hostpath-psp
                    productID:
                    productName: MongoDB
                    productVersion: 3.6.0
Status:             Running
IP:                 10.1.28.2
Controlled By:      ReplicaSet/mongodb-app-ibm-mongodb-dev-b9bb86f56
Containers:
  mongodb-app-ibm-mongodb-dev:
    Container ID:   docker://51a0c2cfbb2a326c71a1e8dc98073043646ae9c31cd25939d248e2c82df17838
    Image:          ibmcom/mongodb:3.6.0
    Image ID:       docker-pullable://ibmcom/mongodb@sha256:e9e6d153d05c2500922d1c159fdf11303e3cc4d0eda66fbea5d832883f383d87
    Port:           27017/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Fri, 06 Sep 2019 20:02:03 +0530
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  4Gi
    Requests:
      cpu:      100m
      memory:   256Mi
    Liveness:   exec [mongo --eval db.adminCommand('ping')] delay=180s timeout=5s period=10s #success=1 #failure=3
    Readiness:  exec [mongo --eval db.adminCommand('ping')] delay=180s timeout=1s period=10s #success=1 #failure=3
    Environment:
      LICENSE:           accept
      MONGODB_USERNAME:  mongo
      MONGODB_PASSWORD:  <set to the key 'password' in secret 'mongodb-app-ibm-mongodb-dev'>  Optional: false
      MONGODB_DATABASE:  admin
    Mounts:
      /data/db from mongodb-app-ibm-mongodb-dev-datavolume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-6g7p4 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  mongodb-app-ibm-mongodb-dev-datavolume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  mongodb-mongodb-ibm-appops-pvc-new
    ReadOnly:   false
  default-token-6g7p4:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-6g7p4
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
hostname:~# velero backup get
NAME              STATUS      CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
devtest-mongodb   Completed   2019-09-06 20:20:58 +0530 IST   29d       default            release=mongodb-app-ibm-mongodb-dev-b9bb86f56-qqfr4
hostname:~# velero describe backup devtest-mongodb
Name:         devtest-mongodb
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  <none>

Phase:  Completed

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  release=mongodb-app-ibm-mongodb-dev-b9bb86f56-qqfr4

Storage Location:  default

Snapshot PVs:  true

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2019-09-06 20:20:58 +0530 IST
Completed:  2019-09-06 20:21:04 +0530 IST

Expiration:  2019-10-06 20:20:58 +0530 IST

Persistent Volumes: <none included>
hostname:~#

**Comment by skriss** [comment]
Can you show the output of `kubectl -n velero-backup-test describe pod mongodb-app-ibm-mongodb-dev-b9bb86f56-qqfr4`?

Also, you don't need the `--snapshot-volumes` flag on `velero backup create` - I don't think it should be causing an issue, but please drop it from the command just to be sure.

**Comment by vkrishr** [comment]
hostname:~# kubectl -n velero-backup-test describe pod mongodb-app-ibm-mongodb-dev-b9bb86f56-5w9d2
Name:               mongodb-app-ibm-mongodb-dev-b9bb86f56-5w9d2
Namespace:          velero-backup-test
Priority:           0
PriorityClassName:  <none>
Node:               9.193.199.39/9.193.199.39
Start Time:         Sat, 07 Sep 2019 23:52:08 +0530
Labels:             app=mongodb-app-ibm-mongodb-dev
                    chart=ibm-mongodb-dev
                    heritage=Tiller
                    pod-template-hash=b9bb86f56
                    release=mongodb-app
Annotations:        kubernetes.io/psp: ibm-anyuid-hostpath-psp
                    productID:
                    productName: MongoDB
                    productVersion: 3.6.0
Status:             Running
IP:                 10.1.192.137
Controlled By:      ReplicaSet/mongodb-app-ibm-mongodb-dev-b9bb86f56
Containers:
  mongodb-app-ibm-mongodb-dev:
    Container ID:   docker://9113a7fec5273e1b2edb3a1a2101b94b05dfcc48f2640a7bd3384c6f163fa877
    Image:          ibmcom/mongodb:3.6.0
    Image ID:       docker-pullable://ibmcom/mongodb@sha256:e9e6d153d05c2500922d1c159fdf11303e3cc4d0eda66fbea5d832883f383d87
    Port:           27017/TCP
    Host Port:      0/TCP
    State:          Running
      Started:      Sat, 07 Sep 2019 23:53:31 +0530
    Last State:     Terminated
      Reason:       Error
      Exit Code:    100
      Started:      Sat, 07 Sep 2019 23:53:10 +0530
      Finished:     Sat, 07 Sep 2019 23:53:10 +0530
    Ready:          True
    Restart Count:  3
    Limits:
      cpu:     2
      memory:  4Gi
    Requests:
      cpu:      100m
      memory:   256Mi
    Liveness:   exec [mongo --eval db.adminCommand('ping')] delay=180s timeout=5s period=10s #success=1 #failure=3
    Readiness:  exec [mongo --eval db.adminCommand('ping')] delay=180s timeout=1s period=10s #success=1 #failure=3
    Environment:
      LICENSE:           accept
      MONGODB_USERNAME:  mongo
      MONGODB_PASSWORD:  <set to the key 'password' in secret 'mongodb-app-ibm-mongodb-dev'>  Optional: false
      MONGODB_DATABASE:  admin
    Mounts:
      /data/db from mongodb-app-ibm-mongodb-dev-datavolume (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-6g7p4 (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  mongodb-app-ibm-mongodb-dev-datavolume:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  mongodb-mongodb-ibm-appops-pvc-new
    ReadOnly:   false
  default-token-6g7p4:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-6g7p4
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>

**Comment by skriss** [comment]
@vkrishr I don't see the Velero restic annotation on your pod. You need to do something like the following:

`kubectl -n velero-backup-test annotate po/mongodb-app-ibm-mongodb-dev-b9bb86f56-5w9d2 backup.velero.io/backup-volumes=mongodb-app-ibm-mongodb-dev-datavolume`

Once you do that, you should be able to get restic backups.

**Comment by vkrishr** [comment]
@skriss Found what is the issue 
 have used --selector =pvc name hence failed to take volume backup
Now corrected with as below 
velero create backup new-deployment-mongo  --selector app=mongodb-app-ibm-mongodb-dev
hostname:~# velero backup describe new-deployment-mongo
Name:         new-deployment-mongo
Namespace:    velero
Labels:       velero.io/storage-location=default
Annotations:  <none>

Phase:  Completed

Namespaces:
  Included:  *
  Excluded:  <none>

Resources:
  Included:        *
  Excluded:        <none>
  Cluster-scoped:  auto

Label selector:  app=mongodb-app-ibm-mongodb-dev

Storage Location:  default

Snapshot PVs:  auto

TTL:  720h0m0s

Hooks:  <none>

Backup Format Version:  1

Started:    2019-09-10 15:42:16 +0530 IST
Completed:  2019-09-10 15:45:44 +0530 IST

Expiration:  2019-10-10 15:42:16 +0530 IST

Persistent Volumes: <none included>

Restic Backups (specify --details for more information):
  Completed:  1

**Comment by skriss** [comment]
OK great - looks like you were able to get the restic backup taken! I'm going to close this issue, but feel free to reach out again as needed.
