### ISSUE TITLE
CSS / display issue

### ISSUE THREAD

**Issue by johnharris85** [heptio/velero#1848]
**What steps did you take and what happened:**
Visit [Velero AWS configuration docs](https://velero.io/docs/v1.1.0/api-types/backupstoragelocation/#aws) and saw that some config option tables aren't formatted properly.

**What did you expect to happen:**
Proper tables displayed

**The output of the following commands will help us better understand what's going on**:
![velero-paremeters](https://user-images.githubusercontent.com/746221/64353332-6fe64100-cfb2-11e9-826c-b884c6d390c2.png)

**Anything else you would like to add:**
N/A

**Environment:**
N/A

**Comment by skriss** [comment]
closed by #1865
