### ISSUE TITLE
Is it possible to browse the content of velero restic backups?

### ISSUE THREAD

**Issue by Marki4711** [heptio/velero#1855]
Hello,

I really love this project and it works extremey well for us. What I miss (or just don't know how to do it) is a way to browse the contenct of existing restic-backups that were made by velero. Restic on its own provides a very comfortable way to do it, but I don't know if this is also possible for the restic-backups that were made by velero. If this is possible, please give me a hint about the procedure to achieve it.

BR,
Matthias

**Comment by prydonius** [comment]
Hey @Marki4711, thanks for the feedback, I'm glad Velero is working out well for you!

It is possible to connect directly to the restic repository and access it using the restic CLI. You can run `velero restic repo get -o yaml` to get the repository repository address (see the `resticIdentifier`). This can be passed to `restic` with the `RESTIC_REPOSITORY` env var or the `-r` flag.

To get the password, look at the Secret in the velero namespace: `kubectl get secrets -n velero -o yaml velero-restic-credentials`. The base64 decoded value of `repository-password` is the password and can be given to `restic` using the `RESTIC_PASSWORD` env var (or when prompted in the CLI).

Depending on the storage backend, you may also need to provide credentials (see the restic docs for this https://restic.readthedocs.io/en/stable/030_preparing_a_new_repo.html#amazon-s3).

Let me know if this helps!

**Comment by Marki4711** [comment]
Wow, it works like a charm. This is just a really cool solution.

It took me some time that the restic-client just hangs without any message, if the environment-variables for the AWS credentials are not configured.

Big thanks,
Matthias

**Comment by prydonius** [comment]
Glad that worked for you, I think we can close this out, but feel free to reopen or create a new issue if you have any other questions/issues!
