### ISSUE TITLE
Restic repo maintenance is not running for one Repo 

### ISSUE THREAD

**Issue by adityagu0910** [heptio/velero#1857]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)
I see restic repo maintenance is running but it is not updating time stamp for one of the repo and because of this it tries to run again and schedule backup fails. 
in logs it gives - No ready channel found for repository

Last restic repo maintenance log for restic repo that is failing for maintenance  from velero logs(debug was enabled)

time="2019-09-09T13:43:01Z" level=debug msg="Running processQueueItem" controller=restic-repository key=velero/kube-system-default-xjl9n logSource="pkg/co
ntroller/restic_repository_controller.go:102"
time="2019-09-09T13:43:01Z" level=debug msg="Checking repository for stale locks" controller=restic-repository logSource="pkg/controller/restic_repository
_controller.go:131" name=kube-system-default-xjl9n namespace=velero
time="2019-09-09T13:43:02Z" level=debug msg="Ran restic command" command="restic unlock --repo=s3:http://MYIP:12401/gc-icp-dev-backup/restic/kube-
system --password-file=/tmp/velero-restic-credentials-kube-system377844178 --cache-dir=/scratch/.cache/restic" logSource="pkg/restic/repository_manager.go
:276" repository=kube-system stderr= stdout="successfully removed locks\n"
time="2019-09-09T13:43:02Z" level=debug msg=resticRepositoryController.runMaintenanceIfDue controller=restic-repository logSource="pkg/controller/restic_r
epository_controller.go:196" name=kube-system-default-xjl9n namespace=velero
time="2019-09-09T13:43:02Z" level=info msg="Running maintenance on restic repository" controller=restic-repository logSource="pkg/controller/restic_reposi
tory_controller.go:205" name=kube-system-default-xjl9n namespace=velero
time="2019-09-09T13:43:02Z" level=debug msg="Checking repo before prune" controller=restic-repository logSource="pkg/controller/restic_repository_controll
er.go:207" name=kube-system-default-xjl9n namespace=velero
time="2019-09-09T13:43:05Z" level=debug msg="Ran restic command" command="restic check --repo=s3:http://MYIP:12401/gc-icp-dev-backup/restic/kube-s
ystem --password-file=/tmp/velero-restic-credentials-kube-system227301129 --cache-dir=/scratch/.cache/restic" logSource="pkg/restic/repository_manager.go:
276" repository=kube-system stderr= stdout="using temporary cache in /scratch/.cache/restic/restic-check-cache-565950402\ncreated new cache in /scratch/.c
ache/restic/restic-check-cache-565950402\ncreate exclusive lock for repository\nload indexes\n"
time="2019-09-09T13:43:05Z" level=debug msg="Running processQueueItem" controller=restic-repository key=velero/services-default-wh8m9 logSource="pkg/contr
oller/restic_repository_controller.go:102"
time="2019-09-09T13:43:05Z" level=debug msg="Checking repository for stale locks" controller=restic-repository logSource="pkg/controller/restic_repository_controller.go:131" name=services-default-wh8m9 namespace=velero
time="2019-09-09T13:43:05Z" level=debug msg="**No ready channel found for repository** velero/kube-system-default-xjl9n" logSource="pkg/restic/repository_ensurer.go:89"

[root@opcgg008400002 ~]# velero restic repo get
NAME                               STATUS   LAST MAINTENANCE
**kube-system-default-xjl9n**          Ready    **_2019-09-06 14:40:17 -0400 EDT_**
lrc-mnrf-fsims-dev-default-lxp74   Ready    2019-09-08 13:48:03 -0400 EDT
services-default-wh8m9             Ready    2019-09-08 16:43:04 -0400 EDT

**What did you expect to happen:**
Restic Repo Maintenance should update the time and if it fails then should show error in logs.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
* `velero backup logs <backupname>`
* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
* `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
velero version
Client:
        Version: v1.1.0
        Git commit: a357f21aec6b39a8244dd23e469cc4519f1fe608
Server:
        Version: v1.1.0
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by adityagu0910** [comment]
I see below error.  

time="2019-09-09T14:23:04Z" level=debug msg="Ran restic command" command="restic check --repo=s3:http://IP:12401/gc-icp-dev-backup/restic/kube-s
ystem --password-file=/tmp/velero-restic-credentials-kube-system429682729 --cache-dir=/scratch/.cache/restic" logSource="pkg/restic/repository_manager.go:
276" repository=kube-system stderr="Load(<index/bcdfe96761>, 0, 0) returned error, retrying after 749.334338ms: Copy: write /scratch/.cache/restic/restic-
check-cache-606715968/b51f26aabbb9d7dc20100cf915842a8fb360b265f7c00b71ec0f2047bcc0090d/index/bc/bcdfe967615928a65b89923ff4a080094468c276a1f16d697f2d16963a
faf9b8: **cannot allocate memory**\n" stdout="using temporary cache in /scratch/.cache/restic/restic-check-cache-606715968\ncreated new cache in /scratch/.cac
he/restic/restic-check-cache-606715968\ncreate exclusive lock for repository\nload indexes\n"

**Comment by adityagu0910** [comment]
I recreated restic repos again and will monitor for few days and report if I see any issue with restic repo maintenance. 
Thanks !

**Comment by prydonius** [comment]
Thanks @adityagu0910, do you have any resource requests/limits on the velero pod? They might need to be increased.

**Comment by adityagu0910** [comment]
Actually I did not set anything and kept default values 
I see below from my pod spec 
    Limits:
      cpu:     1
      memory:  256Mi

Today again maintenance was completed for other repositories but did not complete for kube-system repository
NAME                               STATUS     LAST MAINTENANCE
kube-system-default-zlcq8          NotReady   **2019-09-09 11:59:18** -0400 EDT
lrc-mnrf-fsims-dev-default-24ng6   Ready      2019-09-10 11:59:55 -0400 EDT
services-default-mvpt4             Ready      2019-09-10 11:59:58 -0400 EDT

I am attaching complete logs for velero pod . I am not able to see any specific error that shows why it did not complete for kube-system restic repo. 
[velero.log](https://github.com/heptio/velero/files/3597450/velero.log)

**Comment by skriss** [comment]
It looks like something is going wrong when `restic check` is being run against that repository during maintenance. Compare the output for the kube-system repo to one of the others:

`time="2019-09-10T16:19:59Z" level=debug msg="Ran restic command" command="restic check --repo=s3:http://MYIP:MYPORT/gc-icp-dev-backup/restic/kube-system --password-file=/tmp/velero-restic-credentials-kube-system760563073 --cache-dir=/scratch/.cache/restic" logSource="pkg/restic/repository_manager.go:276" repository=kube-system stderr= stdout="using temporary cache in /scratch/.cache/restic/restic-check-cache-882795557\ncreated new cache in /scratch/.cache/restic/restic-check-cache-882795557\ncreate exclusive lock for repository\nload indexes\n"`

vs. 

`time="2019-09-10T15:59:56Z" level=debug msg="Ran restic command" command="restic check --repo=s3:http://MYIP:MYPORT/gc-icp-dev-backup/restic/lrc-mnrf-fsims-dev --password-file=/tmp/velero-restic-credentials-lrc-mnrf-fsims-dev088299561 --cache-dir=/scratch/.cache/restic" logSource="pkg/restic/repository_manager.go:276" repository=lrc-mnrf-fsims-dev stderr= stdout="using temporary cache in /scratch/.cache/restic/restic-check-cache-322716012\ncreated new cache in /scratch/.cache/restic/restic-check-cache-322716012\ncreate exclusive lock for repository\nload indexes\ncheck all packs\ncheck snapshots, trees and blobs\nno errors were found\n"`

If possible, it would definitely be interesting to see what happens if you run `restic check` manually against that repo. I can provide more detail on exactly how to do that if needed.

**Comment by adityagu0910** [comment]
Yes please give me the way to run restic check manually. I will try.

I also see below restic snapshot is running for this repository while i do not find restic snapshot command  for other repositories 

> time="2019-09-10T20:04:57Z" level=debug msg="Ran restic command" command="restic snapshots --repo=s3:http://MYIP5:MYPORT/gc-icp-dev-backup/restic/kube-system --password-file=/tmp/velero-restic-credentials-kube-system795752821 --cache-dir=/scratch/.cache/restic --last" logSource="pkg/restic/repository_manager.go:276" repository=kube-system stderr= stdout="ID        Time                 Host        Tags                                                                                                                                                                                                         Paths\n------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n60a75d93  2019-09-09 16:47:05  velero      backup=whole-cluster-backup-09092019124322,backup-uid=57414ac6-d321-11e9-bf48-0050568abba1,ns=kube-system,pod=logging-elk-data-0,pod-uid=30c5a170-b277-11e9-9dac-0050568abba1,volume=data                    /host_pods/30c5a170-b277-11e9-9dac-0050568abba1/volumes/kubernetes.io~local-volume/logging-datanode-MYIP1\n6c0a66d7  2019-09-10 14:18:13  velero      backup=whole-cluster-backup-10092019101601,backup-uid=d29142ec-d3d5-11e9-bf48-0050568abba1,ns=kube-system,pod=icp-mongodb-0,pod-uid=b4b8e374-b276-11e9-9dac-0050568abba1,volume=mongodbdir                   /host_pods/b4b8e374-b276-11e9-9dac-0050568abba1/volumes/kubernetes.io~local-volume/mongodb-MYIP0\n5b853d27  2019-09-10 14:18:35  velero      backup=whole-cluster-backup-10092019101601,backup-uid=d29142ec-d3d5-11e9-bf48-0050568abba1,ns=kube-system,pod=image-manager-0,pod-uid=e3346b00-c2f6-11e9-a26e-0050568abba1,volume=image-manager              /host_pods/e3346b00-c2f6-11e9-a26e-0050568abba1/volumes/kubernetes.io~local-volume/image-manager-MYIP0\neb49e933  2019-09-10 14:18:59  velero      pod-uid=cb6ce276-b493-11e9-bbe0-0050568abba1,volume=datadir,backup=whole-cluster-backup-10092019101601,backup-uid=d29142ec-d3d5-11e9-bf48-0050568abba1,ns=kube-system,pod=vulnerability-advisor-minio-0      /host_pods/cb6ce276-b493-11e9-bbe0-0050568abba1/volumes/kubernetes.io~local-volume/minio-MYIP9\neaab5cf5  2019-09-10 14:24:12  velero      pod-uid=cb639435-b493-11e9-bbe0-0050568abba1,volume=datadir,backup=whole-cluster-backup-10092019101601,backup-uid=d29142ec-d3d5-11e9-bf48-0050568abba1,ns=kube-system,pod=vulnerability-advisor-zookeeper-0  /host_pods/cb639435-b493-11e9-bbe0-0050568abba1/volumes/kubernetes.io~local-volume/zookeeper-MYIP9\n------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------\n5 snapshots\n"
time="2019-09-10T20:04:57Z" level=debug msg="No ready channel found for repository velero/kube-system-default-zlcq8" logSource="pkg/restic/repository_ensurer.go:89"

**Comment by skriss** [comment]
OK, so you'll need to do the following:

1. Have credentials locally to access your object storage bucket (you could copy the ones in the `cloud-credentials` secret into your local environment)
2. Get the restic repo identifier from the custom resource: look for the `repoIdentifier` field in `velero restic repo get kube-system-default-zlcq8 -o yaml`

Then, you'll want to run `restic check -r <repo identifier>`, using a password of `static-passw0rd` when prompted (yes, this is the password; we rely on your object storage IAM for protecting the data).

**Comment by adityagu0910** [comment]
Thanks Steve 

It is getting killed after index load 

> $ restic check -r s3:http://MYURL/gc-icp-dev-backup/restic/kube-system -v
using temporary cache in /tmp/restic-check-cache-087909954
enter password for repository: 
repository 29022249 opened successfully, password is correct
created new cache in /tmp/restic-check-cache-087909954
create exclusive lock for repository
load indexes
**_Killed_**
$

**Comment by adityagu0910** [comment]
do we have any way to enable log and see why it is getting killed ?
I tried with flag 
> `-vvvvvvvvv`
But it is not showing any extra logs

**Comment by adityagu0910** [comment]
when i am running same command inside restic pod, it is working fine.
only failing from velero pod . Could it be some permission issue for velero pod ?

> restic check -r s3:http://MYURL/gc-icp-dev-backup/restic/kube-system -vvvvvvvvv
using temporary cache in /tmp/restic-check-cache-469937870
enter password for repository: 
repository 29022249 opened successfully, password is correct
created new cache in /tmp/restic-check-cache-469937870
create exclusive lock for repository
load indexes
check all packs
check snapshots, trees and blobs
no errors were found

**Comment by skriss** [comment]
Could you try increasing the memory limit on the pod? That seems like a likely culprit at this point.

**Comment by adityagu0910** [comment]
It worked with 2Gi limit and request both.
Did not work with 1Gi 

Thanks Steve !!

**Comment by skriss** [comment]
OK great! Good to know for the future. I'll close this issue out but feel free to reach out again as needed.
