### ISSUE TITLE
[doc] Diagram (image) still mentions ark

### ISSUE THREAD

**Issue by Ilyes512** [heptio/velero#1876]
On this page: https://velero.io/docs/v1.1.0/about/ the fallowing image: https://velero.io/docs/v1.1.0/img/backup-process.png still mentions `ark`. This should be `velero`.

Also see https://github.com/heptio/velero/issues/980#issuecomment-531568044

**Comment by keramiozsoy** [comment]
Hi, I resolved and send issue 👍  #1877
