### ISSUE TITLE
Velero not deleting Snapshots associated with backup after Backup Expiry

### ISSUE THREAD

**Issue by puneethpk** [heptio/velero#1880]
**What steps did you take and what happened:**
velero schedule create default-ns --schedule="@every 5m" --include-namespaces default --snapshot-volumes --ttl '2m'"

**What did you expect to happen:**
`velero get backup`

NAME                              STATUS      CREATED                         EXPIRES   STORAGE LOCATION   SELECTOR
default-ns-20190917052933         Completed   2019-09-17 05:29:33 +0000 UTC   3m ago    default            <none>        <none>
default-ns-testing-20190917053231   Completed   2019-09-17 05:32:31 +0000 UTC   4s ago    default            <none>

**The output of the following commands will help us better understand what's going on**:

The Expires Column shows that the backup has been expired 3m ago but the backup is not getting deleted as well as the snapshots.Nothing has been recorded in the logs of 
 `kubectl logs deployment/velero -n velero`
related to deleting the expired backups.

**Anything else you would like to add:**
I had tried the same using heptio-ark and had the same issues.
Adding the AWS_CLUSTER name as ENV in ark-deployment.yaml fixed the issue.
I tried the same by modifying velero deployment using.

`kubectl -n velero edit deploy velero` and added AWS_CLUSTER name as ENV
but its not working.

**Environment:**

- Velero version (use `velero version`): 
 velero version
 Client:
        Version: v1.0.0
        Git commit: 72f5cadc3a865019ab9dc043d4952c9bfd5f2ecb
 Server:
        Version: v1.0.0
- Kubernetes version :
  Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T21:04:45Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.10", GitCommit:"37d169313237cb4ceb2cc4bef300f2ae3053c1a2", GitTreeState:"clean", BuildDate:"2019-08-19T10:44:49Z", GoVersion:"go1.11.13", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes installer & version: v1.13.10
- Cloud provider or hardware configuration: AWS

**Comment by skriss** [comment]
@puneethpk the GC controller, which is responsible for triggering deletions of expired backups, only runs every 60 minutes. Can you wait for at least that long and see if your backups are deleted?

**Comment by skriss** [comment]
Resolved per slack!

**Comment by xtrc** [comment]
I'm experiencing the exact same issue but on Azure. What was the solution?

**Comment by skriss** [comment]
@xtrc what does `velero backup describe BACKUP_NAME --details` show? also, is there anything in the velero server logs (`kubectl -n velero logs deploy/velero`) that indicates an error?
