### ISSUE TITLE
Error while installing velero on openshift cluster

### ISSUE THREAD

**Issue by ashoks27** [heptio/velero#1911]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

Velero installation on openshift installation got the below error.  We have configured the cluster behind the corporate proxy.  Is there any specific proxy which we need to execute while deploying the velero on openshift.

# kubectl logs deployment/velero -n velero
An error occurred: some backup storage locations are invalid: backup store for location "default" is invalid: rpc error: code = Unknown desc = Get https://www.googleapis.com/storage/v1/b/mybucket-sep/o?alt=json&delimiter=%!F(MISSING)&pageToken=&prefix=&prettyPrint=false&projection=full&versions=false: oauth2: cannot fetch token: Post https://oauth2.googleapis.com/token: dial tcp 216.58.204.42:443: i/o timeout

**What did you expect to happen:**

An error less installation of velero
**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`

time="2019-09-26T13:35:22Z" level=info msg="setting log-level to INFO"
time="2019-09-26T13:35:22Z" level=info msg="Starting Velero server v1.0.0 (72f5cadc3a865019ab9dc043d4952c9bfd5f2ecb)" logSource="pkg/cmd/server/server.go:165"
time="2019-09-26T13:35:22Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
time="2019-09-26T13:35:22Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pv
time="2019-09-26T13:35:22Z" level=info msg="registering plugin" command=/velero kind=BackupItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/serviceaccount
time="2019-09-26T13:35:22Z" level=info msg="registering plugin" command=/velero kind=VolumeSnapshotter logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/aws
time="2019-09-26T13:35:22Z" level=info msg="registering plugin" command=/velero kind=VolumeSnapshotter logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/azure
time="2019-09-26T13:35:22Z" level=info msg="registering plugin" command=/velero kind=VolumeSnapshotter logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/gcp
time="2019-09-26T13:35:22Z" level=info msg="registering plugin" command=/velero kind=ObjectStore logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/aws
time="2019-09-26T13:35:22Z" level=info msg="registering plugin" command=/velero kind=ObjectStore logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/azure
time="2019-09-26T13:35:22Z" level=info msg="registering plugin" command=/velero kind=ObjectStore logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/gcp
time="2019-09-26T13:35:22Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/addPVCFromPod
time="2019-09-26T13:35:22Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/addPVFromPVC
time="2019-09-26T13:35:22Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/job
time="2019-09-26T13:35:22Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/pod
time="2019-09-26T13:35:22Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/restic
time="2019-09-26T13:35:22Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/service
time="2019-09-26T13:35:22Z" level=info msg="registering plugin" command=/velero kind=RestoreItemAction logSource="pkg/plugin/clientmgmt/registry.go:100" name=velero.io/serviceaccount
time="2019-09-26T13:35:22Z" level=info msg="Checking existence of namespace" logSource="pkg/cmd/server/server.go:355" namespace=velero
time="2019-09-26T13:35:22Z" level=info msg="Namespace exists" logSource="pkg/cmd/server/server.go:361" namespace=velero
time="2019-09-26T13:35:25Z" level=info msg="Checking existence of Velero custom resource definitions" logSource="pkg/cmd/server/server.go:390"
time="2019-09-26T13:35:25Z" level=info msg="All Velero custom resource definitions exist" logSource="pkg/cmd/server/server.go:424"
time="2019-09-26T13:35:25Z" level=info msg="Checking that all backup storage locations are valid" logSource="pkg/cmd/server/server.go:431"
An error occurred: some backup storage locations are invalid: backup store for location "default" is invalid: rpc error: code = Unknown desc = Get https://www.googleapis.com/storage/v1/b/mybucket-sep/o?alt=json&delimiter=%!F(MISSING)&pageToken=&prefix=&prettyPrint=false&projection=full&versions=false: oauth2: cannot fetch token: Post https://oauth2.googleapis.com/token: dial tcp 216.58.204.42:443: i/o timeout

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`):  Velero version v1.0.0
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):
Redhat Linux 7.4

**Comment by nrb** [comment]
@ashoks27 That's a good question, and something we should definitely document.

Right now, most of the Velero docs and code assume that there's direct access to the cloud provider's endpoints.

Can you tell me a little bit more about your environment? What proxy is being used? Is its information exposed within the Kubernetes cluster?

It looks like the Google Cloud SDK [has support for proxies](https://cloud.google.com/sdk/docs/proxy-settings), but I will need to do more research to see exactly how we might configure it for Velero.

**Comment by nrb** [comment]
After some more research, I believe adding the `https_proxy` variable with the URL of your proxy to the deployment would work.

So something like the below in your deployment's YAML:

```yaml
[....]
      env:
      - name: VELERO_SCRATCH_DIR
          value: /scratch
        - name: VELERO_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: GOOGLE_APPLICATION_CREDENTIALS
          value: /credentials/cloud
        - name: AWS_SHARED_CREDENTIALS_FILE
          value: /credentials/cloud
        - name: AZURE_CREDENTIALS_FILE
          value: /credentials/cloud
        - name: https_proxy
          value: http://127.0.0.1:3128
[....]
```

**Comment by ashoks27** [comment]
Hi Nolan , 

Thanks for your response..

We are using the internal corporate proxy and yes openshift is configured behind proxy only. 

Also I have already tried to apply the proxy on the running deployment , but Velero deployments still failing with error.
**#oc set env deployment/velero  HTTP_PROXY=http://XXXXXX:3128/**

Now I have also tried as you mentioned above and it also didn't work . Herewith I  am attaching the yaml file which I have applied on the deployments and also the logs . Please have a look and advise further.



[velero_logs.txt](https://github.com/heptio/velero/files/3662385/velero_logs.txt)
[velero_pod.txt](https://github.com/heptio/velero/files/3662386/velero_pod.txt)

**Comment by nrb** [comment]
@ashoks27 Is port `3128` the correct port for your proxy server?

Do you have any other services running inside the cluster that use the proxy that you can reference?

Also, I'm curious, how is the Velero container image being downloaded if the cluster doesn't have access to the internet?

**Comment by ashoks27** [comment]
Hi Nolan ,

Yes.. 3128 is the correct port for our proxy server. 

Internet access is working fine with the base OS thru Proxy , but it seems its NOT propagated into OC cluster. I will try to fix this proxy issue and come back if I need any again help on Velero . thanks for your support.

**Comment by sacha-lin** [comment]
HI @ashoks27 

Did you find a way to setup the proxy  because I'm having same of issue

Thanks in advance

Sacha
