### ISSUE TITLE
Restore with namespace mapping is not working as expected 

### ISSUE THREAD

**Issue by adityagu0910** [heptio/velero#1915]
**What steps did you take and what happened:**
[A clear and concise description of what the bug is, and what commands you ran.)

I am taking a nightly full cluster backup (that includes all namespaces in my cluster ) and I want to restore only one namespace from it, into another namespace. 

I am using below command for it
`velero restore create restore-one-toanother-namespace-lrc-mnrf-fsims-dev --from-backup whole-cluster-backup-26092019112127 --include-namespaces lrc-mnrf-fsims-dev --namespace-mappings lrc-mnrf-fsims-dev:lrc-mnrf-fsims-dev-restore `

But it i snot doing anything and creating the lrc-mnrf-fsims-dev-restore without any resources so empty new namespace.
Could you please guide what i am giving wrong in command ?

**What did you expect to happen:**

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/velero -n velero`
* `velero backup describe <backupname>` or `kubectl get backup/<backupname> -n velero -o yaml`
* `velero backup logs <backupname>`
* `velero restore describe <restorename>` or `kubectl get restore/<restorename> -n velero -o yaml`
* `velero restore logs <restorename>`

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Velero version (use `velero version`): 
- Velero features (use `velero client config get features`): 
- Kubernetes version (use `kubectl version`):
- Kubernetes installer & version:
- Cloud provider or hardware configuration:
- OS (e.g. from `/etc/os-release`):

**Comment by skriss** [comment]
Sounds like a dupe of #1888 which we just merged a fix into master for.

**Comment by adityagu0910** [comment]
hmm thanks Steve!!!!
I will retest with latest image

**Comment by adityagu0910** [comment]
HI Steve 
if possible, when you get time, could you please push latest image with verified changes and share ?
Thanks!

**Comment by skriss** [comment]
You could try `gcr.io/heptio-images/velero:master` which has this fix along with all other changes we've made since v1.1.

**Comment by adityagu0910** [comment]
Okay Thanks

**Comment by adityagu0910** [comment]
It worked fine with this image. 
Thanks Steve !!

Closing this.

**Comment by adityagu0910** [comment]
Just for the info - 

with this master image, restic backup for type "LocalVolume" is not working and when request is sent to restic  by velero to backup the volume, restic daemon on that node is getting restarted. 

For now I am using master image in velero deployment and v1.1.0 image in restic daemonset. I hope it will not create any issue.
