### ISSUE TITLE
Git as a storage backend

### ISSUE THREAD

**Issue by bdimcheff** [heptio/velero#238]
I'd love to see git support in ark similar to https://github.com/pieterlange/kube-backup.  Generally, kubernetes is great at the _present_ state of the system, but I think ark could give us some very powerful cluster history inspection if paired with git.  Imagine that instead of creating a record in an object store, it'd commit changes to a git repo and push it to github.

Some use cases that could be handy:

* see an audit log of cluster changes in the same format as other software (eg. in github) irrespective of what tools people are using to create resources in the cluster and answer questions like: how many pods were running last thursday and what version were they?
* use `git bisect` to identify the change that created an issue in production
* diff staging and production clusters to see if they have diverged
* use git tools to pull out unwanted cluster changes and reapply the config

I would _absolutely love_ if this could run constantly by watching the API and writing out changes as they happen, but even a regular snapshot could be very useful.

This has been on my mind for a while as a potential standalone project, but it seems like it might fit well within ark.  I can try to take a crack at it if there's interest.  I also recognize this might be a bit of scope creep. ;)

Looking forward to hear your thoughts!

**Comment by ncdc** [comment]
Hi @bdimcheff, thanks for suggesting this! I think it's a very interesting idea. I'm not sure we're ready to try to do continuous watches, but I do think we could extract an interface to support custom backup persistence formats. Something along the lines of BackupStarted, PersistItem, BackupCompleted, RetrieveItem. Just some initial thoughts here, and more to come over the next few weeks once we decompress from KubeCon 😄.

cc @jbeda

**Comment by ncdc** [comment]
The current backup process looks like this:

1. A `Backup` resource is created
1. The `BackupController` in the `ark` pod sees the new `Backup`
1. The `BackupController` creates a temp file for the backup tarball
1. The `BackupController` tells its `backupper` (a `kubernetesBackupper` instance) to `Backup(backup *api.Backup, backupFile, logFile io.Writer, actions []ItemAction)`, passing in the backup tarball temp file (as an `io.Writer`)
1. The `kubernetesBackupper` does its thing, backing up everything into the backupFile `io.Writer`

Now for a few comments & questions:

If we do this, the `backupFile` in `Backup()` probably needs to become an `ItemPersister` interface (name TBD).

We're starting to think about the idea of a "backup target" as a CRD that represents where the backup tarball is stored. For example, perhaps you decide you want to store your backup in multiple s3 buckets (in different regions), or in both s3 and azure. I want to make sure we keep your idea in mind as we flesh out the backup target design.

Should setting the storage backend be per backup, or should it apply to all of ark (i.e. via the ark config)? How are backups differentiated in git storage?

Ark currently places the temp files for the backup tarball and the backup log file in the default temp dir (via `ioutil.TempFile("", "")`). This means `/tmp` inside the `ark` container, which currently is part of the container's file system. Regardless of tarball vs git, should we have a specific root dir we should use to place temp files, git repos, etc?

For git, does the target repo need to exist first - is the first ark operation a `git clone`?

When the backup is complete, I guess we do a `git commit` and a `git push`?

**Comment by bdimcheff** [comment]
I had a little fun with ark + git today.  

I installed the example nginx app from the ark repo and did a few backups in its [initial state](https://github.com/bdimcheff/ark-git-playground/commit/e89d83360f7630b8d18e796eb30b04bd0e63c3f8), after I manually [deleted a pod](https://github.com/bdimcheff/ark-git-playground/commit/8bc44849a4dcf25c773da80204eb39e84f78b825), and when I [scaled it](https://github.com/bdimcheff/ark-git-playground/commit/2b36a94ad4369b457f1d0ad8ff08994fa0991a0c) from 2-5 pods.  

* The diffs are reasonably readable.  Git treated my deletion of the pod and the subsequent automatic recreation as a rename, which is kinda funny, but I'm sure that rename detection can be suppressed.
* I thought the [endpoint response](https://github.com/bdimcheff/ark-git-playground/commit/2b36a94ad4369b457f1d0ad8ff08994fa0991a0c#diff-908a1879938667a6a95da860dceca00bR29) to scaling showed up pretty well in the diff.
* There's not as much noise as I thought there'd be, with the exception of `resourceVersion` which seems to [change sometimes](https://github.com/bdimcheff/ark-git-playground/commit/8bc44849a4dcf25c773da80204eb39e84f78b825#diff-eaa5f02e2869fe05037c5958a9481f17R16) even when nothing else in the resource does.

Also, I changed [this line](https://github.com/heptio/ark/blob/c129d1cec3ebc4610f28efb8336baa034e9d80f0/pkg/backup/item_backupper.go#L237) to call `json.MarshalIndent(obj.UnstructuredContent(), "", "\t")` because no linebreaks creates an excessive amount of noise in git.  This broke a lot of tests.  I didn't bother fixing them because I'm just messing around, but if that's a change you'd accept upstream I'm happy to make a real PR.  It'd probably be necessary to prettyprint the json for any text-based version control to be practical.

So anyhow I think the good news is that ark already produces output that is pretty close to being usable via git.  If there were hooks/interfaces at the right place, this sort of store should work.

I think the workflow would be:

1. `git fetch` to update a cached copy or `git clone` to start new (cache would be nice as history grows)
2. `git branch <backup name>`
3. remove everything in the local workdir (you need to get rid of deleted resources somehow)
4. do the backup
5. `git add .`
6. `git commit`
7. `git push`

There's probably some lower-level git commands that can be used to avoid doing so much stuff with the local filesystem.  You really just need the bare repo and then to commit the contents of the backup directly on top of it.  You never actually want the contents of the previous files when performing a backup

I think this is going to be a little tricky mapping backups to concepts in git.  As a human, I can figure out when backups are related and when one is logically related to a previous one.  When I manually created my git repo, I knew that "ark test 2" came after "ark test 1".  Ark wouldn't have that information normally, though.  At least scheduled backups should be easy, since they are the same dataset separated by time.  One-off backups are trickier, and I'm not sure how they would be reasonably represented in git. 

I'm still pretty excited about this, because I've wanted a user-readable log of changes in our cluster for a while.  Everyone's already used to git and various tools, so this would let people access that information without having to learn a whole bunch of new stuff.

Even if this doesn't end up as core functionality, I think interfaces in the appropriate places would be enough to build something small but useful.

**Comment by ncdc** [comment]
@bdimcheff neat! Thanks for the report. We're going to start discussing the design & concepts for backup targets soon. Would you be interested in helping with that?

**Comment by ncdc** [comment]
@bdimcheff just getting back to this. Talking about some design options in #ark-dr in the Kubernetes slack.

**Comment by ncdc** [comment]
@ajbouh it's not currently on the roadmap. If we decide to proceed, we need to find a design that allows for both the current tarball approach and a git approach to work easily, without a lot of `if/else` blocks.

**Comment by bdimcheff** [comment]
for the time being, I've settled on using kube-backup to snapshot the yamls hourly and then running ark less often to do a "full" backup... it's been working pretty well for me for the last 6 weeks or so.

**Comment by ajbouh** [comment]
@bdimcheff, have you thought about (or seen) any continuous options? That is, a system that will keep a live backup of yamls as they are updated?

**Comment by skriss** [comment]
Thanks for this request. We are not currently prioritizing this item within our roadmap, and as such will be closing out the issue. Please feel free to reach out as needed in this issue or a new one.
