### ISSUE TITLE
Disallow `ark create backup` when `restoreOnlyMode: true`

### ISSUE THREAD

**Issue by jrnt30** [heptio/velero#357]
I inadvertently deployed a cluster spec with `restoreOnlyMode: true`.  When I attempted to conduct a backup, it seemingly succeeded however none of the PV/PVCs were actually backed up due to them not being available. 

Does it make sense to allow a backup to proceed in a `restoreOnlyMode` cluster?

**Comment by ncdc** [comment]
I'm assuming its status.phase just stayed at `New`?

**Comment by jrnt30** [comment]
If I recall correctly, yes. I can replicate  tomorrow but I believe it was new but present in S3

**Comment by ncdc** [comment]
I would expect the phase to be New and it not to be in S3

**Comment by rosskukulinski** [comment]
Can there be more than one Ark controller deployed within a cluster?  If so, how would the Ark client know whether the server is configured for restoreOnlyMode?

**Comment by rosskukulinski** [comment]
@jrnt30 Thanks for the additional detail and sorry for any confusion - my comment around multi-controllers was more forward thinking around solution options.  

I 100% agree that the Ark provide some UX behavior to prevent attempting a backup when the server is in `restoreOnlyMode`.

**Comment by ncdc** [comment]
> Can there be more than one Ark controller deployed within a cluster?

If someone scales the ark deployment to 2 or more replicas, there would be multiple controllers.

FYI my plan for `restoreOnlyMode` is to move it from the `Config` to the `BackupTarget` (name TBD), but we'll still have the same issue. We can have `ark backup create` fail if it can detect that restore-only mode is in effect. We must also add logic to the server to set the backup's status to `FailedValidation` (because users can `POST` a backup directly to the k8s apiserver).

**Comment by ncdc** [comment]
It's now a server flag: `--restore-only`. From what I understand, the plan is to add `restoreOnly` to the `BackupStorageLocation` object and remove the server flag as part of the ownership/replication story.

**Comment by skriss** [comment]
With #1517 we've deprecated the `--restore-only` flag and replaced it with the ability to put individual BackupStorageLocations into read-only mode.  If a BSL is in read-only mode, any backups attempted against that BSL will fail validation with a descriptive error message.  I'm considering this issue resolved.
