### ISSUE TITLE
Support wildcards for --include-resources and --exclude-resources

### ISSUE THREAD

**Issue by sands6** [heptio/velero#373]

**Comment by sands6** [comment]
ark backup create test --include-resources *.acme.com

This wildcard support for resources is not supported right now and would be helpful to open a feature request in regards to this.

**Comment by ncdc** [comment]
Thanks @sands6 for the feature request! I'll add a bit more detail on how it could be implemented

**Comment by ncdc** [comment]
To do this, we'd probably need to create a new struct that's a bit broader than just `collections.IncludesExcludes`. Probably something like this:

```go
type ResourceMatcher struct {
  groupWildcards sets.String
  resources *collections.IncludesExcludes
}
```

And then in the constructor, it would evaluate the user input and split wildcards from regular resources as needed.

**Comment by rosskukulinski** [comment]
If we're going to support wildcards, should we go so far as to support proper Regex?

**Comment by ncdc** [comment]
I think basic `*` wildcard matching will be a lot easier for users to use

**Comment by nrb** [comment]
To clarify a bit further, are you thinking of a single wildcard (`*`) and not wild card completion? (`mynames*`)?

**Comment by ncdc** [comment]
Right, `*.acme.com`, `foo*bar`, `foo*bar*baz.acme.com`, etc.

**Comment by kivagant-ba** [comment]
This also can be useful to ignore `*.ark.heptio.com` to do backup/restore between clusters.
