### ISSUE TITLE
Reduce import surface of plugin interfaces

### ISSUE THREAD

**Issue by ncdc** [heptio/velero#488]
If you want to write a `backup.ItemAction` plugin, for example, you have to import all of `pkg/backup`, which is probably significantly more than necessary. Let's evaluate our plugin interfaces and make sure they're in 1 or more small packages that don't have large dependency trees.

**Comment by skriss** [comment]
`pkg/backup` imports:
- `ItemAction`
- `ResourceIdentifier`
- `ResourceSelector`

`pkg/restore` imports:
- `ItemAction`
- `ResourceSelector`

`pkg/cloudprovider` imports:
- `BlockStore`
- `ObjectStore` 

It would be nice to eliminate the redundant `ResourceSelector` types in `pkg/backup` and `pkg/restore`, as well.

**Comment by ncdc** [comment]
Also consider moving `cloudprovider.ObjectStore` and `cloudprovider.BlockStore` to either their own `object*` and `volume*` packages, or create a single package that contains all the interfaces that plugin authors can potentially implement.

**Comment by carlisia** [comment]
@ncdc to confirm: those files contain only the interfaces. Do you mean "copy" the interfaces there they'd also be accessible to the authors, or also move the implementation?

**Comment by ncdc** [comment]
I was referring to having an interface-only (plus supporting types as needed) package. If you're a plugin author, you ideally only import just the code (interfaces/helpers) you need, and not other stuff too.

**Comment by skriss** [comment]
Closed by #1264!
