### ISSUE TITLE
Proposal: standardize package import names

### ISSUE THREAD

**Issue by skriss** [heptio/velero#494]
For Kube/Ark imports, since many of the packages have names like `v1`, we often give them explicit names like `corev1`, `arkv1`, etc. to disambiguate. The problem is that we have no consistency in how we do this, so every file is different.

I'm proposing a standard way of naming these across Ark. The convention would be:
```
<group><version><api | client | informer | ...>
```

So, for example:
```
import (
    corev1api "k8s.io/api/core/v1"
    corev1client "k8s.io/client-go/kubernetes/typed/core/v1"
    
    arkv1api "github.com/heptio/ark/pkg/apis/ark/v1"
)
```

Haven't ensured this will cover all cases yet, but wanted to see if folks think this is worthwhile. I don't necessarily think we need to do a one-time adjustment, but maybe we adopt this standard for new code/files we touch, and we'll eventually converge.

Please weigh in!

cc @ncdc @nrb @wwitzel3

**Comment by nrb** [comment]
I'm +1 on adopting this and cleaning up as we go

**Comment by nrb** [comment]
I'm inclined to close this as we've agreed, unless we want to close it with a PR to `CONTRIBUTING`. Thoughts @skriss ?

**Comment by skriss** [comment]
Closing issue as we've agreed on the standard and are cleaning up as we go.
