### ISSUE TITLE
Add panic recovery handlers to all server-side plugin code

### ISSUE THREAD

**Issue by ncdc** [heptio/velero#521]
If a plugin encounters a panic during execution, right now we don't get any information about what caused the panic. Instead, all we see is something like this in the Ark server log:

```
ERRO[0004] backup failed                                 error="error executing custom action (groupResource=persistentvolumeclaims, namespace=brett, name=orientdb-storage-orientdb3.0-0): rpc error: code = Unavailable desc = transport is closing" key=heptio-ark/brett15 logSource="pkg/controller/backup_controller.go:273"
```

We should add panic handlers to all server-side plugin functions so we can capture the error (and maybe the full stack trace) and return gracefully instead of crashing the plugin process.

**Comment by rosskukulinski** [comment]
@ncdc Is this still slated for v0.9.0? If not, I can move to 1.0.0 meta-milestone.

**Comment by ncdc** [comment]
Not at the moment. Maybe if we have time in the next couple of weeks.

**Comment by rosskukulinski** [comment]
Also Relates to #549 and UX when things go wrong.
