### ISSUE TITLE
Reconciliation as part of restore

### ISSUE THREAD

**Issue by saravanakumar-periyasamy** [heptio/velero#523]
Use case: in cluster migration scenario, user likes to keep the resources in `destination` clusters in sync with `source` cluster. Which means, the restore process have to delete the resources in the destination cluster if its not part of the backup.

**Comment by ncdc** [comment]
@rosskukulinski for PM review

**Comment by nrb** [comment]
xref #469

**Comment by skriss** [comment]
Closing this issue as a dupe of #469.
