### ISSUE TITLE
Find a way to share state between plugins

### ISSUE THREAD

**Issue by ncdc** [heptio/velero#575]
We have a lot of logic in `pkg/restore/restore.go` that is specific to certain resource types, such as PVCs and PVs. This is better suited in individual restore item actions, but because we need to share state across multiple types of resources (e.g. if we see something in PV X it means we need to modify PVC Y), we have it in `restore.go` with the shared state as a field on the `context`.

One possible approach could be for the Ark server to instantiate an in-memory shared data store using something such as Redis. The Ark server and all the plugins would then have access to a single shared data store they could use to share state.

**Comment by skriss** [comment]
Thanks for this request. We are not currently prioritizing this item within our roadmap, and as such will be closing out the issue. Please feel free to reach out as needed in this issue or a new one.
