### ISSUE TITLE
Add error codes, messages, and maybe stack traces to protobuf response messages

### ISSUE THREAD

**Issue by ncdc** [heptio/velero#581]
When we make a call to a gRPC plugin, such as `objectStore.PutObject()`, if the plugin returns an error, it generally gets translated by the gRPC glue code to a gRPC "unknown" error. This makes it impossible, for example, to determine if the plugin returns something like a `NotFound` error unless we parse the error message text. We should switch to using our own error codes and messages for Ark, and possibly even consider including stack traces. This will require changes to our protobuf definitions.

**Comment by ncdc** [comment]
This would help fix #308

**Comment by skriss** [comment]
Closing this based on #1300, #1301. Further enhancements to error codes/details will be tracked in separate issues.
