### ISSUE TITLE
Decide on final names for plugins

### ISSUE THREAD

**Issue by ncdc** [heptio/velero#582]
BlockStore might be overly specific. I think something with "Volume" instead of "Block" in the name would make more sense.

Also decide if we want to rename any of the others.

**Comment by ncdc** [comment]
I'm ok with BackupItemAction, RestoreItemAction, and ObjectStore. I'd like to rename BlockStore. Some options:

- VolumeSnapshotter
- VolumeSnapshotProvider
- VolumeStore
- VolumeStorage

Any other ideas?

**Comment by carlisia** [comment]
@heptio/ark-team if I don't get any strong preference I'm going to go with `VolumeStore`.

**Comment by ncdc** [comment]
I'm hemming & hawing on the "store" part of the word. In ObjectStore, it makes sense, because it's storing objects. In VolumeStore, I'm less convinced.

Kubernetes has ContainerStorageInterface (CSI). But I don't really like VolumeInterface.

Maybe VolumeProvider? Or if we really don't want to bike shed, I can live with VolumeStore (albeit a bit grumbly 😄 )

**Comment by carlisia** [comment]
Noo I'm totes willing to name it something else! Especially to a meaningful name. What you said makes sense. 

I wonder if anyone would not agree with `VolumeProvider`? It sounds good to me.

**Comment by skriss** [comment]
Agree that `Store` isn't the most appropriate.  I almost want to go back to what we originally called it in our config -- `PersistentVolumeProvider`.  Intent being to be explicit about the fact that it is for PVs only, not for pod volumes.

**Comment by carlisia** [comment]
Fwiw (and this hasn’t gone thru code review yet), this is how I have it organized now (on PR #1147):

![image](https://user-images.githubusercontent.com/16508/50990052-e97e6b80-14c5-11e9-939d-a14f35640d99.png)

**Comment by carlisia** [comment]
I'm thinking one of these two?

- VolumeSnapshotter
- VolumeSnapshotProvider

**Comment by skriss** [comment]
I'd go with `VolumeSnapshotter` out of those two. I think I'd still prefer `PersistentVolumeSnapshotter`, to clarify that it's for PVs rather than all pod volumes (especially since we also have restic, which **does** operate on pod volumes), but I'm okay with whatever the team decides.

**Comment by carlisia** [comment]
I like avoiding confusion whenever possible so I wouldn't mind the longer name `PersistentVolumeSnapshotter` for that purpose. If no one chimes in til afternoon I'll go with that then.
