### ISSUE TITLE
Figure out how to handle possible plugin naming collisions

### ISSUE THREAD

**Issue by ncdc** [heptio/velero#583]
If 2 plugins both provide a backup item action named "pod", we need to figure out how to handle the collision. Same for all other plugin types. We could potentially require all plugins to have fully-qualified names, such as `ark.heptio.com/aws` instead of just `aws`.

**Comment by ncdc** [comment]
Proposal: ark internal plugins do not need to be "namespaced". All other plugins must be so, using the format `<namespace>/<name>`, such as `foo.com/aws`. If Ark detects 2 plugins with the same name (`foo.com/aws` and `foo.com/aws`), that is an error.

**Comment by carlisia** [comment]
This is pretty simple except that I'm having trouble thinking how to differentiate between Velero and external plugins. c/c @skriss

**Comment by carlisia** [comment]
To be preemptive: should we ignore case? Would `foo.com/aws` be the same or different as `Foo.com/aws`?

**Comment by skriss** [comment]
I would name all internal plugins `velero.io/<name>` so there's no inconsistency.

**Comment by skriss** [comment]
re: case - I don't know, what do you think?

**Comment by carlisia** [comment]
That's my preference too.

re case: I think we should process all incoming names into lower case.

**Comment by skriss** [comment]
that sounds reasonable

**Comment by skriss** [comment]
Closed by #1339
