### ISSUE TITLE
Add prioritized resource list for backups

### ISSUE THREAD

**Issue by ncdc** [heptio/velero#586]
Similar to restores, backups should be able to process resources in a well-defined order.

**Comment by dymurray** [comment]
Is there some documentation around how to prioritize resources on restore?

**Comment by dymurray** [comment]
I see the default list, but It's not obviout to me how to extend this to support custom resources.

https://github.com/heptio/velero/blob/4583aa707821f5860b09b67cc091b70d504e1385/pkg/cmd/server/server.go#L440

**Comment by ncdc** [comment]
It's a flag to `velero server`: https://github.com/heptio/velero/blob/73514a003b4cdaf1feed4e0976cff5a3400e4405/pkg/cmd/server/server.go#L167

**Comment by dymurray** [comment]
Awesome, thank you @ncdc!

**Comment by skriss** [comment]
Thanks for this request. We are not currently prioritizing this item within our roadmap, and as such will be closing out the issue. Please feel free to reach out as needed in this issue or a new one.
