### ISSUE TITLE
If we allow the pod->pvc->pv flow to be disabled, try to find a way to run pre/post snapshot hooks

### ISSUE THREAD

**Issue by ncdc** [heptio/velero#591]
If we allow plugins to be disabled (#584), then we'll want to try to find a way to allow the user to run pre/post snapshot hooks. The current mechanism is:

1. Ark starts to process a pod and invokes the pre hook
1. Ark sees the pod has a PVC, so it processes the PVC immediately
1. Ark processes the PVC and finds its associated PV, so it processes the PV immediately
1. Ark process the PV and creates the snapshot
1. Ark invokes the post hook for the pod
1. Ark writes the pod json to the backup tarball

If we don't have this, we'll need some way to coordinate pre/post hooks at the pod level while somehow making sure we snapshot in the middle of the process.

cc @sleepybrett

**Comment by skriss** [comment]
Thanks for this request. We are not currently prioritizing this item within our roadmap, and as such will be closing out the issue. Please feel free to reach out as needed in this issue or a new one.
