### ISSUE TITLE
Decide if/how to allow users to change the storageclass of a PVC/PV when restoring

### ISSUE THREAD

**Issue by ncdc** [heptio/velero#595]
For example. if the original PV was hdd, and the user wants to switch to ssd. This might be part of the more generic #474.

**Comment by skriss** [comment]
Current thinking around this is that it should be an optional plugin that users can add to their deployment, and configure with a ConfigMap using a similar approach to #1311.

**Comment by blackpiglet** [comment]
According to the implementation on PR #1621, the StorageClass name mapping action can only modify the PV, PVC and STS's referenced StorageClass name, but if the mapping-from and mapping-to StorageClass's configurations have differences, the already created PVs' disks cannot change accordingly.
