### ISSUE TITLE
Create a logging interface to use instead of logrus.FieldLogger

### ISSUE THREAD

**Issue by ncdc** [heptio/velero#597]
If we do this, we'll modify every place that references a `logrus.FieldLogger` once, replacing it with our interface. Then, if we need to swap out the logging implementation, it will be consolidated to a small set of files, instead of all over the entire repository.

**Comment by skriss** [comment]
Thanks for this request. We are not currently prioritizing this item within our roadmap, and as such will be closing out the issue. Please feel free to reach out as needed in this issue or a new one.
