### ISSUE TITLE
Finalize protobuf definitions

### ISSUE THREAD

**Issue by ncdc** [heptio/velero#602]
Review all protobuf definitions as we move to 1.0. Related: #581

**Comment by skriss** [comment]
@carlisia I took a look at this - here's what I'm thinking:

- [ ] currently, `ObjectStore.proto` and `VolumeSnapshotter.proto` both use the `InitRequest` message in `Shared.proto` for their `Init` functions. Let's create two separate copies of this, one in `ObjectStore.proto` and one in `VolumeSnapshotter.proto` so they can vary independently if needed.
- [ ] let's do the same for the `AppliesToRequest` and `AppliesToResponse`, that are currently in `Shared.proto` and are used by both `BackupItemAction.proto` and `RestoreItemAction.proto`.
- [ ] as part of the previous bullet, we could create a shared message type, something like the following:
    ```
    message ResourceSelector {
        repeated string includedNamespaces = 1;
        repeated string excludedNamespaces = 2;
        repeated string includedResources = 3;
        repeated string excludedResources = 4;
        string selector = 5;
    }
    ```
    and then each `AppliesToResponse` message would just include a single field, a `ResourceSelector`.

Other than that, I don't see anything else that needs to change. WDYT?

**Comment by carlisia** [comment]
This makes sense to me. Thanks for the explanation. 👍

**Comment by carlisia** [comment]
@skriss if I copy any of the messages or methods within the same (`proto`) package, with the same name, there's a duplication conflict. I can't change the names else it won't conform to the interfaces. I'm not familiar enough with this proto stuff to know if I can split these into separate packages?

**Comment by skriss** [comment]
Discussed in team sync, but we should go with e.g. `ObjectStoreInitRequest` and `VolumeSnapshotterInitRequest` to differentiate.
