### ISSUE TITLE
RFE: Pass backup metadata to plugins.

### ISSUE THREAD

**Issue by pms1969** [heptio/velero#612]
It would be useful if Ark could pass backup metadata to it's plugins.

When working on a plugin, I found myself wanting to store PV shapshots in a similar structure; same bucket heirarchy; as Ark was using.  For me, it just makes sense to house the PV snapshots with the rest of the backup data, but even if I chose to store it in another bucket, I'd like to be able to see what backup generated the blob when navigating s3.  I recognise that's likely a breaking change to all the existing plugins :(

**Comment by ncdc** [comment]
This is a good idea. Like all of Ark, we're not at GA yet, so there will be breaking changes between now and 1.0/GA. Related to #602.

**Comment by ncdc** [comment]
@pms1969 is this something you're still interested in seeing? If so, could you please elaborate what specifically you'd like to have happen? Which plugin(s) and method(s) need modifications? What would you add?

**Comment by pms1969** [comment]
Not sure I need it any more, but it's still something I think should be added.

Specifically I was referring to the backup plugin (damn it's been so long, I can't even remember if that's what it was called).  I'm pretty sure you only need to add a metadata param to the plugin constructor. 
 That metadata in as a string in the form of json or yaml that can be decoded at any time by the consuming plugin then.

The type of data that would be handy, would be date/time of backup, path that ark is using to store it's data, backup name.... not sure how much other data there is floating around, but there's not likely to be enough to make it onerous, so the more the merrier.

Having said that, you probably then need the restore to have access to the same data, so it can figure out where it's got to go to do it's thang.

Hope that makes sense.

**Comment by skriss** [comment]
Thanks for this request. We are not currently prioritizing this item within our roadmap, and as such will be closing out the issue. Please feel free to reach out as needed in this issue or a new one.
