### ISSUE TITLE
Disallow overwriting objects in object storage

### ISSUE THREAD

**Issue by ncdc** [heptio/velero#623]
We must not overwrite anything in object storage (backup json, logs, etc). If something needs to be replaced and retain the same name, the user must delete and then recreate (e.g. delete backup `foo`, then create a new backup `foo`).

**Comment by nrb** [comment]
Some references we found that may be helpful when this is worked on:

Google Cloud Storage supports using a header to not overwrite with [Put Object](https://cloud.google.com/storage/docs/xml-api/put-object).

Azure will overwrite objects on [Put Blob](https://cloud.google.com/storage/docs/xml-api/put-object).

S3 will overwrite objects on [Put Object](https://docs.aws.amazon.com/sdkfornet1/latest/apidocs/html/M_Amazon_S3_AmazonS3Client_PutObject.htm).

Looks like the simplest method here across these 3 providers is to check object store before writing in the Ark code.

**Comment by ncdc** [comment]
What do you think if we call `backupService.GetBackup()` at the beginning of the backup process, before we do any work? If the backup exists in object storage, we record it as a validation error and stop.

**Comment by nrb** [comment]
That makes sense to me, and is probably the most general solution across providers.

**Comment by ncdc** [comment]
Ok great, I'm almost done with the code 😄
