### ISSUE TITLE
RFE: Create backup from schedule

### ISSUE THREAD

**Issue by Evesy** [heptio/velero#656]
Hi,

Similar to Kubernetes jobs `kubectl create job --from-cronjob` it would be nice to be able to manually trigger ark backups based on existing schedule definitions.

This could be useful as a quick shortcut for running backups before upgrades, maintenance etc.

e.g. `ark backup create db-maintenance --from-schedule database`

Cheers,
Mike

**Comment by ncdc** [comment]
Thanks for the idea @Evesy! We'll review and prioritize.

cc @rosskukulinski

**Comment by nrb** [comment]
> Perhaps shifting some of the data items currently in Schedule (e.g. ttl, namespaces, labels, etc) explicitly to the Backup or Restore would help.

That does happen, but at runtime when the `ScheduleController` creates a new `Backup`.

It sounds like you're wanting to separate the scheduling data from the template used to create a `Backup` (and maybe a `Restore`) - is that an accurate characterization, @rosskukulinski? If so, I would think we'd have a separate set of CRDs for the backup and restore templates that a schedule would then reference.

**Comment by ncdc** [comment]
The "quick 'n' dirty" implementation of this RFE is a client-only code change that retrieves the backup spec from the specified schedule, then creates a new backup using that spec. I think that's valuable. I'd suggest keeping this issue about how to best implement that (assuming we decide to proceed), and moving the rest of the discussion to another meta issue about schedule UX.

**Comment by nrb** [comment]
@ncdc I'm +1 to that. The separation discussion should happen elsewhere

**Comment by prydonius** [comment]
The ScheduleController is currently where the Backup is created from the Schedule (https://github.com/heptio/velero/blob/89415fecac2e6c1585b8aec7f47a668d95aba00b/pkg/controller/schedule_controller.go#L288). If we move this helper to a different package (perhaps a `pkg/backup/schedule_helpers.go` or in the new builder pkg) we can reuse it in a CLI command.

The CLI command can then fetch the given Schedule and create the Backup from it. It probably makes sense to distinguish these backups from ones scheduled by the controller, perhaps the name should be a little different (e.g. `<schedule-name>-manual-<timestamp>`) and/or a label (e.g. `velero.io/schedule-manual-run: true`).

The LastBackup time should also be updated in the Schedule spec after creating the Backup.

The ScheduleController doesn't currently check if a backup is running before triggering one (https://github.com/heptio/velero/blob/89415fecac2e6c1585b8aec7f47a668d95aba00b/pkg/controller/schedule_controller.go#L257-L259). We might need to revisit this if backups can be manually triggered, as the likelihood of backups overlapping is greater.

**Comment by skriss** [comment]
> It probably makes sense to distinguish these backups from ones scheduled by the controller, perhaps the name should be a little different (e.g. <schedule-name>-manual-<timestamp>) and/or a label (e.g. velero.io/schedule-manual-run: true).

I'm thinking that we should require the user to specify the backup name here, e.g. the CLI command would look like: `velero backup create NAME --from-schedule SCHEDULE_NAME`. I think adding a label with the source schedule name makes sense, though.

> The LastBackup time should also be updated in the Schedule spec after creating the Backup.

I don't think we need to do this - in my mind, creating a manual backup using the Schedule's backup spec shouldn't alter the execution of the schedule itself.

**Comment by prydonius** [comment]
Thanks for the feedback @skriss!

> I'm thinking that we should require the user to specify the backup name here, e.g. the CLI command would look like: velero backup create NAME --from-schedule SCHEDULE_NAME. I think adding a label with the source schedule name makes sense, though.

Ah yes, I forgot the name is specified there, agree that we don't need to generate a name here.

> I don't think we need to do this - in my mind, creating a manual backup using the Schedule's backup spec shouldn't alter the execution of the schedule itself.

Could this field change the time a scheduled backup is triggered? I assumed it was just informational, and the cron schedule isn't based on the last backup time?

**Comment by nrb** [comment]
Looks like the cron schedule will use the LastBackup.Time to schedule the next one.

See [`getNextRunTime`](https://github.com/heptio/velero/blob/master/pkg/controller/schedule_controller.go#L278)

**Comment by prydonius** [comment]
IIUC though that's only used to get the next run time greater than the last run time. The next run time should still stick to the schedule. For example, if the schedule is every hour, and I trigger it manually on the half hour (e.g. 2:30), the schedule should still run at the correct time (3:00)?

**Comment by skriss** [comment]
It depends on the cron expression - for example, the "@every 5m" descriptor will look at the last run time to determine the next one.

**Comment by prydonius** [comment]
Ah thanks, I see. In that case I agree that the schedule's LastBackup time shouldn't be updated in this case.
