### ISSUE TITLE
[Epic] Ark in automation like Continuous Integration/Continuous Deployment

### ISSUE THREAD

**Issue by rosskukulinski** [heptio/velero#662]
As a platform operator I would like to use Ark as part of my automation workflows.

**Comment by rosskukulinski** [comment]
Hi @nrb. We're trying to use [ZenHub](https://www.zenhub.com/blog/open-source/) for project tracking.  Using ZenHub, I've associated a number of Issues with this Epic card, some of which have Breaking Changes:

<img width="712" alt="screen shot 2018-07-17 at 11 00 06 am" src="https://user-images.githubusercontent.com/2746479/42825722-a200b86c-89b0-11e8-94e3-d76f14a7874f.png">

**Comment by skriss** [comment]
We're no longer using this epic issue for tracking, closing.
