### ISSUE TITLE
[Epic] Restoring an "initial configuration" to Kubernetes clusters

### ISSUE THREAD

**Issue by rosskukulinski** [heptio/velero#664]
Like golden VM images, but for the entire cluster.

Use cluster-api/HAF to stamp out clusters, then run an ark restore to apply the "golden cluster image" which might include common add-ons or components:

* cert-manager
* imagePull secrets
* auth gateway (dex, etc)

**Comment by skriss** [comment]
We're no longer using this epic issue for tracking, closing.
