### ISSUE TITLE
Auto-build documents site from master branch

### ISSUE THREAD

**Issue by nrb** [heptio/velero#698]
**Describe the solution you'd like**
Currently, adding documentation requires updating at least 2 branches - master, for making sure it's included in new versions of sites, and gh-pages within the appropriate version's directory to make sure it's published live.

Ideally, we'd auto build these with CI and not require manual cherry-picks/backports of content.

**Comment by Bradamant3** [comment]
@nrb TimH and I have been discussing this item for all Heptio OSS docs :-)

**Comment by Bradamant3** [comment]
latest plan: we'll put a complete Jekyll site in the /docs folder -- you'll still need to update a /master subfolder there, but that'll be all that's required. We'll write a script to copy the contents of /docs/master to /docs/version-X when the release is tagged, then push automatically to a Netlify build/deploy. Netlify will update /docs/master continually, with previews for PRs. This may change down the road to a Docker/Jenkins/K8s cluster deploy, but the script will remain. (Sorry, Nolan, but Blackfriday markdown makes Hugo a non-starter :-(. Maybe we can move to Gatsby, though!)

**Comment by skriss** [comment]
Now that we're using netlify this has been addressed, closing.
