### ISSUE TITLE
[Epic] Revisit Project Description & Messaging

### ISSUE THREAD

**Issue by rosskukulinski** [heptio/velero#730]
Current project description:

> Heptio Ark is a utility for managing disaster recovery, specifically for your Kubernetes cluster resources and persistent volumes.

Since launching, the Ark project has expanded its feature set to cover use-cases beyond just "disaster recovery".  For example, Ark can be used for cluster/workload migration, replication, and disaster recovery.

As the project stabilizes ahead of a 1.0 release, we should review project messaging, documentation, and tutorials to ensure we have consistent messaging.

**Comment by skriss** [comment]
Closing this out as there's been a bunch of updating to the copy around Velero. We can track further specific updates in other issues.
