### ISSUE TITLE
[Epic] Improve Ark supportability & debuggability

### ISSUE THREAD

**Issue by rosskukulinski** [heptio/velero#751]
The Ark engineering team frequently provides support to users via the [#ark-dr](https://kubernetes.slack.com/messages/ark-dr) channel on the Kubernetes Slack and through GitHub Issues.  The team also is an escalation path for Heptio's Customer Reliability Engineers working with our commercial customers.

As Ark continues to gain traction, we are seeing an increase in support requests.  This is in part because identifying failure conditions and errors in Ark is often difficult.  In addition, we may not be updating our [Troubleshooting](https://heptio.github.io/ark/v0.9.0/troubleshooting) documentation section to cover common failure conditions.

**User Stories**

As an Ark user, I would like to like to have an easy way to understand when a backup or restore has failed and why the failure occurred.

**Comment by skriss** [comment]
We're no longer using this epic issue for tracking, closing.
