### ISSUE TITLE
[Epic] Ark CLI, Server & CRD installation & upgrade mechanics

### ISSUE THREAD

**Issue by rosskukulinski** [heptio/velero#752]
**User Stories**

As a cluster operator, I would like an easy but production-ready way to install Ark within my Kubernetes cluster.

As a cluster operator, I would like to have an easy mechanism to upgrade Ark, including the Server and relevant CRDs

As a cluster operator, I would like to have confidence that my existing older Ark Backups will always work with newer Ark versions.

**Comment by cblecker** [comment]
It would be fantastic if velero's on-cluster components were managed via an operator on https://operatorhub.io/

**Comment by skriss** [comment]
We're no longer using this epic issue for tracking, closing.
