### ISSUE TITLE
[Epic] Migrate PV data to a larger PV

### ISSUE THREAD

**Issue by rosskukulinski** [heptio/velero#756]
**Describe the solution you'd like**

As a cluster operator or application operator, I would like an easy way to migrate a PersistentVolume to a larger PersistentVolume for a deployed application.  For example, my database (prometheus) is running out of storage space on its PersistentVolume.  I would like to backup the database's PV, and then restore to a new PV with a larger size.

**Comment by rosskukulinski** [comment]
Relevant discussion from ark-dr: https://kubernetes.slack.com/archives/C6VCGP4MT/p1533828657000137

**Comment by ncdc** [comment]
Related? #504

**Comment by rosskukulinski** [comment]
Some cloud providers support resizing PVCs on newer versions of Kubernetes (`beta` on 1.11) https://kubernetes.io/docs/concepts/storage/persistent-volumes/#expanding-persistent-volumes-claims, so this may be less helpful for some scenarios.

**Comment by skriss** [comment]
We're no longer using this epic issue for tracking, closing.
