### ISSUE TITLE
RFE: backup/restore AWS RDS instances 

### ISSUE THREAD

**Issue by HerrmannHinz** [heptio/velero#817]
as an cluster operator i want to be able to 
backup and restore rds instances which are associated to the aws account where ark runs in
to ensure an easy manageable workflow to provide a backup/restore strategy to my tenants. 
(also: making it work to connect to other aws accounts would be awesome) 

Additional informations: 

there is this neat project: https://github.com/sorenmat/k8s-rds
in combination with a nice way of handling backup/restore those previously created databases it could be a nice addition to each cluster operator regarding providing cloud provider managed databases instead of creating own instances within a cluster.

see this slack message: https://kubernetes.slack.com/archives/C6VCGP4MT/p1536089765000100

**Comment by skriss** [comment]
Thanks for this request. We are not currently prioritizing this item within our roadmap, and as such will be closing out the issue. Please feel free to reach out as needed in this issue or a new one.
