### ISSUE TITLE
Update go-plugin magic cookie key and/or protocol version

### ISSUE THREAD

**Issue by nrb** [heptio/velero#857]
v0.10.0 has changed the plugin API. In order to ensure a v0.9.x server doesn't try to run later plugins, we should update at least the [protocol version](https://github.com/heptio/ark/blob/master/pkg/plugin/server.go#L31) so that they will fail fast.

This may also require code changes to our examples and updating plugin docs, but I haven't dug in depth on that yet.

**Comment by nrb** [comment]
We'll hold off on this until we have more substantive changes to the API (like adding new methods or changing any signatures)

**Comment by carlisia** [comment]
Question for the @heptio/ark-team: if we bump the protocol version, none of the existing external plugins will work until they update to the new interface (and maybe something else to indicate a correspondence with the new version, but haven't looked at what that would be yet.)

The way to both bump the protocol version AND maintain backwards compatibility is to have two client implementations, one for each version.

I'm not sure how important backwards compatibility is for plugins, or how important it is to add this gatekeeping.

**Comment by skriss** [comment]
We're not attempting to maintain backwards-compatibility for this set of changes. Once we're at 1.0, that'll change, but fine to break here.

The internal plugins will work fine with this change - since they're part of the same binary.  Any externally-developed plugins will need to be recompiled with the latest code to work.

**Comment by carlisia** [comment]
If I change both the`ProtocolVersion` and the `MagicCookeyKey` (from `ARK_PLUGIN` to `VELERO_PLUGIN` we'll get this message:

![image](https://user-images.githubusercontent.com/16508/55101416-4cbd7a00-5081-11e9-9428-803bbad43447.png)

If I only change the `ProtocolVersion` we get this message:

![image](https://user-images.githubusercontent.com/16508/55101446-5e9f1d00-5081-11e9-9acc-ee4a3c7cac26.png)

Should I change both?
