### ISSUE TITLE
Failed to backup volume mounted as local using restic

### ISSUE THREAD

**Issue by dipak-pawar** [heptio/velero#932]
**What steps did you take and what happened:**
* `minishift start` 
* `git clone https://github.com/heptio/ark` 
* `git checkout v0.9.7`
* `oc create -f examples/common/00-prereqs.yaml`
* `oc create -f examples/minio/`
* `oc create -f `https://git.io/fx874
* `oc -n nginx-example annotate pod/nginx-deployment-77d8f78fcb-c8qjr backup.ark.heptio.com/backup-volumes=nginx-logs`
* `ark backup create nginx-backup --include-namespaces nginx-example`

**What did you expect to happen:**
I was expecting local volume to be backed up in restic bucket. But it's failing to back up PV.

**The output of the following commands will help us better understand what's going on**:
(Pasting long output into a [GitHub gist](https://gist.github.com) or other pastebin is fine.)

* `kubectl logs deployment/ark -n heptio-ark`
   -  https://gist.github.com/f4eb8b92812f0788028ed22116604c45
* `ark backup describe nginx-backup`
   - https://gist.github.com/d05f948e4c49429c76b1aab0b4155c95
* `ark backup logs nginx-backup` 
   - https://gist.github.com/01612a73dde9b145259860d9eca84b4c
* `kubectl logs restic-tn5v8 --namespace=heptio-ark`
   - https://gist.github.com/9f50ec786a40d7bba233e614839e7bdc

**Environment:**

- Ark version (use `ark version`): 
```bash
Version: v0.9.7
Git commit: v0.9.7
Git tree state: clean
```
- Kubernetes version (use `kubectl version`):
```bash
Client Version: v1.10.0
Server Version: v1.10.0+b81c8f8
```
- Kubernetes installer & version (`minishift version`):
```bash
minishift v1.25.0+90fb23e
```
- OS (e.g. from `/etc/os-release`): 
Fedora 27

**Comment by ncdc** [comment]
@dipak-pawar I'm fairly certain that the dynamic provisioner that Minishift uses is hostPath-based. If this is the case, that is why this isn't working. We don't support hostPath volumes for restic snapshots, as that would require us to bind mount the entire root filesystem of the node into the Ark pod. We feel this is a potential security issue, and are trying to err on the side of caution.

We'll double check and let you know.

**Comment by nrb** [comment]
If I'm reading https://docs.okd.io/latest/minishift/using/basic-usage.html#persistent-volumes and https://github.com/kubernetes/minikube/blob/master/docs/persistent_volumes.md correctly, it looks like Minishift is using hostPath volumes.

**Comment by ryall** [comment]
Had the same problem. Glad I saw this. 

Was getting the specific error: `error getting volume path on host: expected one matching path, got 0`

**Comment by ryall** [comment]
Have this same problem using `minikube`, which seems to also use `hostPath` for the `standard` `StorageClass`. 

Was seeing this error in the `PodVolumeBackup`:
`error getting volume path on host: expected one matching path, got 0`

**Comment by ncdc** [comment]
@skriss we should be able to check if a volume the user asked us to back up with restic is `hostPath`, and if so, produce a better error. WDYT?

**Comment by skriss** [comment]
Yeah, I thought we were already doing that...will take a look

**Comment by ncdc** [comment]
@skriss we do have a check for `hostPath` volumes, so this must be some subtle difference here

**Comment by ncdc** [comment]
Oh, we do a check for `pod.spec.volumes[i].hostPath != nil`, but I bet we don't have a check for pod -> PVC -> PV (hostPath)
