### ISSUE TITLE
Invalid restic repo prefix when using custom object store plugin

### ISSUE THREAD

**Issue by bashofmann** [heptio/velero#939]
**What steps did you take and what happened:**
When you have a custom object store plugin configured, the `getRepoPrefix` (https://github.com/heptio/ark/blob/master/pkg/restic/config.go#L43-L79)  method returns an invalid restic repo string and there is no way to configure ark in a way to get a valid one because `prefix` will remain empty.

This results in the following error message when creating a backup with restic:

```
 error running command=restic init --repo=:metakube-cluster-backup-fhgbvx65xg-restic:/backup-tutorial --password-file=/tmp/ark-restic-credentials-backup-tutorial462685577 --cache-dir=/scratch/.cache/restic, stdout=, stderr=Fatal: create repository at :metakube-cluster-backup-fhgbvx65xg-restic:/backup-tutorial failed: invalid backend
    If the repo is in a local directory, you need to add a `local:` prefix
```

**What did you expect to happen:**
There should be a way to configure ark to produce a valid restic repo string.

**Environment:**

- Ark version (use `ark version`):  0.9.7
- Kubernetes version (use `kubectl version`): 1.11.3

**Comment by ncdc** [comment]
@bashofmann thanks for the report! What kind of object store plugin are you using?

**Comment by bashofmann** [comment]
Basically the s3 object store but with a different signer because of https://github.com/heptio/ark/issues/811.

A potential patch for this could be

```
--- a/pkg/restic/config.go
+++ b/pkg/restic/config.go
@@ -73,6 +73,8 @@ func getRepoPrefix(config arkv1api.ObjectStorageProviderConfig) string {
                prefix = "azure"
        case GCPBackend:
                prefix = "gs"
+       default:
+               return config.ResticLocation
        }

        return fmt.Sprintf("%s:%s:/%s", prefix, bucket, path)
```

**Comment by ncdc** [comment]
Ok thanks for the info. Another possible option would be to add a method to the BlockStore plugin interface to allow it to return this information. But if your proposed patch works for you, we could certainly start there.

@skriss wdyt?

**Comment by bashofmann** [comment]
Tested it and the above patch with configuring the full restic location (`s3:https:/.../bucket`) works for us.
