### ISSUE TITLE
Ark support for Swift backend protocol

### ISSUE THREAD

**Issue by NeilW** [heptio/velero#940]
**Describe the solution you'd like**
Can Ark use restic to talk to Swift backend like the ones provided with Openstack? If not what would be required to get it working?

**Anything else you would like to add:**
restic can talk to Swift repos, but at first glance there doesn't appear to be anyway to get Ark to use them. It seems to like to talk S3.

**Comment by nrb** [comment]
Hi @NeilW,

I think Ark's restic support could back up to Swift if an S3 API layer was used. Right now, our Restic support uses the credentials for providers like S3 (and compatibility layers), GCP, and Azure inserted via the restic DaemonSet. See https://github.com/heptio/ark/blob/master/examples/aws/20-restic-daemonset.yaml, for example.

To use Swift natively, I *think* if there was a DaemonSet manifest that specified the OpenStack environment variables needed as described at  https://restic.readthedocs.io/en/latest/030_preparing_a_new_repo.html#openstack-swift, it should work, but I don't know know for sure.

I do know that backup manifests won't be sent to Swift without a Swift plugin or an S3 compatibility layer in front. We've had community interest in writing a Swift plugin, but I don't believe it's been published yet. See #119 and #528.

**Comment by tlvenn** [comment]
Hi, any idea if a plugin targeting swift has been created by the community in the end ?

**Comment by tlvenn** [comment]
> https://github.com/cisco-sso/velero-plugin-openstack

**Comment by tlvenn** [comment]
This openstack plugin should probably referenced on the [support matrix](https://velero.io/docs/v1.1.0-beta.2/support-matrix/) page.

@nrb what do you think ?

**Comment by nrb** [comment]
@drekle Is the Cisco OpenStack plugin still supported by your team?

**Comment by skriss** [comment]
Thanks for this request. We are not currently prioritizing this item within our roadmap, and as such will be closing out the issue. Please feel free to reach out as needed in this issue or a new one.
