### ISSUE TITLE
Update install docs to use `velero install` instead of in-tree YAML

### ISSUE THREAD

**Issue by skriss** [heptio/velero#952]
The install docs for our various supported platforms sometimes differ from each other for no apparent reason.  For example, for Azure we `kubectl apply` the entire example folder, whereas for GCP we don't.  

Additionally, we have a legacy numbering scheme on our YAML files that probably isn't necessary anymore and may just lead to confusion/annoyance.  Look at possibly removing that. 

cc @carlisia

**Comment by carlisia** [comment]
Good point. This ticket could be the organization phase of moving towards an install.

**Comment by nrb** [comment]
Looking at what I may do for #52, I'm thinking the following:

* YAML examples will be entirely from the repository. If YAML is needed, users can run `ark install --dry-run -o yaml` (exact args and flags not necessarily final)
* Each provider's install invocation will be with instructions for preparing the necessary provider-specific steps. I'm thinking that doing provider set up like creating buckets and IAM roles/policy is out of scope for `ark install` - it just focuses on creating the CRDs + necessary objects in the cluster, plus the deployment. I'm not sure if I care where that goes, in light of the larger docs refactor.

@Bradamant3 The two points above seem fairly minimal to me. I can discuss further, but I think those are my main concerns at the moment.

**Comment by skriss** [comment]
Now that we have `velero install`, we'll standardize by updating the install docs to use this command, and largely doing away with static sample YAML.

**Comment by skriss** [comment]
Can we close this issue now?
