### ISSUE TITLE
RFC: Backup templates

### ISSUE THREAD

**Issue by ncdc** [heptio/velero#97]
If the person taking a backup is not the same person who defines how an application is deployed to Kubernetes, they might not know _what_ resources should be backed up for said application. A way to get around this could be to allow the application author to define what to back up, without actually initiating a backup or schedule. This is a "backup template".

A backup template will likely look similar or possibly identical to a backup. The sole distinction is that templates do not cause any backups to occur. If you're creating files you can `kubectl create/apply`, you could include a `BackupTemplate` in one of them.

Here is a tentative API definition:

```go
type BackupTemplate struct {
   Spec BackupSpec
}
```

It's short and to the point. We will need to determine how to adjust `ScheduleSpec` - do we do something like this:

```go
type ScheduleSpec struct {
  Template *BackupSpec
  TemplateRef *ObjectReference
}
```

where only one of `Template` or `TemplateRef` may be specified? `Template` would function exactly as it does today, as an inline definition. `TemplateRef` would be a reference to the namespace and name of a `BackupTemplate` to use instead of having an inline definition.

Alternatively, we could remove support for the inline definition, and instead require the creation of a `BackupTemplate` object first, at which point you could create a `Schedule` that references it.

Food for thought... cc @jbeda @skriss @jrnt30

**Comment by jrnt30** [comment]
Well this is certainly an interesting idea which I had not considered.  I had though of Ark acting from an operator's perspective to "backup the cluster".  The idea of an application being able to declare it's own needs is an interesting one. 

I wonder if for the `ScheduleSpec` if it would make sense then to allow this to be an array of `TemplateRef`s then so the application could express it's backup needs and an operator could create curated sets of `BackupTemplates` for an actual backup.  

I think the granularity at which we think people will be wanting to express the backup is really key here.  If it's application centric (and something that could be part of the application's deployment in the first place) I like this a lot but there will be a somewhat significant increase in complexity for partial success/failure in that case.

**Comment by ncdc** [comment]
@jrnt30 I don't think I realized until your comment in the hooks design doc what you were saying about having an array of template refs. But I get it now, and it's an interesting idea.

**Comment by ncdc** [comment]
@jbeda how important do you think this is, feature wise?

**Comment by jbeda** [comment]
I like the idea of having a way to capture the expanding of options
necessary to specify the right way to backup an application.  I can also
see where you'd want to have a single "backup" reference a set of these.  I
feel that having it be 1:1 is probably good enough to start.  At some
point, you may want to either (a) select these with labels or (b) have a
way for a namespace to declare "instead of following the cluster wide
policy for how to backup, follow my local policy".  Then when you back up
the cluster you end up getting the right stuff on a case by case basis.

I don't have a great feel for where this fits in with other features from a
priority point of view.  My gut is that we have bigger fish to fry right
now. But it seems like a great idea.

**Comment by rosskukulinski** [comment]
I agree with @jbeda - lots of more important things to tackle in the coming months.

**Comment by skriss** [comment]
Thanks for this request. We are not currently prioritizing this item within our roadmap, and as such will be closing out the issue. Please feel free to reach out as needed in this issue or a new one.
