### ISSUE TITLE
Improve `describe` output

### ISSUE THREAD

**Issue by carlisia** [heptio/velero#987]
I'd like to:
1) move the field `Validation errors` to right after the field phase (all operations).
2) make the value for the field `Validation errors` red for all values != `none`.

![image](https://user-images.githubusercontent.com/16508/47396425-90c9de80-d6df-11e8-886e-f441db3c7bfd.png)

**Comment by prateekpandey14** [comment]
Can i take this up @carlisia ?

**Comment by carlisia** [comment]
@prateekpandey14 I want to get a 👍 from the team first, to make sure we wouldn't be breaking some standard way to output this info. c/c @heptio/ark-team

**Comment by rosskukulinski** [comment]
+1 for moving `Validation Errors` field.
-1 for adding colored output as that can easily make viewing output in automation tooling (e.g. Jenkins) confusing.

**Comment by ncdc** [comment]
@rosskukulinski colored log output can be enabled/disabled based upon the presence or absence of a TTY

**Comment by carlisia** [comment]
@rosskukulinski good idea re separating the color issue. I opened an issue to track it: https://github.com/heptio/ark/issues/1082

**Comment by nzoueidi** [comment]
> Can i take this up @carlisia ?

@prateekpandey14 are you working on this?
